CodingTrain/website

_Courses/data-and-apis/0.2-Setup.md, _Courses/data-and-apis/3.4-hiding-api-key.md, _Streams/117.2-unit-testing-ci-circleci.md, _Streams/119-solving-merge-conflicts-xor-problem.md, _Streams/124.1-linting-neuroevolution.md, _Tutorials/9-additional-topics/9.13-github-pages-p5.md, _beginners/git-and-github/1-introduction.md, _beginners/git-and-github/10-git-remotes.md, _beginners/git-and-github/2-branches.md, _beginners/git-and-github/3-forks-and-pull-requests.md, _beginners/git-and-github/4-github-issues.md, _beginners/git-and-github/5-command-line.md, _beginners/git-and-github/6-cloning-push-pull.md, _beginners/git-and-github/7-init-and-add.md, _beginners/git-and-github/8-github-pages.md, _beginners/git-and-github/9-resolving-merge-conflicts.md, _beginners/git-and-github/index.md, _beginners/index.md, _config.yml, _jekyll/includes/2-base/navigation.html, unit_testing/files.js, unit_testing/yaml.test.js
Added videos in the git and github for poets series. Linked to the p5 video in the page for video 8 but might be worth coming up with a way to add it to the series page if we want to match the playlist on youtube.
quick links:
https://thecodingtrain.com/git
https://thecodingtrain.com/github
=> Adding Pages for Git/Github Series

Courses/beginner_ml5/7.1_posenet/P5/index.html, Courses/beginner_ml5/7.1_posenet/P5/sketch.js, _Courses/ml5-beginners-guide/7.1-posenet.md
Leaving open for final video id.
=> Page for ml5 PoseNet Video

Courses/beginner_ml5/7.1_posenet/P5/sketch.js
Just fixing the PoseNet video url in the source code example.
=> PoseNet Video URL

_jekyll/includes/3-modules/code-variation-dropdown.html, _jekyll/layouts/video.html, assets/css/2-base/_footer.sass, assets/css/2-base/_navigation.sass, assets/css/3-layouts/_video.sass
Reverts CodingTrain/website#2042
=> Revert "Making Changes to video dropdown buttons"

_Courses/ml5-beginners-guide/7.1-posenet.md
Linkd demo here: https://editor.p5js.org/zulx/full/F3zhSzmUr
**Instagram:**
**Twitter:**
=> ml5.js contribution: Pose Estimation with PoseNet

_CodingChallenges/069.1-steering-evolution.md
Added contribution that has on p5 web editor. Altruism, Mating and Serialization
Live Demo: https://editor.p5js.org/tompov227/full/RZ2ZSMhDT
https://editor.p5js.org/tompov227/full/RZ2ZSMhDT
=> Adding contribution from

_jekyll/includes/3-modules/code-variation-dropdown.html, _jekyll/layouts/video.html, assets/css/2-base/_footer.sass, assets/css/2-base/_navigation.sass, assets/css/3-layouts/_video.sass
=> DropDown menu test

_jekyll/includes/3-modules/code-variation-dropdown.html, _jekyll/layouts/video.html, assets/css/2-base/_footer.sass, assets/css/2-base/_navigation.sass, assets/css/3-layouts/_video.sass
Reverts CodingTrain/website#2052
=> Revert "DropDown menu test"

_Courses/ml5-beginners-guide/7.1-posenet.md
https://editor.p5js.org/jvfe/full/Ob_jdv5Ji
**Instagram:**
**Twitter:**
=> ml5.js Contribution - Posenet: Near-sighted camera

_config.yml, assets/css/2-base/_landing-page.sass, landing-page.html
=> Adding discord cta

_CodingChallenges/149-tic-tac-toe.md
https://codepen.io/Gypsydangerous/full/oNgMevp
**Instagram:** _snyderling
**Twitter:** @jebfan101
=> added tic tac toe with dom manipulation

_Courses/ml5-beginners-guide/7.2-pose-classifier.md
I'm resubmitting a pull request for #2056 with just the markdown page so that the webpage can go live. We can sort out the linting errors and adding the code repo later. cc @gruselhaus
=> Pose Classifier Video (redoing pull request)

_CodingChallenges/115-snake-game-redux.md
https://mikekuijper.github.io/ai-snake/
**Instagram:**
mike_kuijper
**Twitter:**
=> Snake Game Contribution:  AI learns to play

CodingChallenges/CC_117_SevenSegmentDisplay/P5/sketch.js
Fixed typo in the code documentation [Segment G had been marked as A] 
**Instagram:**
**Twitter:**
=> Typo in segment G

_CodingChallenges/047-pixelsorting.md
A game where you try to capture such an image (from webcam) so that the sorting algorithm makes as little comparisons and array accesses as possible
=> Pixel sorting game with live picture

_Courses/ml5-beginners-guide/7.1-posenet.md
Link for DEMO : https://exhausted-squat-nsfw.herokuapp.com
Link for the DEMO youtube video : https://youtu.be/VqErc3hWESw
Link for github : https://github.com/phishchiang/exhausted-squat-porn
**Instagram:**
**Twitter:**
=> PoseNet Estimation : By doing squat to play the video as an incentive.

_config.yml
I know the design by humans store is still up but since the new store has been officially announced I figured it would be a good idea to update the link
=> updated merch store link

_Courses/ml5-beginners-guide/7.3-pose-regression.md
This replaces #2067, some git remote hijinks caused me to need to open up a new pull request, ooops. New video! https://youtu.be/lob74HqHYJ0
=> Pose regression

_CodingChallenges/032.1-agar.md
It's not related to agario but it is related to WebSockets
http://ticonlinetactoe.herokuapp.com/
=> First Websockets contribution

assets/css/1-tools/_vars.sass, assets/javascript/functions.js
Fixes #2050 
Sorry it took so long to get around to this. Ideally we would share sass and javascript variables but I didn't see an easy way to do it without webpack.
=> Focus Visible Fix

assets/css/2-base/_landing-page.sass
relates to #2051 
Changed colors to meet WCAG guidelines.
=> Discord Button Contrast Fix

_CodingChallenges/016-lsystem.md
Link to the project: http://www.mega-firm.com/projects/dragonCurve/index.html
**Instagram:**
**Twitter:**
=> Dragon Curve using an L-System

_CodingChallenges/133-times-tables-cardioid.md
Link to demo: https://szymon300101.github.io/TableFlow/
It's quite old video, but i found it very interesting, so i expanded the idea a bit.
**Instagram:**
**Twitter:**
=> Nowacki_Multishape_Timetable

_CodingChallenges/010.1-maze-dfs-p5.md
a rat in a maze program visualizing custom maze making and finding path using dfs
**Instagram:**
**Twitter:**
=> rat in a maze program

_CodingChallenges/010.1-maze-dfs-p5.md
used bfs to find a path between start node and end node.
**Instagram:**
**Twitter:**
=> created a path finding visualiser using bfs.

_CodingChallenges/154-tic-tac-toe-minimax.md
Minimax Algorithm also with DEPTH and DRAW adjustments
=> Tic Tac Toe MiniMax with Angular and Charts

_CodingChallenges/143-quicksort.md
https://editor.p5js.org/felix-jealous/sketches/rl2iGBVL
=> Added slow sort contribution

_CodingChallenges/151-ukulele-tuner.md
Demo : https://playmesomething.par-azar.com/
🎤 Record your voice or play the guitar 🎸, and I'll play back your melody while playing the piano 🎹.
**Link to live project, video, or image:** https://twitter.com/parazar
**Instagram:**
**Twitter:** https://twitter.com/parazar
=> A pitch detection Game

_CodingChallenges/067-pong.md
adding an example of Pong AI x Computer
**Instagram:**
**Twitter:**
=> Add one more reference

README.md
Adding discord and membership links.
=> Updating Links on README

_CodingInTheCabana/index.md
(Not sure exactly what should go here but this is a little improvement I think.)
**Instagram:**
**Twitter:**
=> Changing the language on the cabana page

_Courses/data-and-apis/0.2-Setup.md, _Courses/data-and-apis/2.1-server-side-node.md, _config.yml, _jekyll/includes/2-base/navigation.html, _more/workflow/1-introduction.md, _more/workflow/2-vscode.md, _more/workflow/3-shell.md, _more/workflow/4-git.md, _more/workflow/5-node.md, _more/workflow/6-python.md, _more/workflow/index.md
Making the workflow series easier to find and putting it under the more section. Redirect added to avoid breaking links.
=> Moving Workflow Series to More Section

CodingInTheCabana/Cabana_003_Hilbert_Curve/P5/index.html, CodingInTheCabana/Cabana_003_Hilbert_Curve/P5/sketch.js, CodingInTheCabana/Cabana_003_Hilbert_Curve/Processing/Hilbert/Hilbert.pde, _CodingInTheCabana/003-hilbert-curve.md
Starting pull request for Hilbert Curve video. Still needs the final video id (also needs to be added to comment in the web editor). Also possibly a better description.
=> Adding Page for Hilbert Curve Video

_CodingInTheCabana/index.md
> The sun out is, the birds are chirping, it's a beautiful day to code a generative algorithm. Choo choo!
=> edits edits edits

_CodingChallenges/154-tic-tac-toe-minimax.md, _CodingInTheCabana/003-hilbert-curve.md, _Courses/ml5-beginners-guide/5.2-ml5-knn-classification-2.md, _Courses/ml5-beginners-guide/6.1-ml5-train-your-own.md, _Courses/ml5-beginners-guide/7.1-posenet.md, _Courses/ml5-beginners-guide/7.3-pose-regression.md, _Courses/ml5-beginners-guide/8.1-pixels-input.md
I used the same script as in #1878 to find wrong release dates.
Especially the release date from the latest "Hilbert Curve" video is off by a year so it won't appear on the landing page.
=> Fix release dates

_CodingInTheCabana/003-hilbert-curve.md
Video of the working project: https://youtu.be/NrHzXmUjAhE
Note: it's the first time I'm adding a community contribution, so I'm not sure if I did everything correctly.
**Instagram:**
**Twitter:**
=> Added my community contribution

_CodingChallenges/051.1-astar.md
https://github.com/egegungordu/flutter_pathfinding_visualizer
**Instagram:** @egegungordu
**Twitter:**
=> Astar pathfinding: using flutter

_CodingInTheCabana/003-hilbert-curve.md
p5.js web display: https://editor.p5js.org/cbrwn/full/xKE8rHPL
p5.js web editor source: https://editor.p5js.org/cbrwn/sketches/xKE8rHPL
**Twitter:** z6v
=> Added my hilbert curve interpolation :)

_CodingInTheCabana/003-hilbert-curve.md
Main thing about this contribution is that this is whole code for calculating hilbert curve:
```
hilbert :: Int -> Trail V2 Double
hilbert 0 = mempty
hilbert n = hilbert (n-1)  # rotateBy (1/4) # reflectY <> vrule 1
<> hilbert (n-1) <> hrule 1
<> hilbert (n-1) <> vrule (-1)
<> hilbert (n-1)  # rotateBy (1/4) # reflectX
```
To add colors there's another 4-12 or so lines
**Link to output image:**
It can output to pdf, svg and others (output can be found in repo).
**Project repo:** [Project repo](https://github.com/kanashimia/Throw-Away-Projects/tree/master/FunctionalHilbert)
**Github:** https://github.com/kanashimia -- as if you didnt know
=> Add hilbert curve contribution

_CodingInTheCabana/003-hilbert-curve.md
This is a community contribution to Coding in the Cabana 3: Hilbert Curve. In this sketch on p5.js, I let the person running the sketch to be able to drive a car on an order 5 Hilbert Curve, as well as a mini-map so as not to get lost.
https://editor.p5js.org/hanxyn888@gmail.com/present/swzvW4vwK
**Instagram:**
**Twitter:**
=> Driving a Car on an order 5 Hilbert Curve

_CodingInTheCabana/003-hilbert-curve.md
"https://github.com/Darbness/Hilbert-Curve"
"https://github.com/Darbness/Hilbert-Curve"
- [X ] I would be happy to have my project shared on The Coding Train's social media!
**Instagram:**
**Twitter:**
=> "Image Rendering Curve"

_CodingInTheCabana/003-hilbert-curve.md
It's my first contribution I hope I do all right
https://codepen.io/Babouinduweb/full/xxGbyVg
**Twitter:**
https://twitter.com/tibo_officiel
=> Add my own contribution to the list

_CodingChallenges/107-sandpiles.md
https://edorfaus.github.io/coding-train-variants/CodingChallenges/CC_107_sandpiles/P5/
This is an oldie - created late June 2018, just never got around to publishing it before now. It differs from the original in several ways, but also shares a lot with it.
- [🤷] I would be happy to have my project shared on The Coding Train's social media!
=> Add contribution for Sandpiles (CC 107)

_CodingInTheCabana/003-hilbert-curve.md
Here's a link: https://editor.p5js.org/simontiger/full/2CrT12N4
It's not just the Hilbert Curve, you can make any space-filling curve on a square 2x2 or 3x3 grid you like! For example:
- Hilbert Curve
- Morton / Z-order Curve
- Peano curve
=> Adding Community Contribution 9/10 for Hilbert Curve Video!

_CodingInTheCabana/003-hilbert-curve.md
https://editor.p5js.org/D_Snyder/full/6iGNyqly
=> hilbert curve contribution

CodingChallenges/CC_103_Flames/P5/index.html, CodingChallenges/CC_103_Flames/P5/sketch.js, _CodingChallenges/103-fire-effect.md
This is a straight port of the current Processing code, making it work with as few changes as I could manage.
The most obvious and biggest differences are the index calculations for pixels arrays, and setting 4 instead of 1 entry at a time; both of which are necessary due to the different structure of these arrays.
I also halved the width/height of the canvas, because that lets it run fast enough to see that something is moving, albeit still slowly.
I can see several easy ways to optimize this code so it runs faster, but I assumed it was more important to stay as close as possible to the original, so it's easier to understand what's going on based on the video.
(Feel free to tell me if I should do/have done something differently here.)
=> Add port to p5.js of Coding Challenge #103: Fire Effect

CodingInTheCabana/Cabana_003_Hilbert_Curve/P5/sketch.js, CodingInTheCabana/Cabana_003_Hilbert_Curve/Processing/Hilbert/Hilbert.pde
Useless repetitive declaration of the variable "len" (= width / N) in a for loop (in setup function).
- For the Hilbert curve
=> len line declaration

_CodingInTheCabana/003-hilbert-curve.md
=> Contribution, 'Hilbert's Flower'

_CodingChallenges/103-fire-effect.md
https://edorfaus.github.io/coding-train-variants/CodingChallenges/CC_103_Flames/P5/
The main point of this contribution is the explanation (in [the source](https://github.com/edorfaus/coding-train-variants/blob/master/CodingChallenges/CC_103_Flames/P5/sketch.js)) of the simple optimization it does to speed up the p5.js version. I'm hoping it's explained well enough that people who followed along with the video can figure it out, even without a video showing the process, and thus can learn something in the process.
The main reason I didn't include this in the main p5.js version is that the changes, while fairly simple, are large enough that I thought they might confuse someone trying to follow along with the video.
- [🤷] I would be happy to have …
=> Add contribution to CC 103

_CodingInTheCabana/003-hilbert-curve.md
https://editor.p5js.org/D_Snyder/full/2sn_O_qb
=> hilbert curve contribution (gosper curve)

_CodingInTheCabana/002-collatz-conjecture.md
=> Collatz contribution -- hailstones

_CodingInTheCabana/003-hilbert-curve.md
https://editor.p5js.org/D_Snyder/sketches/AbO9VQMr
=> hilbert curve, dragon curve, and gosper curve with l systems

unit_testing/files.js, unit_testing/formats.js, unit_testing/yaml.test.js
Adding workflow videos back into unit testing.
Relates to #2088
=> Adding Workflow to Unit Testing

_TeachableMachine/2-teachable-game.md
Including options to restart game, only ask for camera access when clicking start and being able to use your own model without editing the source code
https://alikarpuzoglu.com/snake_ml/
- [X ] I would be happy to have my project shared on The Coding Train's social media!
**Instagram:** @watermelonson
**Twitter:** @alikarpuzoglu
=> Added a refined UI for Daniels Snake game.

_CodingChallenges/001-starfield.md
Link to demo/source here: https://www.openprocessing.org/sketch/830290
https://www.openprocessing.org/sketch/830290
https://www.instagram.com/p/B7yeuTVHF8H/
**Instagram:**
https://www.instagram.com/shoreydesigns/
**Twitter:**
=> 001 starfield contribution : rainbow stars

_jekyll/includes/2-base/navigation.html, _jekyll/layouts/faq.html, _more/faq/index.md, assets/css/3-layouts/_faq.sass, assets/css/main.sass, unit_testing/files.js, unit_testing/formats.js, unit_testing/yaml.test.js
Put the frequently asked questions page under the More section. Could easily be moved somewhere else. I based the questions on the google doc I have access to. Should be easy to change or add other questions.
Wondering if the sections make sense or not.
Planning to merge in the next day or two unless changes are suggested.
Related to #1870 
Styling:
=> Adding Frequently Asked Questions

CodingChallenges/CC_008_SolarSystemGenerator3D/Processing/CC_008_SolarSystemGenerator3D/Planet.pde
In the videos, this field was not added until challenge 9, and it is not used in the code here.
While I was at it, I also updated the header.
=> CC 8: Remove unused field in Planet class

CodingChallenges/CC_008_SolarSystemGenerator3D/P5/Planet.js, CodingChallenges/CC_008_SolarSystemGenerator3D/P5/index.html, CodingChallenges/CC_008_SolarSystemGenerator3D/P5/sketch.js, _CodingChallenges/008-solarsystemgenerator3d.md
It's as straight a port as I could manage, though some changes were necessary - like using p5.EasyCam instead of PeasyCam. I think it's pretty close overall, though.
Note that this assumes PR #2127 is OK, as it does not include the unused field that is removed by that PR.
=> Add port to p5.js of Coding Challenge 8: Solar System part 2 (3D)

_learning/ml5/6.1-train-your-own.md, _learning/ml5/6.2-save-data.md, _learning/ml5/6.3-save-model.md, _learning/ml5/6.4-regression.md, _learning/ml5/7.1-posenet.md, _learning/ml5/7.2-pose-classifier.md, _learning/ml5/7.3-pose-regression.md, _learning/ml5/8.1-pixels-input.md, _learning/ml5/8.2-cnn-1.md, _learning/ml5/8.3-cnn-2.md
Minor fix to repo paths in ml5 pages.
=> fixing links in ml5 pages to the code repos

_learning/ml5/8.3-cnn-2.md
Some updates for the second CNN video, will make public later today or tomorrow morning.
=> cnn video 2 updates

_CodingChallenges/068.1-bfs-kevin-bacon.md
https://itsjigyasu.me/graph-search-gui
**Instagram:** https://www.instagram.com/jprak_arts/
=> BFS Visualization Contribution

_learning/ml5/8.1-pixels-input.md
https://gypsydangerous.github.io/Image-Convolution-tester/
=> added image convolution contribution

_CodingChallenges/031-flappybird.md
- Demo: https://flappy-pose.glitch.me/
- Source: https://glitch.com/edit/#!/flappy-pose?path=README.md:1:0
**Twitter:** https://twitter.com/checkboxoz
=> Add Flappy Pose to Flappy Bird community contribs

CodingChallenges/CC_102_WaterRipples/P5/index.html, CodingChallenges/CC_102_WaterRipples/P5/sketch.js, _CodingChallenges/102-2d-water-ripple.md
This is a straight port - the only real differences (beyond syntax and coding style) are the use of the `pixels` array (index times 4, setting density), and the `current`/`previous` array initialization (which is a bit tricky, not sure if it needs further explanation).
=> Add port to p5.js of Coding Challenge 102: 2D Water Ripple

_CodingChallenges/065.1-binary-tree.md
https://editor.p5js.org/Jedabero/sketches/EFJIeR_n
**Instagram:** https://www.instagram.com/jedabero/
**Twitter:** https://twitter.com/jedabero/
=> Visualizing a Binary Tree Contrib: equally spaced nodes

_CodingChallenges/105-polynomial-regression-tfjs.md
Live demo here: https://giacomoschiavo.github.io/projects/polynomial-regression-tf/
Enjoy.
=> Polynomial regression contribution

_learning/ml5/5.1-knn-classification-1.md
Link to demo here: https://giacomoschiavo.github.io/projects/KNN-classifier-tf/
=> KNN Class. contribution: teachable machine clone

_CodingChallenges/134.1-heart-curve.md
PARTICULATED HEARTS ( https://editor.p5js.org/AnonymousPyro/full/Q2XUJXm5 )
This is my second Contribution to the same Challenge. 
I have also added my challenge to your Rainbow Topics for PI DAY SPECIAL
Please check that challenge it is of TWO PARTS ( if you wish to read the PART  1(https://github.com/CodingTrain/Rainbow-Topics/issues/1465) or PART 2 (https://github.com/CodingTrain/Rainbow-Topics/issues/1467) is wraps it all in a better way I would go straight to PART 2).
**Instagram:**
**Twitter:**
=> Particulate Heart addition and PI - DAY CHALLENGE

_CodingChallenges/074-clock.md
Link to demo here: https://editor.p5js.org/Morphinepill/full/UFsFBd1Z
**Instagram:**
**Twitter:**
=> 075-clock.md

_learning/nature-of-code/1.2-vector-math.md, learning/nature-of-code/1.2_vector_math/P5/sketch.js, learning/nature-of-code/1.2_vector_math/P5/walker.js
Adding page for nature of code 1.2 getting started with vector math. Code example was already added in #2131
=> Adding page for NOC 1.2

learning/nature-of-code/1.1_what_is_a_vector/P5/sketch.js, learning/nature-of-code/1.1_what_is_a_vector/P5/walker.js
Noticed that youtube links weren't added to the code for noc 1.1.
=> Adding youtube link to NOC 1.1

_learning/nature-of-code/1.2-vector-math.md
Hope to start getting these out faster! 1.2 is public today.
=> new description for noc 1.2

_CodingChallenges/148-gift-wrapping.md
Hello!!!
Here is my take on the challenge where I used vector's cross product from a spinning line with the lines created from the current point to all the other points. And I am able to find the next line to the left of the current one, when the z coordinate from the cross product equals to zero, that means the vectors are parallel.
Now, given that I'm adding 0.005 to the angle of the rotating line, per frame, there is a precision issue, and I had to make a threshold to consider parallel. That is, if the absolute value of the z vector created by the cross product is close to zero ( precision is set in the code to be less than 100 ) then, that is good enough to consider the lines parallel.
https://editor.p5js.org/arthurrc/full/OldqKcL5 …
=> Challenge #148: Gift Wrapping Algorithm 

_CodingChallenges/143-quicksort.md
https://editor.p5js.org/budzique/full/eL779ZiF
=> Added Bogoesque algorithm adaptation

_CodingChallenges/156-pi-digits.md
Using the ml5 Pitch Detector to get the pitch and looking for it in pi.
https://editor.p5js.org/Arnav-Sirigere/full/d3e6yoeA
**Instagram:** @arnavsirigere
**Twitter:** @arnavsirigere
=> Community Contribution for Peeking in π

_CodingChallenges/013-reactiondiffusion-p5.md
Link to github: https://github.com/Solidsilver/PDEProj/tree/master/Numerics
=> Reaction-Diffusion Contribution: Cuda support for faster computation

_CodingChallenges/050.1-circlepackinganimated.md
https://codepen.io/DonKarlssonSan/full/VwLxXYg
**Twitter: https://twitter.com/DonKarlssonSan**
=> Add Soap Bubble Sweeper

_learning/nature-of-code/1.4-static-functions.md
@shiffman see if the description sounds good.
=> Adding Page for NOC 1.4

_learning/nature-of-code/1.6-acceleration-vector.md, learning/nature-of-code/1.6_acceleration_vector/P5/index.html, learning/nature-of-code/1.6_acceleration_vector/P5/mover.js, learning/nature-of-code/1.6_acceleration_vector/P5/sketch.js
Page for Nature of Code 1.6 Acceleration Vector.
=> Adding page for NOC 1.6

_CodingChallenges/011-perlinnoiseterrain.md
https://github.com/Lemmings42/Coding_Challenges/blob/master/Terrain_Generation/Terrain_Loop_Lo-Res.gif
**Instagram:**
**Twitter:**
=> Community Contribution to Noise Terrain 011

_CodingChallenges/147-chrome-dinosaur.md
Chrome dinosaur game with Computer Vision
Link: https://github.com/sushantPatrikar/teachable-dinosaur
=> Chrome Dinosaur Game contribution

_learning/nature-of-code/2.1-simulating-forces.md, learning/nature-of-code/2.1_simulating_forces/P5/index.html, learning/nature-of-code/2.1_simulating_forces/P5/mover.js, learning/nature-of-code/2.1_simulating_forces/P5/sketch.js
Adding page for nature of code 2.1 simulating forces.
=> Adding page for NOC 2.1

_CodingChallenges/120-bit-shifting.md
https://unsuitable001.github.io/BitViz/
BitViz is a bit wise operation visualizer. It can visualize bit shifting, basic mathematical operations and logical operations.
**Twitter:** @unsuitable001
=> Bit Shifting Contribution: BitViz

_CodingChallenges/098.1-quadtree.md
- [X ] I would be happy to have my project shared on The Coding Train's social media!
**Instagram:**
@sueszli
**Twitter:**
=> just implemented in java

_CodingChallenges/004-purplerain.md
Example does with p5.js, with just slightly more aesthetic rain (imho), and a window .png file
link: https://editor.p5js.org/danno484/sketches/s_tE8ND4R
website where i tried a few other challenges:
http://dnkaye.com/2020_CodingChallenges.html
**Instagram:**
**Twitter:**
=> Update Purple Rain

_CodingChallenges/005-space-invaders-p5.md
demo:
https://editor.p5js.org/danno484/sketches/zzO5nmnEg
**Instagram:**
**Twitter:**
=> Space Invaders Contribution: Classic Space Invaders with p5.js

_CodingChallenges/006-mitosis-p5.md
https://editor.p5js.org/danno484/sketches/aKs1OwEpn
particle 'cells' that grown, shrink, mitostisize(?), and bounce off the edges
**Instagram:**
**Twitter:**
=> User contribution - Exponential mitosis growth

_beginners/p5js/1.1-introduction.md
Link to code : https://editor.p5js.org/Godeta/present/tInAHlbvU
**Instagram:**
**Twitter:**
=> First p5.js rectangle face

_beginners/p5js/2.1-mousex-mousey.md
Source code  : https://editor.p5js.org/Godeta/present/CFgbWpdhv
Exemple of simple objects moving.
**Instagram:**
**Twitter:**
=> Moving objects

_beginners/p5js/3.1-conditional-statements.md
Link to the code : https://editor.p5js.org/Godeta/present/DDENV3ibx
**Instagram:**
**Twitter:**
=> Bouncing ball with color changes

_CodingChallenges/147-chrome-dinosaur.md
After watching this video, I managed to start creating the replica of the master system game Alex Kidd, I'm still at the beginning, but I'm already making it available on GIT for help from the community!
**Instagram:**
**Twitter:**
=> Adding Contributions - Rodrigo Kulb

_CodingChallenges/027-fireworks.md
I created my version of beautiful fireworks animation!!
Link : https://editor.p5js.org/tusharpg/full/8XmPDsf6H
**Instagram:**
**Twitter:**
=> Adding my Contribution!

_CodingChallenges/074-clock.md
Link to demo: https://editor.p5js.org/Kubi/sketches/i9nZF5u5A
**Instagram:**
**Twitter:**
=> Clock Contribution

_CodingChallenges/046.1-asteroids-part-1.md
Adding Asteroids game with cool sound effects
https://editor.p5js.org/tusharpg/full/RL9bD0KPB
**Instagram:**
**Twitter:**
=> Added My Version of Asteroids Game

_CodingChallenges/114-bubble-sort.md
https://mansfields.org/coding_challenges/sorting_visualiser/sorter.html?algo=bubble
Includes multiple sorting algorithms, color schemes and visualisations, all using p5. Original source in Typescript
https://mansfields.org/coding_challenges/sorting_visualiser/sorter.html?algo=bubble
**Instagram:**
**Twitter:**@AlexanderM2017
=> Add sorting algorithms visualiser

_learning/nature-of-code/2.4-drag.md, learning/nature-of-code/2.4_drag/P5/index.html, learning/nature-of-code/2.4_drag/P5/mover.js, learning/nature-of-code/2.4_drag/P5/sketch.js
Adding a the page and code for Nature of Code 2.4 Drag.
=> Adding page for NOC 2.4 Drag

_CodingChallenges/005-space-invaders-p5.md
Source code : https://editor.p5js.org/Godeta/present/iItQVOprn
Or on github : https://github.com/Godeta/space-invaders-JS
**Instagram:**
**Twitter:**
=> Remastered with pictures space invaders

_CodingChallenges/124-flocking-boids.md
Contains a README.md with some programming tips, and a simple UI that lets you benchmark several implementations.
https://kreativitetno.github.io/boids_p5js/
**Instagram:**
**Twitter:**
=> Yet another boids implementation

_CodingChallenges/031-flappybird.md
Link to demo here: https://editor.p5js.org/jounger/present/AArmk7_SZ
https://editor.p5js.org/jounger/present/AArmk7_SZ
**Instagram:**
**Twitter:**
=> FlappyBird contribution: flappybird lite

_CodingChallenges/100.1-neuroevolution-flappy-bird.md
Link to demo here: https://editor.p5js.org/jounger/present/7uRyDWGvl
https://editor.p5js.org/jounger/present/7uRyDWGvl
**Instagram:**
**Twitter:**
=> 100.1 Contribution: Flappy Bird Lite - TensorFlow

_CodingChallenges/024-perlinnoiseflowfield.md
Link to demo: https://nilsde.github.io/flowfield/
**Instagram:**
**Twitter:**
=> Flowfield contribution

_CodingChallenges/064.1-forward-kinematics.md
Video demo:
- https://www.reddit.com/r/Python/comments/g2njfz/hexapod_robot_simulator_with_only_numpy_and/
There are also a lot of gifs in the README of the repository itself. Thanks! 💖
- https://github.com/mithi/hexapod-robot-simulator
**Instagram:** https://www.instagram.com/minimithi/
=> Add my Hexapod Robot Simulator Project

_CodingChallenges/063.1-unikitty-flag.md
Using the  Cloth Simulation coding challenge to simulate a net that hangs from the letters of a word.
the coordinates for each letters are generated using this coding challenge: https://editor.p5js.org/codingtrain/sketches/VDLbnxyQe
Here you can find the source code for the simulation: https://github.com/loresalm/Cloth_Simulation_fishnet
**Instagram:**
**Twitter:**
=> adding a contribution

_CodingChallenges/008-solarsystemgenerator3d.md
https://editor.p5js.org/danno484/sketches/EOChmqoJX
3D solar system, but used different object structures and rotation menthods than in the video, and has slightly different features (rings, mostly-in-plane orbits, ect
https://editor.p5js.org/danno484/sketches/EOChmqoJX
**Instagram:**
**Twitter:**
=> Community Contribution - first

_learning/nature-of-code/2.5-gravitational-attraction.md, learning/nature-of-code/2.5_gravitiational_attraction/P5/attractor.js, learning/nature-of-code/2.5_gravitiational_attraction/P5/index.html, learning/nature-of-code/2.5_gravitiational_attraction/P5/mover.js, learning/nature-of-code/2.5_gravitiational_attraction/P5/sketch.js
Page for Nature of Code 2.5 - Gravitational Attraction.
=> Adding Page for Nature of Code 2.5

_CodingChallenges/009-solarsystemgenerator3d-texture.md
https://editor.p5js.org/danno484/sketches/2NwiMyhxA
Made quite differently and looks slightly different from Schiffman's version:
-has rings
-sun rotates
-orbits are mostly in one plane (like our galaxy)
https://editor.p5js.org/danno484/sketches/2NwiMyhxA
**Instagram:**
**Twitter:**
=> Community Contribution - simple 3d solar system with textures

_CodingChallenges/035.1-tsp.md
- https://medium.com/@mithi/genetic-algorithms-in-rust-for-autonomous-agents-an-introduction-ac182de32aee
- https://github.com/mithi/rusty-genes
**Instagram:**
https://www.instagram.com/minimithi/
=> Add genetic algorithm written in Rust

_CodingChallenges/067-pong.md
Link to source code: https://github.com/CleverEngage/pong
**Instagram:**
**Twitter:**
=> Pong contribution: by OOP

_CodingChallenges/027-fireworks.md
link: https://editor.p5js.org/Supriyo/full/2_88sdlhE
**Instagram:**
**Twitter:**
=> Kali Puja FireWorks

_GuestTutorials/004-emily-xie-matrix-digital-rain.md
=> Matrix Rain In Processing

_CodingChallenges/067-pong.md
Game where you control, the racket with the webcam using your hands
**Instagram:**
**Twitter:**
=>  Adding a pong webcam reference

_CodingChallenges/021-mandelbrot-p5.md
Burning Ship: a famous fractal based on the Mandelbrot Set Formula...
**Instagram:**
**Twitter:**
=> The Burning Ship fractal

_CodingChallenges/124-flocking-boids.md
Hello dear Coding Train community,
I would like to share this flocking sketch with emojis.
**Link to live project:**
https://editor.p5js.org/jcponce/present/ECrShIcB8
**Twitter:**
[@PonceCampuzano](https://twitter.com/PonceCampuzano)
=> Emojis flocking

_CodingChallenges/001-starfield.md
That's my first pull request and I really loved the project!
Just some small changes like:
1: Backward
2: Rotation
3: Mouse control rotation and speed
4: Keyboard control rotation and speed
5: Random colors for the stars
6: Removed the line ( I think you can do the same effect with enough speed)
**Instagram:**
**Twitter:**
=> Added my simple version

CodingInTheCabana/Cabana_004_worley_noise/P5/index.html, CodingInTheCabana/Cabana_004_worley_noise/P5/sketch.js, CodingInTheCabana/Cabana_004_worley_noise/Processing/worley_noise_cabana/worley_noise_cabana.pde, _CodingInTheCabana/004-worley-noise.md
@shiffman Should we also include the code from the live stream or visualization?
=> Worley Noise - Coding in the Cabana Page

_CodingInTheCabana/004-worley-noise.md
[Full view](https://codepen.io/Alca/full/PoPePoJ)
[Source](https://codepen.io/Alca/pen/PoPePoJ)
This is made using my custom p5.js-like canvas library.
**Twitter:** AlcaMagic
=> Add Worley Noise contrib - Alca

_CodingChallenges/094.1-2048.md
Hello, I just wanted to update my old contribution with my new username and working links :).
=> Update CC094 contribution with new name and links

_CodingChallenges/002-mengersponge.md
You can enter inside it, wow!
**Instagram:**
**Twitter:**
=> Added few cool things!

_CodingInTheCabana/004-worley-noise.md
https://editor.p5js.org/D_Snyder/full/3kC74c8w6
**Instagram:**
**Twitter:**
=> added another worley noise contribution

_CodingInTheCabana/004-worley-noise.md
Hello Coding Train community,
I am very exited to share my first sketch in this section, Coding in the Cabana.
Thank you for your amazing work!
**Link to live project**
[https://editor.p5js.org/jcponce/present/qUWkfuHLg](https://editor.p5js.org/jcponce/present/qUWkfuHLg)
**Twitter**
[@PonceCampuzano](https://twitter.com/PonceCampuzano)
=> Worley Noise pixelated

_jekyll/includes/3-modules/link-list.html
I found more cases of a tags having a bad target and fixed it
=> fixed more a tag target bugs

_CodingInTheCabana/004-worley-noise.md
here is a link to my contribution
https://editor.p5js.org/greggelong/full/4EMqsUDZG
**Instagram:**
**Twitter:**
=> Add Greg Kreisman contribution

_CodingChallenges/003-snake-game-p5.md
**Instagram:**
**Twitter: @cassiofb_dev**
=> Added yet another version!

_CodingInTheCabana/004-worley-noise.md
=> Update 004-worley-noise.md with my Cell Division simulation

_CodingInTheCabana/004-worley-noise.md
https://editor.p5js.org/KobeL/present/A7eDZ49Rz
**Instagram:**
**Twitter:**
=> Community contribution Kobe L.

_CodingInTheCabana/004-worley-noise.md
Link to source code: https://github.com/CShatto99/MyProjects/blob/master/animatedWorleyNoise/animatedWorleyNoise.pde
**Instagram:**
**Twitter:**
=> Animated Worley Noise in O(n^2)

_CodingChallenges/004-purplerain.md
=> The drops can be attracted by the mouse

_CodingChallenges/004-purplerain.md
Though the site is working, I messed the link order, sorry.
**Instagram:**
**Twitter:**
=> Link change

_CodingInTheCabana/004-worley-noise.md
https://violetcraze.github.io/worley-mirror/
https://github.com/violetcraze/worley-mirror
=> Adding Community Contribution to Worley Noise

_beginners/p5js/2.1-mousex-mousey.md
creating led digital segment numbers with graphic rectangles - then moving them around using the mouse  
Link to demo :  https://editor.p5js.org/serup/full/j0ylff1PS
**Instagram:**
**Twitter:**
=> createGraphics contribution: moving numbers

_CodingChallenges/001-starfield.md
- [+] I would be happy to have my project shared on The Coding Train's social media!
**Patreon:**
https://www.patreon.com/thienxxn
=> Added Starfield in Processing/Python by thienxxn

_CodingChallenges/002-mengersponge.md
**Patreon:**
https://www.patreon.com/thienxxn
=> Added "Menger sponge via Processing/Python"

_CodingChallenges/011-perlinnoiseterrain.md
https://editor.p5js.org/danno484/sketches/7DJW-j-C9a
https://editor.p5js.org/danno484/sketches/7DJW-j-C9a
**Instagram:**
**Twitter:**
=> Community Contribution - Tron riding Perlin Noise Terrain

_learning/nature-of-code/1.1-what-is-a-vector.md
link to notebook: [https://observablehq.com/@eesur/what-is-a-vector](https://observablehq.com/@eesur/what-is-a-vector)
thank you! looking forward to next tutorial :)
**note**: btw the link to contribute / 'add your own' takes you to the wrong github page (goes to ML5 folder)
**Twitter:** @eesur
=> add contribution to 1.1_what_is_a_vector

_learning/nature-of-code/1.2-vector-math.md
source: https://observablehq.com/@eesur/getting-started-with-vector-math
**note**: link to add your own is going to ml5 folder
thank you :)
**Twitter:** @eesur
=> #1.2 using factory function contribution

_CodingInTheCabana/004-worley-noise.md
https://editor.p5js.org/gelami/sketches/W2r9UH2j3
https://editor.p5js.org/gelami/full/W2r9UH2j3
Hello! Here's my implementation of an animated Worley Noise. I used a spatial hash grid to lessen the number of searches done (though it might cause weird artifacts sometimes). Could probably be done faster with a kd-tree (?). Anyways, thanks
=> Community Contribution - Animated Worley Noise

_learning/ml5/2.1-transfer-learning.md
Demo -> https://editor.p5js.org/Lets_A_Code/sketches/_swz04pem
=> Contribution to Gravity Sim

_learning/nature-of-code/1.3-random-vector.md
link: [https://observablehq.com/@eesur/a-random-vector](https://observablehq.com/@eesur/a-random-vector)
**note** : link to add your own goes to ML5 folder instead of https://github.com/CodingTrain/website/edit/master/_learning/nature-of-code/1.3-random-vector.md
thank you :)
**Twitter:** @eesur
=> #1.3 random vectors contribution

_CodingChallenges/149-tic-tac-toe.md
Link to demo here: https://editor.p5js.org/wmrsp/full/WvUMYJefz
https://editor.p5js.org/wmrsp/full/WvUMYJefz
**Instagram:**
**Twitter:**
=> Added my version of the coding challenge

_CodingChallenges/076-10print.md
Implemented 10Print using vanilla JavaScript with TRIANGLES
Characters used are
"\u25B3", "\u25B2","\u25B6","\u25BC","\u25BD","\u25C0","\u25C1","\u25E2","\u25E3","\u25E4","\u25E5"
**Image:**
**Instagram:**  https://www.instagram.com/ashik.paul/
**Twitter:**
=> 10Print using JavaScript

_CodingChallenges/051.1-astar.md
Added a link to my own maze visualisations inspired by this project
https://www.mikekotte.nl/projects/maze-generation-and-solving
**Instagram:** mike.kotte
=> Community Contribution - A* pathfinding

_CodingChallenges/011-perlinnoiseterrain.md
Link here: https://codepen.io/leimapapa/full/oNjQLBP
**Instagram:**
**Twitter:**
=> Perlin Noise Terrain contribution: p5.js version

_CodingInTheCabana/004-worley-noise.md
This is the link to the source https://github.com/Susul-1312/worleyboids
**Link to live project, video, or image:** https://github.com/Susul-1312/worleyboids I dont know how to make it run in the browser
**Instagram:**
**Twitter:** @Susul90163869
=> Worley Noise contribution: Boids controlling the points

_CodingChallenges/035.1-tsp.md
I added my version of the TSA !
**Instagram:**
**Twitter:**
=> Mathieu 'Millefeuille' Labourier Contribution

_CodingChallenges/007-solarsystemgenerator.md
=> One more contribution

_CodingChallenges/005-space-invaders-p5.md
=> Added my funny version with paint sprites lol

_CodingChallenges/006-mitosis-p5.md
=> One more version 🥳

_CodingChallenges/149-tic-tac-toe.md
=> Tic Tac Toe: with lines

_CodingChallenges/013-reactiondiffusion-p5.md
Diffusion Simulation with Rainbows and mouse click seeding
https://editor.p5js.org/danno484/sketches/rhNcFsGoA
https://editor.p5js.org/danno484/sketches/rhNcFsGoA
**Instagram:**
**Twitter:**
=> Diffusion Simulation with Rainbows and mouse click seeding

_CodingChallenges/154-tic-tac-toe-minimax.md
I have made this Tic Tac Toe game using Minimax algorithm, and by placing a bunch of images on the canvas. Every time the user clicks on a valid board position, a heart image is displayed which is chosen randomly from an array of heart images (to give it a realistic feeling). After that the bot places its move using a cross image which is again a random image from an array of cross images.
https://editor.p5js.org/ssmkhrj/full/JzpBW6cxO
=> Tic Tac Toe Contribution: Made with only Images.

_CodingChallenges/078-simple-particle-system.md
I have created a vibrant and colorful flower pot, which is a very famous cracker that is burnt in the festival of Diwali in India. It is also know as Anaar in Hindi. I have made it look like the sparks (or particles) go up from the source and then they lose their acceleration and come down and eventually disappear.
https://codepen.io/ssmkhrj/full/OJMNmJJ
**Instagram:** https://www.instagram.com/ssmkhrj/
=> Simple Particle System Contribution: Flower Pot

_CodingChallenges/124-flocking-boids.md
Hi, I'd like to contribute my take on the flocking coding challenge, slightly over-engineered. 
The post linked below contains a demonstration of flocking written in p5.js and videos with the actual 3D outputs of the c++ code I wrote (see the first link below).
linked post with outputs: https://vojtatom.cz/flocking
linked source: https://github.com/vojtatom/flocking-cpp
**Instagram:** @vojtatom (private account, for public posts I use twitter, although I don't mind being tagged/followed by new people on Instagram)
**Twitter:** @vojtatom
=> Flocking contribution (c++ compute shaders + spatial structures)

_CodingChallenges/114-bubble-sort.md
I have created a Bubble Sort Visualizer where the active indices that are being checked for swaps are shown in Green color. And the numbers that have been placed correctly are shown in blue color. Also, added some width to the bars and also these widths can be tweaked by the user, using the slider that is present on the top left corner of the screen. This will unable the user to see bubble sort for varying lengths of the array and observe how the time taken by bubble sort increases quadratically with increase in the length of the array.
http://codepen.io/ssmkhrj/full/WNroXOo
**Instagram:** https://www.instagram.com/ssmkhrj/
=> Community Contribution - BubbleSort Visualizer

_CodingChallenges/042.1-markov-chains.md
=> Community Contribution

_CodingChallenges/067-pong.md
Editor link: https://editor.p5js.org/gustavo.gsmn/sketches/pu9rQeanT
Fulsscreen link https://editor.p5js.org/gustavo.gsmn/full/pu9rQeanT
**Instagram:**
**Twitter:**
=> Single Player Pong Contribution

_CodingChallenges/065.1-binary-tree.md
https://editor.p5js.org/pazatico/full/NbmPQEfmx
=> A contribution to display big binary trees.

_CodingChallenges/009-solarsystemgenerator3d-texture.md
=> Contribution in cc-009

_CodingInTheCabana/003-hilbert-curve.md
I couldn't resist the pun so I turned the algorithm into an R package: hilbeRt. It also as a pretty animation.
[animation](https://github.com/jannikbuhr/hilbeRt#example)
**Twitter:**
jannikbuhr
=> Community contribution to 003-hilbert-curve

_CodingChallenges/001-starfield.md
Link to demo here: https://forkphorus.github.io/app.html?id=404000997
**Instagram:**
**Twitter:**
=> Shoot the stars in Scratch

_CodingChallenges/001-starfield.md
Adding my version of Starfield effect using Vanilla Javascript that changes speed and color on mouse scroll. 😁
**Instagram:** https://www.instagram.com/ashik.paul/
**Twitter:** https://twitter.com/ashikpaul19
Thank you so much @shiffman. Learnt a lot from this challenge. 😍
=> Adding my version of Starfield effect

_CodingChallenges/078-simple-particle-system.md
The previous link to my contribution does not exist anymore, it was a Codepen link, and I had to delete it for some reason. I have updated the link of the contribution.
https://codepen.io/ssmkhrj/pen/gOPmBBz
=> Updated the link for my contribution

_CodingChallenges/051.1-astar.md, _CodingChallenges/068.1-bfs-kevin-bacon.md, _CodingChallenges/114-bubble-sort.md, _CodingChallenges/115-snake-game-redux.md
**Changes:**
* Updated my old website link for Challenge # 114 and # 115
Old PR link: https://github.com/CodingTrain/website/pull/756
* Added new links for challenge # 51, # 68
* 51
https://subeshbhandari.com/app/graph-search/a-star
* 68
https://subeshbhandari.com/app/drawable-graph/bfs
* 114
https://subeshbhandari.com/app/sorting/bubble-sort
* 115
https://subeshbhandari.com/app/games/snake-game
**Instagram:**
**Twitter:**
https://twitter.com/subeshb1
=> Community Contribution #51, #68, #114, #115

_CodingChallenges/022-juliaset.md
https://elizabethhudnott.github.io/algorithmic-art/background/?gen=julia-set
**Instagram:**
**Twitter:**
=> Add Elizabeth's Julia Set contribution

_CodingChallenges/010.1-maze-dfs-p5.md
Choose the shape of your maze.
https://editor.p5js.org/pazatico/full/-h8q01a1I
**Instagram:**
**Twitter:**
=> Variation on maze generator challenge

_CodingChallenges/071-minesweeper.md
Not as pretty as Sayan Goswami's, but I did implement a marking system. I would be honored to be included in the list; it will be my first contribution after years of YouTube enjoyment. Recently worked mostly with pygame, but am also eager to work on a coding challenge in P5.js again.
https://github.com/stemvork/quickle/blob/master/minesweeper/screenshot.png
**Instagram: stemvork**
=> Community contribution: Marksweeper by stemvork

_CodingChallenges/010.1-maze-dfs-p5.md
maze :https://bishoy-magdy.github.io/Algorithm-and-Data-Structure-Visualization/Backtracking/Maze/maze.html
=> maze generator algorithm

_CodingChallenges/057-mapping-earthquake-data.md
Provided links no longer works and the user has removed this repository from his account. 
hosted URL
Resource
Hope this helps
=> Invalid link.

_CodingChallenges/010.1-maze-dfs-p5.md
So, in this project the user can visualize the maze being generated and also play that maze using arrow keys or the on screen buttons. Also, the user can toggle the visualization of maze generation.
https://codepen.io/ssmkhrj/full/bGEROmp
=> Community Contribution for Maze Generator

_CodingChallenges/064.1-forward-kinematics.md
40 second demo: https://www.youtube.com/watch?v=FxjfTUj2Dk0
live app: hexapod.netlify.app/
source code readme: https://github.com/mithi/hexapod
**Instagram:**
https://www.instagram.com/minimithi/
=> Add Hexapod Robot Visualizer with Javascript

_CodingChallenges/055-roses.md
A vanilla JavaScript version of Mathematical rose patterns.
[DEMO](https://ashik-flower.glitch.me/)
**Instagram:** https://www.instagram.com/ashik.paul/
**Twitter:** https://twitter.com/ashikpaul19
Thank you 😍
=> Adding version of Mathematical rose patterns

_CodingChallenges/075-wikipedia-api.md
Looks like the project has been deleted by the user.
Hosted URL
Source Code
Thank you
=> Project does not exist

assets/css/3-layouts/_guide.sass
Before left, new right
[Imgur](https://i.imgur.com/IkEmDKX.png)
=> improve miniature, on mobile in guide

_CodingChallenges/143-quicksort.md
source code: https://github.com/shubh67678/sorting-visualizer
live demo : https://peaceful-archimedes-611715.netlify.app
(Also thanks for your videos. You are awesome!)
**Instagram:**
**Twitter:**
=> Added my project to the list with links

_CodingChallenges/057-mapping-earthquake-data.md
A site that shows recovery rate verses active cases of on a map.
[DEMO](https://ashikpaul.github.io/Recoveries/)
**Instagram:** 
https://www.instagram.com/ashik.paul/
**Twitter:**
https://twitter.com/ashikpaul19
This project may be silly, but I learnt a lot. Thank you so much @shiffman. Never knew using a map was this easy.
=> Adding a map related project

CONTRIBUTING.md
Changed commmunity to community
=> Fixed a minor typo

_CodingChallenges/027-fireworks.md
Looks like the project has been deleted by the user.
[Deployed link](https://toferj.github.io/p5js/fireworks/)
[Source Code](https://github.com/toferj/p5js/tree/master/fireworks)
Thank you
=> Invalid links

_challenges/coding-in-the-cabana/005-marching-squares.md
link to project on p5 web editor: https://editor.p5js.org/greggelong/full/K8ymmGGC5
https://editor.p5js.org/greggelong/full/K8ymmGGC5
**Instagram:**
https://www.instagram.com/gregkreisman/
**Twitter:**
=> community contribution, Marching Squares

_challenges/coding-in-the-cabana/005-marching-squares.md
1. Using square contours in p5.js web editor. 
2. Using for loops instead of switch.
Thank you !
https://editor.p5js.org/fanbyprinciple/present/irH3GxBi3
**Instagram:**
fanbyprinciple
**Twitter:**
fanbyprinciple
=> Contribution: Marching Squares square contours

_CodingChallenges/030-phyllotaxis.md
[DEMO](https://ashikpaul.github.io/phyllotaxis/)
**Instagram:**
https://www.instagram.com/ashik.paul/
**Twitter:**
https://twitter.com/ashikpaul19
=> A simple spinning Phyllotaxis in vanilla JavaScript

_challenges/coding-in-the-cabana/001-maurer-rose.md
[DEMO](https://ashikpaul.github.io/Maurer-Rose/)
**Instagram:**
https://www.instagram.com/ashik.paul/
**Twitter:**
https://twitter.com/ashikpaul19
=> Maurer Rose in JavaScript

_challenges/coding-in-the-cabana/005-marching-squares.md
=> Added my inspired project

_challenges/coding-in-the-cabana/005-marching-squares.md
Link to a screenshot: https://github.com/Krafpy/Marching-Cubes/blob/master/screenshots/screenshot1.PNG (see screenshots folder for more pictures)
Link to the github repo: https://github.com/Krafpy/Marching-Cubes
=> Marching Squares contribution: C++ 3D Marching Cubes

_CodingChallenges/012-lorenzattractor.md
Hi, I would like to share this new Lorenz attractor with butterflies flying around.
Thanks! :)
https://editor.p5js.org/jcponce/present/JH7nMvdIC
**Instagram:**
**Twitter:**
https://twitter.com/PonceCampuzano
=> A new Lorenz attractor with butterflies

_challenges/coding-in-the-cabana/004-worley-noise.md
https://github.com/hcoffey1/worley
**Instagram:**
**Twitter:**
=> Adding link to Worley Noise contribution.

_jekyll/includes/3-modules/back-to-top-button.html, assets/css/4-modules/_back-to-top-button.sass
As requested in #2444   
I didn't address the fourth point, as I'm not good at designing these and there was a little conversation about it [here](https://github.com/CodingTrain/website/pull/1881), maybe someone else can take that one if needed.  
Accessibility shoud be fine now. @phucduong86 can you take a look and make sure?
=> add a11y to back to top button

_CodingChallenges/022-juliaset.md, _CodingChallenges/030-phyllotaxis.md, _CodingChallenges/055-roses.md, _CodingChallenges/134.1-heart-curve.md
https://mathematical-art.github.io/?gen=graphing-calculator&preset=rose
https://mathematical-art.github.io/?gen=graphing-calculator&preset=heart
**Instagram:**
**Twitter:**
=> Elizabeth's animated heart, rose pattern and new website location

_CodingChallenges/003-snake-game-p5.md
https://www.youtube.com/watch?v=r7KOiF8WrQ8
https://github.com/ThomasW2005/snake/blob/master/snake.exe
https://www.youtube.com/watch?v=r7KOiF8WrQ8
**Instagram:** https://www.instagram.com/thomas_weichhart/?hl=de
**Twitter:** https://twitter.com/WeichhartThomas
=> Snake in c

_challenges/coding-in-the-cabana/005-marching-squares.md
A "slime-like" creature made from linearly interpolated Marching Squares on a modified Metaball infrastructure with random behaviors.
Link to Demo: https://editor.p5js.org/BasidiomyCody/present/k3BeoweuV
Link to Source: https://editor.p5js.org/BasidiomyCody/sketches/k3BeoweuV
**Instagram:**
**Twitter:**
=> Marching Squares Contribution

_CodingChallenges/085-the-game-of-life.md
URL : https://sdtrain.github.io/conway-game-of-life/
Clickable 20 x 30 grid with options for adding delay and no. of time-steps
https://sdtrain.github.io/conway-game-of-life/
**Instagram:**
**Twitter:**
=> Added game-of-life community contribution

_CodingChallenges/149-tic-tac-toe.md
https://editor.p5js.org/brianlong912/present/UKhywuoJe
https://editor.p5js.org/brianlong912/present/UKhywuoJe
**Instagram:**
@b_long37
**Twitter:**
@B_Long23
=> Tic-Tac-Toe Contribution: Ultimate

_CodingChallenges/124-flocking-boids.md
Source Code here: https://editor.p5js.org/TheSleepingAssassin/sketches/LVvPlIvzC
Hope you like it!
**Instagram:**
**Twitter:**
=> I am adding triangles instead of circles

Courses/programming_with_text/session11/11-06_Pop-ups_Messaging/manifest.json
**Link to the Chrome official Doc:**
[contentSecurityPolicy](https://developer.chrome.com/extensions/contentSecurityPolicy)
**Instagram:** https://www.instagram.com/sidanaanurag/
**Twitter:** https://twitter.com/anuragsidana23
=> Content security policy added in manifest

_CodingChallenges/149-tic-tac-toe.md
https://github.com/TanHongIT/JavaScript-Tic-Tac-Toe-Project
**Link to live project, video, or image:** https://github.com/TanHongIT/JavaScript-Tic-Tac-Toe-Project
**Instagram:**
**Twitter:** https://twitter.com/TanHongIT
=> Invincible Tic Tac Toe

README.md
only readme.md file is edited added the link to website and CONTRIBUTING.md file
**Instagram:**
**Twitter:**
=> Added links to website and CONTRIBUTING.md file

_CodingChallenges/065.1-binary-tree.md
I created a version of Binary Search Tree which is drawn on the canvas using Recursion. There is also ability to add nodes, search nodes and see sorted traversal path.
(I tried to implement removing nodes, but it didn't work.)
https://editor.p5js.org/dipam2006/present/_uwaomKtM
=> Interactive Visualization of Binary Search Tree

_CodingChallenges/149-tic-tac-toe.md
**Link to live project, video, or image:** https://railstictactoe.herokuapp.com/
**Instagram:**
**Twitter:** https://twitter.com/TanHongIT
=> Game Tic Tac Toe With Ruby On Rails

_CodingChallenges/146-rendering-ray-casting.md
Link: http://mortis-grimreaper.ddns.net/projects/Raycasting3DAdvAdv/
Some hints: You need to click inside the maze to set Target Location
http://mortis-grimreaper.ddns.net/projects/Raycasting3DAdvAdv/
**Instagram:**
**Twitter:**
=> Ray casting Ald with Maze Generation and A* Alg

_CodingChallenges/059-steering-text-paths.md
Link: http://mortis-grimreaper.ddns.net/projects/SteeringBehavior/
Some hints: You can change behavior by pressing arrow keys. Button click change text.
**Instagram:**
**Twitter:**
=> Steering behaviors with different behavior

_CodingChallenges/010.1-maze-dfs-p5.md
Link: http://mortis-grimreaper.ddns.net/projects/MazeGenerator2/
**Instagram:**
**Twitter:**
=> Maze Generator Recursive division method

_CodingChallenges/117-seven-segment.md
https://ivan-denisovich-py.github.io/rainbow-clock/
**Authors:**
* Bhaswar Chakraborty
* Anusha Tripathi
**Instagram:**
@bhaswar.py
(Anusha Tripathi doesn't have instagram)
**Twitter:**
@denisovich_py
@anusha_exe
=> Rainbow Clock: Because Dan likes rainbows!

_CodingChallenges/085-the-game-of-life.md
Link: http://mortis-grimreaper.ddns.net/projects/GameOfLife/
=> Game of Life with Terminal Commands

_CodingChallenges/074-clock.md
Added my Contribution on the Clock visualization Coding challenge
**Instagram:**
**Twitter:**
=> Contribution on Clock Coding Challenge

_CodingChallenges/112-3d-rendering.md
- https://github.com/mithi/hello-tiny-box
- https://mithi.github.io/hello-3d-world/
**Instagram:**
@minimithi
http://instagram.com/minimithi
=> Add two "3D Rendering" projects

_CodingChallenges/028-metaballs.md
Implementation of metaballs written in Processing and GLSL (shader). Each metaball has its own color. See https://www.youtube.com/watch?v=LZfmCuEPRIM for demo.
=> Metaball contribution: individually-colored w/ GLSL

CodingChallenges/CC_084_Word_Definition_Extension/JavaScript/manifest.json
Extension failure fix
**Link to the Chrome official Doc:**
[contentSecurityPolicy](https://developer.chrome.com/extensions/contentSecurityPolicy)
**Instagram:**
**Twitter:**
=> contentSecurityPolicy added in manifest

_CodingChallenges/011-perlinnoiseterrain.md
**Link to live project, video, or image:** https://youtu.be/2N-t3u2dtXs
=> Contribution: interactive and colorful terrain

_CodingChallenges/124-flocking-boids.md
Hello dear community
I would like to share another fun flocking simulation with WEBGL. 
Thanks.
https://editor.p5js.org/jcponce/present/fwsX61dRa
**Instagram:**
**Twitter:**
[@PonceCampuzano](https://twitter.com/PonceCampuzano)
=> A fun 3D flocking animation with butterflies in 3D

_CodingChallenges/051.1-astar.md
https://khalidsaifullaah.github.io/pathfinding-visualizer/
**Instagram:** khalidsaifullaah
**Twitter:** k_saifullaah
=> A* Pathfinding Algorithm contribution: included a lot more search algos

README.md
=> improved in README.md

_CodingChallenges/003-snake-game-p5.md
https://codepen.io/ssmkhrj/full/Vwapvjw
=> Add My Version of Snake Game

README.md
Will need to be removed at the end of October.
=> Adding Hacktoberfest Section on README

_CodingChallenges/074-clock.md
https://calmcoding.github.io/minimalist-watch/
**Instagram:** @milchreisjunkie
**Twitter:**
=> Integrates my minimalist clock

_CodingChallenges/149-tic-tac-toe.md
https://github.com/idea456/TicTacPro
=> Tic Tac Toe contribution: Tic Tac Pro with 2D array visualization

_CodingChallenges/004-purplerain.md
Link demo https://editor.p5js.org/ddwebdev/full/isq-7UK7f
**Instagram:**
**Twitter:**
=> Rain and snow

_CodingChallenges/001-starfield.md
Link for demo https://editor.p5js.org/ddwebdev/full/sgMgyPi79
**Instagram:**
**Twitter:**
=> Star Wars Starfield

.github/pull_request_template.md
Hopefully, this extra description will help reduce spam pull requests, and hopefully, it will give us an easier way to point people towards the rainbow poem repo.
=> added hacktoberfest description to PR template

_CodingChallenges/051.1-astar.md
https://codepen.io/ssmkhrj/full/zYvbYpK
=> Add BFS Visualizer Community Contribution

_CodingChallenges/004-purplerain.md
https://editor.p5js.org/aky91/full/IUxpPJnaK
**Instagram:**
**Twitter:**
=> Added contribution: Midnight Colorful Rain

_CodingChallenges/003-snake-game-p5.md
https://sanjana-mukherjee.github.io/Snake-Game/
=> Add Snake Game With Obstacles

_CodingChallenges/076-10print.md
Link demo here https://editor.p5js.org/ddwebdev/full/uHMOSzPo4
**Instagram:**
**Twitter:**
=> 10PRINT Rain and Snow

_CodingChallenges/136.1-polar-perlin-noise-loops.md
https://www.openprocessing.org/sketch/772904
**Instagram:**
@leithba
**Twitter:**
@leithba
=> Perlin Noise Loop contribution: Perlin Meta Rings

_CodingChallenges/076-10print.md
https://www.openprocessing.org/sketch/737761
**Instagram:**
@leithba
**Twitter:**
@leithba
=> 10 Print contribution : 10PRINT with perlin and style

_CodingChallenges/156-pi-digits.md
Live Demo here: https://iamsarthakk.github.io/P5.js/SearchPi/
=> Peeking in π with number pad

_CodingChallenges/156-pi-digits.md
A little bit late but still fun to make!
- https://pi.ejer.gq/
**Instagram:** datejer
**Twitter:** datejer
=> Add Peeking Inside Pi contribution

_beginners/p5js/1.1-introduction.md
Thank you CodingTrain for excellent videos.
Here's my first p5.js sample for fun.
Beware lots of circles!
Random circles generating pattern
Link to demo : https://phg98.github.io/phg98p5sample/
https://phg98.github.io/phg98p5sample/
source : https://github.com/phg98/phg98p5sample
**Instagram:**
**Twitter:**
phg98
=> Add Beginners Introdunction contribution #2615

_CodingChallenges/143-quicksort.md
https://github.com/Tvashta/Sort
=> Sorting Algorithms as a Color Spectrum

_challenges/coding-in-the-cabana/004-worley-noise.md
This makes use of the basic trignometry functions for achieving this
**Instagram:**
**Twitter:**
=> Updated worley noises with a ripple effect

_CodingChallenges/114-bubble-sort.md
Link to demo here: https://9nine-tails.github.io/Sorting-Algorithms-Visualized/
source code here: https://github.com/9Nine-Tails/Sorting-Algorithms-Visualized
https://9nine-tails.github.io/Sorting-Algorithms-Visualized/
=> Bubble Sort contribution: Sorting a picture

_CodingChallenges/036-blobby.md
https://www.openprocessing.org/sketch/773556
**Instagram:**
@leithba
**Twitter:**
@leithba
=> Blobbly contribution: Meta Matter

_CodingChallenges/024-perlinnoiseflowfield.md
https://www.openprocessing.org/sketch/738530
**Instagram:**
@leithba
**Twitter:**
@leithba
=> Perlin Noise Flow Field contribution : Perlin Roots

_CodingChallenges/031-flappybird.md
https://codepen.io/thinks_code/full/WNwVymq
**Instagram:** mr_thinkswell
**Twitter:**
=> Added my version of flappy bird (Slide the Rain).

_CodingChallenges/071-minesweeper.md
**Link to video**
[Video](https://github.com/guptavaibhav0/beesweeper/blob/master/BeeSweeper_video.mp4)
**Twitter:** guptavaibhav0
=> Added new community contribution

_CodingChallenges/079-number-guessing-chatbot.md
Here is the output:
https://suman98kumar.github.io/Chatbot-GuessGame/
**Instagram:**
**Twitter:**
=> Guess Game Contribution - Implemented using react

_CodingChallenges/076-10print.md
https://dzson.github.io/10PRINT/index.html
**Instagram:**
**Twitter:**
=> 10PRINT Contribution: 10PRINT with C# and Unity

_beginners/p5js/3.1-conditional-statements.md
Link: https://editor.p5js.org/Puettrick/full/oUHOZOAR3
**Instagram:**
**Twitter:**
=> bouncing ball contribution: changing colors and mouse interaction

_CodingChallenges/054.1-starpatterns.md
https://editor.p5js.org/LeithBA/sketches/Co1xJm47x
https://editor.p5js.org/LeithBA/present/Co1xJm47x
**Instagram:**
@leithba
**Twitter:**
@leithba
=> start pattern contribution: alternative version

_CodingChallenges/076-10print.md
Link to demo here : https://editor.p5js.org/amnindersingh12/full/dXrGmyFz9
This is my first pull request.😊
Have a good day !!
=> Random Colourfull Maze

_CodingChallenges/156-pi-digits.md
Demo - https://shrouded-springs-15406.herokuapp.com/
https://shrouded-springs-15406.herokuapp.com/
**Instagram:** https://www.instagram.com/praaatiik/
**Twitter:**
=> Add a web app version of the original

_CodingChallenges/031-flappybird.md
Here is a link to the demo: https://editor.p5js.org/szloszjar.marvin@gmail.com/full/jE8DQY1Zd
**Instagram:**
**Twitter:**
=> added my own version of "flappy bird"

_CodingChallenges/079-number-guessing-chatbot.md
Also updated the code to work with latest RiveScript.
=> created web editor version of RiveScript chatbot

_CodingChallenges/069.1-steering-evolution.md
https://editor.p5js.org/dummyani26/full/2kf3BgcHL
=> Evolutionary Steering Behaviour with Boids, Predators, Microbes and Hiding Places

_CodingChallenges/086-beesandbombs.md
Move the mouse over the canvas for seeing the dynamics of the cube and press any mouse button for changing the view
**Instagram:**
**Twitter:**
=> Dancing cube with mouse interaction

_CodingChallenges/007-solarsystemgenerator.md
CC 007: Solar System
https://editor.p5js.org/dipam2006/present/cH9EHZ0Wp
=> Created a p5 Port using OOP

_CodingChallenges/024-perlinnoiseflowfield.md
Adding a sine wave effect to the noise
**Instagram:**
**Twitter:**
=> Perlin noise with sine and cos waves

_CodingChallenges/011-perlinnoiseterrain.md
https://dzson.github.io/TerrainGeneration/index.html
**Instagram:**
**Twitter:**
=> Terrain Generation Contribution: Synthwave

_CodingChallenges/014-fractaltree.md
Move the mouse over the canvas to see the changing fractal trees
**Instagram:**
**Twitter:**
=> Added mouse interaction with sin and cos waves

_CodingChallenges/001-starfield.md
Link: https://worldbiomusic.github.io/star-field/.
My first pull request. Thank you!
**Instagram:**
**Twitter:**
=> can change color with speed!

_Guides/pages-contribution-guide.md
Adding a guide on making pages for the site.
=> Adding Pages Contribution Guide

_CodingChallenges/114-bubble-sort.md
https://github.com/Tvashta/Sort
=> Sorting Visualizer as a color Spectrum

_CodingChallenges/114-bubble-sort.md
[live demo](https://galelmalah.github.io/sorting-visualisations/)
**Instagram:**
**Twitter:**
=> Update 114-bubble-sort.md for hacktoberfest issue #2615

_learning/ml5/8.2-cnn-1.md, _learning/ml5/8.3-cnn-2.md
=> Fixing cnn code examples

_CodingChallenges/003-snake-game-p5.md
https://editor.p5js.org/snowcol008/full/odG4k9NG_
**Instagram:**
**Twitter:**
@AHHHHH02705128
=> Billeh Contabution

_CodingChallenges/005-space-invaders-p5.md
Hanzi Space Invaders is space invaders but instead of aliens or asteroids its all Chinese characters! This game was made as a part of several games I made for my local Chinese tuition center to teach young kids Chinese characters. The Coding Train's Space Invaders challenge was a great inspiration for me and was the baseline of this game! This game was made using p5js (with react-p5-wrapper) and React.
https://github.com/idea456/fun-mandarin-games
**Instagram:**
**Twitter:**
=> Space Invaders contribution : Hanzi Space Invaders

_CodingChallenges/003-snake-game-p5.md
Hanzi Snake Game made using p5js and React, is part of several games I made for my local Chinese tuition center to teach young kids Chinese characters. Its the classic snake game but with clouds of Hanzis and interactive background. The Coding Train's Snake challenge was also another inspiration for this game, and helped me to create this game using p5js (with react-p5-wrapper) and React.
https://github.com/idea456/fun-mandarin-games
**Instagram:**
**Twitter:**
=> Snake Game contribution : Hanzi Snake Game

_CodingChallenges/149-tic-tac-toe.md
**Link to demo here : https://amnindersingh12.github.io/Colourfull-tic-tac-toe/**
=> Adding Colourful Tic Tac Toe

_CodingChallenges/088-snowfall.md
https://marcovela.github.io/SnowAnimation/
=> Snowfall animation with static picture in background

_CodingChallenges/085-the-game-of-life.md
Regarding CodingTrain#2615
**Instagram:**
**Twitter:**
=> Adding a contribution to the game of life coding challenge

_beginners/p5js/2.1-mousex-mousey.md
Pixel to centimeter converter, and display. (version 0.01)
Link to demo here: https://editor.p5js.org/nesztorov/sketches/2ruTW9DMD
**Instagram:**
**Twitter:**
=> pixel to centimeter

_CodingChallenges/113-hypercube.md
Added a Processing sketch that projects N-Dimensional cubes onto a 2D canvas. Features an intuitive rotation selection menu and the ability to choose projection methods for individual layers.
<https://github.com/piguyinthesky/piguyinthesky.github.io/tree/main/projection/Projection>
**Instagram:**
@piguyinthesky
**Twitter:**
@AcaiPie
=> Add a contribution to Coding Challenge 113

_CodingChallenges/010.1-maze-dfs-p5.md
play: https://worldbiomusic.github.io/multiplay-maze-game/
**Blog:** 
https://blog.naver.com/ljh3047063
=> Maze Generator: 2 Player Maze Game

_CodingChallenges/071-minesweeper.md
Link to demo: https://lucid-villani-c69bfc.netlify.app/
=> Minesweeper contribution: 3D Minesweeper

_CodingChallenges/088-snowfall.md
To celebrate 🍻Hacktoberfest, beer falls from the sky
Thank you for the great challenge!
[🍻Beerfall](https://editor.p5js.org/wooooooood/full/vbIe54vYK)
**Instagram:**
g0lim
=> Coding challenge 88 Contribution

_CodingChallenges/156-pi-digits.md
**Link to Demo here :** https://amnindersingh12.github.io/two-pie/
Regarding #2615
=> Peeking Inside Pi Coding Challenge : 2Pi a.k.a Tau

_CodingChallenges/085-the-game-of-life.md
https://sidwellr.github.io/Yet-Another-Life/
**Instagram:**
**Twitter:**
=> Add community contribution to 085-the-game-of-life.md

_more/faq/index.md
=> Added Faq answer about wallpapers

_CodingChallenges/076-10print.md
I've used the concept introduced the challenge with the Canvas API and requestAnimationFrame. The script draws diagonal lines with given odds, and repeats the operation over and over to give the illusion of movement.
---
https://codepen.io/borntofrappe/pen/OJXNgeg
**Twitter:** https://twitter.com/borntofrappe
=> 10PRINT contribution: rain simulation

_CodingChallenges/030-phyllotaxis.md
Mesmerizing pattern of red and blue "breathing" phyllotaxis patterns
**Instagram:**
**Twitter:**
=> Hypnotic Phyllotaxis

CodingChallenges/CC_042.2_markov-chain-names/P5/sketch.js
would love help with going back and updating all of these! (also in the web editor). cc @violetcraze
=> fixing headers for markov chains

_CodingChallenges/149-tic-tac-toe.md
Link to demo here: https://editor.p5js.org/FEDQK/full/-Pv-iJu4j
Regarding #2615 
**Instagram:**
**Twitter:**
=> Tic Tac Toe contribution: 2 players

.github/workflows/gist.yml
This pull request is mostly to check and fix anything that broke when switching to main for the default branch.
=> Switching to Main

_learning/programming-with-text/1.3-text-input.md
Adding "1.3: Getting Text form User: Text Input - Programming with Text" video details
https://www.youtube.com/watch?v=uNQSVU0IKec
Fixes #2764
=> Added a video description of "Programming with Text"

_learning/programming-with-text/10.1-introducation.md
Adding "10.1: Introduction to Chatbots - Programming with Text" video details
https://www.youtube.com/watch?v=slmSCEho31g
Fixes #2768
=> Added a video description(10.1)

_CodingChallenges/100.1-neuroevolution-flappy-bird.md
Evolving Flappy Bird
Demo: https://editor.p5js.org/b-yogesh/present/VLRGtg84Q
Demo: https://editor.p5js.org/b-yogesh/present/VLRGtg84Q
**Instagram:**
**Twitter:**
=> Contribution: Evolving Flappy Bird

_learning/programming-with-text/3.1-the-ritajs-library.md
Add "3.1: The RiTa.js Library - Programming with Text" page and details for #2762
https://youtu.be/lIPEvh8HbGQ
=> Add Missing Pages in Programing with Text Series - vid 3.1

.gitignore, _beginners/git-and-github/index.md, _beginners/p5js/index.md, _scripts/generate-youtube-descriptions.js, package.json, unit_testing/formats.js
Adding a script to generate descriptions for YouTube videos based on web page data. May add a way to automatically use these to update YouTube if I can figure out the YouTube API or another tool. Another future project is using topics for timestamps.
=> Adding Script to Generate YouTube Descriptions

_learning/programming-with-text/3.1-the-ritajs-library.md, _learning/programming-with-text/3.2-the-nlp-compromise-library.md, _learning/programming-with-text/3.3-homework-assignments-week-3.md
Add "3.2: The "nlp-compromise" Library - Programming with Text" page and details for #2762 
Add "3.3: Homework Assignments Week 3 - Programming with Text" page and details for #2762 
https://youtu.be/tk_JGu2AbJY
https://youtu.be/XUhyfkE4BS8
=> Add Missing Pages in Programing with Text Series - vids 3.2 and 3.3

_CodingChallenges/046.1-asteroids-part-1.md
Also has additional inputs for customizing the evolution process of the AI.
Source: https://github.com/Immodal/asteroids
https://immodal.github.io/asteroids/
**Instagram:**
**Twitter: @NCImmodal**
=> Asteroids Contribution: NEAT AI and Ray Casting

_learning/programming-with-text/6.1-introduction.md, _learning/programming-with-text/6.2-homework-assignment-session-6.md
Add "6.1: Intro to Session 6: Markov Chains" page and details for #2762
Add "6.2: Homework Assignment Session 6" page and details for #2762
https://youtu.be/v4kL0OHuxXs
https://youtu.be/aq9Wf7F5e84
=> Add Missing Pages in Programing with Text Series - Session 6

_CodingChallenges/143-quicksort.md
https://github.com/Ivan-Denisovich-py/Quick-Sort-Visualisation
**Instagram:**
@bhaswar.py
**Twitter:**
@denisovich_py
=> Added a pygame version quicksort visualization

_CodingChallenges/071-minesweeper.md
https://www.youtube.com/watch?v=yCPmRfIEzZ4&feature=youtu.be
**Instagram:**
@bhaswar.py
**Twitter:**
@denisovich_py
=> Added Minesweeper with Processing.py

_learning/programming-with-text/5.2-assosiative-arrays.md
=> Add Missing Pages in Programing with Text Series - vid 5.2

_learning/programming-with-text/1.5-javascript-string-object.md
- Add "3.2: The "nlp-compromise" Library - Programming with Text" page and details for [#2762](https://github.com/CodingTrain/website/issues/2762)
- [https://youtu.be/DcoAjEZYies](https://youtu.be/DcoAjEZYies)
=> Add Missing Pages in Programing with Text Series - video 1.5

_CodingChallenges/010.1-maze-dfs-p5.md
Just linking my contribution. I've used a GCD function to scale cells & a wavy color effect.
As I said, this is a modest contribution.
**Instagram:**
**Twitter:**
=> Adding my own modest contribution

_learning/programming-with-text/1.5-javascript-string-object.md, _learning/programming-with-text/1.6-homework-assignments-week-1.md
- Add "1.6: Homework Assignments Week 1 - Programming with Text" page and details for [#2762](https://github.com/CodingTrain/website/issues/2762)
- [https://youtu.be/YTzVbuV89RE](https://youtu.be/YTzVbuV89RE)
=> Add Missing Pages in Programing with Text Series - video 1.6

_learning/programming-with-text/1.5-javascript-string-object.md, _learning/programming-with-text/5.3-homework-assignment-week-5.md
- Add "5.3: Homework Assignment Week 5 - Programming with Text page and details for [#2762](https://github.com/CodingTrain/website/issues/2762)
- [https://youtu.be/6DoJob85jE0](https://youtu.be/6DoJob85jE0)
=> Add Missing Pages in Programing with Text Series - video 5.3

_CodingChallenges/130.1-fourier-transform-drawing.md
This a project we pulled off to have a sustainable YouTube Live drawing the Hacktoberfest logo as a Fourier Epicycle using the p5.js library as a fun project.
https://youtu.be/t7VMomSOTyg
#Hacktoberfest forever
project-moonshot: https://github.com/dscnitrourkela/project-moonshot
[YouTube Live](https://youtu.be/t7VMomSOTyg)
**Instagram:**
https://www.instagram.com/dscnitrourkela/
**Twitter:**
https://twitter.com/dscnitrourkela
=> Hacktoberfest Logo Drawing YouTube Live

_CodingChallenges/117-seven-segment.md
You can change the width and the height of each segment and the space between the segments too, thanks to sliders under the canvas.
Also, there's a little animation in the beginning (a function that allows you to animate the value that's displayed a given number of times).
Link to demo: https://editor.p5js.org/NC_Productions/full/_bNJgU6kF
=> Seven-segment contribution: editable appearance

Courses/programming_with_text/session11/README.md
Fixed broken links in programming_with_text/session11/README.md
=> Broken links: programming_with_text_session11

_CodingChallenges/098.1-quadtree.md
https://dansarno.github.io/p5-pandemic-simulation/
=> Quadtree and SIR Model Visualisation

_CodingChallenges/154-tic-tac-toe-minimax.md
Link to demo: https://anjakhan.github.io/TicTacToe_Challenge/
https://anjakhan.github.io/TicTacToe_Challenge/
**Instagram:**
**Twitter: https://twitter.com/anja_khan90**
=> TicTacToe MiniMax contribution

_CodingChallenges/155-kaleidoscope-snowflake.md
https://youtu.be/BD4Y-88ryvE
**Instagram:**
@bhaswar.py
**Twitter:**
@denisovich_py
=> Added Kaleidoscope Simulation with Processing

_CodingChallenges/109-subscribers-map.md
https://editor.p5js.org/iccir919/full/RFuSwIS0S
**Twitter:**
realNeilVR
=> Map visualization contribution: Input Bay Wheels 2020 data

_Guides/community-contribution-guide.md
small error that leaves the page insecure from the point of view of browsers
**Instagram:** ALSWnet
**Twitter:** ALSWnet
=> change the image protocol of the contribution guide

_CodingChallenges/098.1-quadtree.md
My interactive simulation of an epidemic based on 3Blue1Brown's video of the same title.
Source: https://github.com/Immodal/simulating-an-epidemic
https://immodal.github.io/simulating-an-epidemic/
**Instagram:**
**Twitter: @NCImmodal**
=> Community Contribution: Simulating An Epidemic

_CodingChallenges/147-chrome-dinosaur.md
https://editor.p5js.org/Ivan-Denisovich-py/full/HheYX4_2P
(Sorry for the late enrtry for hacktoberfest. TT.)
**Instagram:**
bhaswar.py
**Twitter:**
denisovich_py
=> Added a classic dinosaur game

Courses/programming_with_text/session01/README.md, Courses/programming_with_text/session02/README.md, Courses/programming_with_text/session03/README.md, Courses/programming_with_text/session05/README.md, Courses/programming_with_text/session06/README.md, Courses/programming_with_text/session07/README.md, Courses/programming_with_text/session08/README.md, Courses/programming_with_text/session09/README.md, Courses/programming_with_text/session10/README.md
I made a Python script that checked all the links in the .md files in the folder Courses and I fixed all the broken links in the Courses folder.
=> Fixed broken links in Courses folder (bug)

_CodingChallenges/109-subscribers-map.md
https://anjakhan.github.io/PostCovidFlights_Challenge/
**Instagram:**
**Twitter: https://twitter.com/anja_khan90**
=> Visualizing contribution: post covid flight map

_CodingChallenges/135-gif-loop.md
Using a MIDI device to change the sketch's parameters on the fly. With The MidiBus library.
Basic example of a processing sketch controlled by a MIDI device, using <a href="http://www.smallbutdigital.com/projects/themidibus/" target="_blank">The MidiBus library</a>. 
Some paremeters like background color, stroke color, speed of the animation or the size of the shape change on the fly as we move the knobs, buttons and sliders of our MIDI controller. 
Output:
<a href="https://ibb.co/DLQP7S0"><img src="https://i.ibb.co/XVtfzvc/processing-midi.gif" alt="processing-midi" border="0"></a>
https://github.com/decrecementofeliz/processing-midibus
https://github.com/decrecementofeliz/processing-midibus/blob/main/processing-midi.gif
**Twitter:** …
=> Contribution to Gif Loop: MIDI control

_CodingChallenges/051.1-astar.md
https://dansarno.github.io/lightning-visualisation/
=> A* Contribution: Lightning Visualisation

Gemfile.lock, _learning/programming-with-text/9.1-what-is-firebase-database-as-a-service.md, _learning/programming-with-text/9.2-firebase-saving-data.md, _learning/programming-with-text/9.3-firebase-retrieving-data.md
Add "md files programming-with-text video 9.1-9.3" for issue #2762
=> Added md files programming-with-text video 9.1-9.3

_CodingChallenges/030-phyllotaxis.md
This one animate the growth angle (137.5°) from 0 to 360 with controllable increase and frequency.
Link to demo here: https://editor.p5js.org/NC_Productions/full/Ui4ns_1c-
=> Phyllotaxis contribution: animating growth angle

_CodingChallenges/054.1-starpatterns.md
demo link here: https://editor.p5js.org/mortuish/present/VY-zqiIAp
P.S. I forked the github code so most of the code is from there I just changed the look and added a fun twist
P.S.S. you can change the music by dropping an .mp3 file on the canvas
**Instagram:**
**Twitter:**
=> StarPatterns contribution: Integrated p5.sound <3

_CodingChallenges/157-zoom-annotations.md
Noticed a formatting problem on the latest coding challenge.
=> Fixing Contributions on cc157

_CodingChallenges/031-flappybird.md
this is my link to my flappy bird thingy :https://github.com/iKittyCode/snake-game
=> I added my flappy bird thingbob

_CodingChallenges/011-perlinnoiseterrain.md
demo link here: https://editor.p5js.org/mortuish/present/rikkujW-e
hope you like it <3 
default scale is 15 btw
**Instagram:**
**Twitter:**
=> 3D terrain contribution: 3D mirror-ish

_CodingChallenges/126-toothpicks.md
https://editor.p5js.org/cezikmertcan/sketches/JiW8l-bCu
=> Toothpicks Contribution - Ulam Warburton Version

_CodingChallenges/076-10print.md
=> Submitting an contribution

404.md, _jekyll/includes/1-tools/sort-videos.html
Thought it would be fun to add the whoops video to the 404 page.
=> Adding Whoops Video to 404 Page

_learning/bots/discord/03-discordjs.md, learning/bots/discord/03-discordjs/Nodejs/bot.js, learning/bots/discord/03-discordjs/Nodejs/package-lock.json, learning/bots/discord/03-discordjs/Nodejs/package.json
YouTube description is done so this should be ready to go unless you see any problems.
=> Adding Page for Discord Bot Video 3

_CodingChallenges/145-2d-ray-casting.md
Source : https://github.com/parampatidar/2D-Ray-casting-with-p5py
=> Raycasting contribution: 2D Ray-casting with p5py

_CodingChallenges/146-rendering-ray-casting.md
Link to project: https://healthpotionstudios.com/messingaround/checkbox_game/11-doom/game.html
**Instagram:**
**Twitter:**
=> raycasting 3d contribution: Doom made out of checkboxes

_CodingChallenges/085-the-game-of-life.md
Link to demo here: https://editor.p5js.org/stephane.roncin/full/EVAPcOrd7
- use of ES6 classes for cell and matrix objects
- mouseClick to run step by step
- can change color on each generation
- can display the number of neighbors for each cells
- can highlight reborn cells
- can infect reborn cells neighbors colors
- can change resolution
- cells can be : rectangles, ellipses, stars, triangles
**Instagram:**
**Twitter:**
=> game of life contribution: step by step running

_CodingChallenges/014-fractaltree.md
link to demo: https://cipherdot.github.io/coding-train-fractal-tree-contribution/
*Fractal tree recursive algorithm*
tree dynamics with mouse position
my Github page: https://github.com/cipherDOT
**Instagram:**
**Twitter:**
=> fractal tree with mouse dynamics

_beginners/p5js/6.1-opp-intro.md
=> Update 6.1-opp-intro.md  link: https://editor.p5js.org/arnavraspberrypi/sketches/G9YjgIuOQ

_challenges/coding-in-the-cabana/005-marching-squares.md
Used this marching squares tutorial to create https://loosethread.xyz/ and added my submission to the contributors list!
https://loosethread.xyz/
@cyberia_2020
https://twitter.com/Cyberia2020
=> Added a browser based artwork contribution

_learning/ml5/8.4-cnn-image-classification.md, learning/ml5/8.4-cnn-image-classification/P5/index.html, learning/ml5/8.4-cnn-image-classification/P5/sketch.js, learning/ml5/8.4-cnn-image-classification/mask/sketch.js
=> Adding page for cnn image classification video

_learning/ml5/8.4-cnn-image-classification.md
=> Adding mask variation to cnn video

_CodingChallenges/083-doodle-chrome-extension.md
<https://github.com/ChaitanyaSingh11/Doodler-Chrome.git>
**Instagram:**
**Twitter:**@Chaitanya_Coder
=> My first ever Contribution !!!

_CodingChallenges/105-polynomial-regression-tfjs.md
https://ishaqibrahimbot.github.io/
Three new features:
- Automatically decides the best degree from 1st, 2nd, and 3rd order polynomials
- Visualizes the changing costs for each degree using chart.js
- Has a slider to adjust the learning rate
https://ishaqibrahimbot.github.io/
**Instagram:** ishaqibrahim39
**Twitter:**@IshaqIbrahim96
=> Contribution: multi-degree and costs graph

_scripts/generate-youtube-descriptions.js
=> Adding Timestamps and Fixing Relative Links in YouTube Descriptions

_CodingChallenges/138-angry-birds.md
minor fix because the formatting was breaking yt-description command
=> formatting fix cc138

_learning/ml5/9.1-doodlenet.md, learning/ml5/9.1-doodlenet/mouse/index.html, learning/ml5/9.1-doodlenet/mouse/sketch.js, learning/ml5/9.1-doodlenet/template/index.html, learning/ml5/9.1-doodlenet/template/sketch.js, learning/ml5/9.1-doodlenet/video/index.html, learning/ml5/9.1-doodlenet/video/sketch.js
@shiffman this should be good to go if the description looks good.
=> Adding page for ml5 DoodleNet Video

CodingChallenges/CC_146_Rendering_Ray_Casting/P5/particle.js, CodingChallenges/CC_146_Rendering_Ray_Casting/P5/sketch.js
This PR completely fixes the fisheye problem in **CC_146_Rendering_Ray_Casting**.
https://imgur.com/a/LcawcHU
**Twitter:**
[@karlphillip](https://twitter.com/karlphillip)
=> CC_146_Rendering_Ray_Casting: fixed fisheye problem

_CodingChallenges/052-random-walk.md
Link to demo here: https://editor.p5js.org/zorkmaster57/full/JbbWCv-0n
**Instagram:**
**Twitter:**
=> Random Walker Contribution: Adding Perlin Nosie

_CodingChallenges/147-chrome-dinosaur.md
=> Trex game with automatic jumping

_CodingChallenges/003-snake-game-p5.md
Snake game with Leader-Board system.
Link to game: https://outdated-snake.herokuapp.com
https://outdated-snake.herokuapp.com
=> Outdated Snake by OutdatedGuy

_CodingChallenges/051.1-astar.md
=> Add my contribution to the bottom

_CodingChallenges/067-pong.md
=> We have done the breakout game in p5.js 

_challenges/coding-in-the-cabana/004-worley-noise.md
https://codepen.io/chromicquanta/pen/zYKRgPx
**Instagram:**
**Twitter:**
=> Whirly Noise

_CodingChallenges/031-flappybird.md
Link to demo here: https://shameekbaranwal.github.io/Flappy_Batarang/
Redesigned Flappy Bird with a Batarang flying between buildings in Gotham City.
https://shameekbaranwal.github.io/Flappy_Batarang/
- [ x ] I would be happy to have my project shared on The Coding Train's social media!
**Instagram:**
@shameekbaranwal
**Twitter:**
=> Flappy Bird contribution: Batman themed graphics.

_CodingChallenges/147-chrome-dinosaur.md
https://editor.p5js.org/sarvagyasingh260508/full/hsaadz92r
**Instagram:**
**Twitter:**
=> updated with animation

_CodingChallenges/001-starfield.md
[DEMO](https://editor.p5js.org/miresk/sketches/DzxMND-Rw)
**Twitter:https://twitter.com/clovek57**
=> Starfield contribution - Windows instead of stars

_CodingChallenges/107-sandpiles.md
p5 version with clicks and optimizations.
No need for a temp array. 
Keeping track of indexes that need to topple next round for better performance. 
https://editor.p5js.org/yaybjorn/full/pBYrUp8-0
**Instagram:**
**Twitter:**
=> sandpiles contribution in P5

_CodingChallenges/088-snowfall.md
Hi,
I would like to add this contribution of a collective mathematical art project with digital snowflakes made by people around the world.
Thanks.
https://editor.p5js.org/jcponce/full/tA94Ptb-f
**Twitter:**
https://twitter.com/jcponcemath
=> Adding my 2021 contribution

_CodingChallenges/019-superellipse.md
Demo: https://editor.p5js.org/jkenzer/full/nPbnDYnsI
**Instagram:**
**Twitter:**
=> Rotating SuperEllipse Contribution

_CodingChallenges/126-toothpicks.md
Fredikin Replicator in P5
Pause on mouse click
autozoom
Stops when line size reaches 0
**Instagram:**
**Twitter:**
=> Fredikin Replicator in P5

_CodingChallenges/036-blobby.md
Demo: https://editor.p5js.org/jkenzer/sketches/WcnOg0z74
**Instagram:**
**Twitter:**
=> Adding Contribution - Rings and Rings

_CodingChallenges/074-clock.md
Submitting my version of the Clock project featuring seven diverse variations.
http://www.robowenking.com/clocks
**Instagram:**
**Twitter:** @RobOwenKing
=> Clock Contribution Submission

_CodingChallenges/036-blobby.md
Link to demo : https://openprocessing.org/sketch/1063256
**Instagram:**
**Twitter:**
=> Blob White Rose

_GuestTutorials/004-emily-xie-matrix-digital-rain.md
https://editor.p5js.org/Gil/present/UsW9zPgNL
1920x1080 full screen
**Instagram:**
**Twitter:**
=> Matrix Digital Rain in p5js

_CodingChallenges/158-shape-classifier.md
Apply Neural Network for detecting handwritten digits: 
https://mortis-grimreaper.ddns.net/projects/HandwrittenDigit/
**Instagram:**
**Twitter:**
=> Add Neural Network project

_CodingChallenges/024-perlinnoiseflowfield.md
https://editor.p5js.org/Gil/present/9T-_t8Y0H
**Instagram:**
**Twitter:**
=> flow field playground

_CodingChallenges/014-fractaltree.md
Hello, I am catching up with challenges. :) I would like to share this pine fractal tree.
Kind regards.
https://editor.p5js.org/jcponce/present/vJ5XRkjm7
**Instagram:**
**Twitter:**
@jcponcemath
=> Pine fractal tree creator

_CodingChallenges/154-tic-tac-toe-minimax.md
Link to demo here: https://github.com/ITManZero/Connect4
**Instagram: ite.man**
**Twitter:**
=> minimax contribution : connect 4 with JavaFx

CodingChallenges/CC_106_xor_tfjs/P5/sketch.js
Removed the unused variable `nn`
=> Removing Unused Variable

_learning/nature-of-code/3.1-angles-rotation.md, learning/nature-of-code/3.1-angles-rotation/P5/index.html, learning/nature-of-code/3.1-angles-rotation/P5/sketch.js
@shiffman if the description looks good this is ready to merge.
=> Adding page for NOC 3.1 video

_learning/nature-of-code/3.2-anglular-motion.md, _learning/nature-of-code/index.md, learning/nature-of-code/3.2-angular-motion/grab/index.html, learning/nature-of-code/3.2-angular-motion/grab/sketch.js, learning/nature-of-code/3.2-angular-motion/gravitational-attraction/attractor.js, learning/nature-of-code/3.2-angular-motion/gravitational-attraction/index.html, learning/nature-of-code/3.2-angular-motion/gravitational-attraction/mover.js, learning/nature-of-code/3.2-angular-motion/gravitational-attraction/sketch.js, learning/nature-of-code/3.2-angular-motion/rect-acc/index.html, learning/nature-of-code/3.2-angular-motion/rect-acc/sketch.js
@shiffman I think this is good to be merged just check the description.
=> Adding Page for NOC 3.2

_CodingChallenges/113-hypercube.md
contributing my own hypercube: https://github.com/caseylabrack/caseylabrack.github.io/tree/master/sketches/hypercube
https://www.instagram.com/p/CJy88MkBQgX/
**Instagram: clabrack**
**Twitter: @CaseyLabrack**
=> new contribution to hypercube challenge

_CodingChallenges/011-perlinnoiseterrain.md
Just translated an extra landscape to create a tunnel like effect.
Created a simple 3 point gradient on the landscape .
**Instagram:** brucemoerdjiman
**Twitter:** broezer
=> 01-perlinnoiseterrain contribution: add an extra field for tunnel effect

_learning/nature-of-code/3.3-angles-and-vectors.md, learning/nature-of-code/3.3-angles-and-vectors/asteroids-exercise/index.html, learning/nature-of-code/3.3-angles-and-vectors/asteroids-exercise/sketch.js, learning/nature-of-code/3.3-angles-and-vectors/asteroids-exercise/spaceship.js, learning/nature-of-code/3.3-angles-and-vectors/direction-pointing/attractor.js, learning/nature-of-code/3.3-angles-and-vectors/direction-pointing/index.html, learning/nature-of-code/3.3-angles-and-vectors/direction-pointing/mover.js, learning/nature-of-code/3.3-angles-and-vectors/direction-pointing/sketch.js, learning/nature-of-code/3.3-angles-and-vectors/vehicle/index.html, learning/nature-of-code/3.3-angles-and-vectors/vehicle/mover.js, learning/nature-of-code/3.3-angles-and-vectors/vehicle/sketch.js
@shiffman check the description then should be good to go.
=> Adding page for NOC 3.3

_learning/nature-of-code/3.3-angles-and-vectors.md
Link to demo here: https://editor.p5js.org/DanielL/full/h2UNZ_F_x
Link to demo here: https://editor.p5js.org/DanielL/full/h2UNZ_F_x
**Instagram:**
**Twitter:**
=> Nature of Code 3.3 - communitiy contribution

.github/workflows/build.yml, .github/workflows/featurepeek.yml
=> Using a new caching key for ruby jobs to resolve #3022

_learning/nature-of-code/3.3-angles-and-vectors.md
https://editor.p5js.org/DanielL/full/z8Mqzazzs
**Instagram:**
**Twitter:**
=> Nature of Code 3.3 - Community contribution

_CodingChallenges/123.1-chaos-game.md
Link to demo: https://editor.p5js.org/kushagrabajpai64/present/gVZbu8DPC
**Instagram:**
**Twitter:**
=> Chaos game! Sierpinski Tetrahedron

_CodingChallenges/100.1-neuroevolution-flappy-bird.md
- https://github.com/reddragonnm/neatpy
- https://pypi.org/project/neatpy/
**Instagram:**
**Twitter:**
=> Neuroevolution Contribution:  NEAT library

_learning/nature-of-code/3.1-angles-rotation.md
https://editor.p5js.org/DanielL/full/BM4GKMLt7
**Instagram:**
**Twitter:**
=> Nature of Code 3.1 - Community contribution

_learning/nature-of-code/3.4-polar-coordinates.md, learning/nature-of-code/3.4-polar-coordinates/basic-polar-coordinates/index.html, learning/nature-of-code/3.4-polar-coordinates/basic-polar-coordinates/sketch.js, learning/nature-of-code/3.4-polar-coordinates/circular-shape/index.html, learning/nature-of-code/3.4-polar-coordinates/circular-shape/sketch.js, learning/nature-of-code/3.4-polar-coordinates/random-trail/index.html, learning/nature-of-code/3.4-polar-coordinates/random-trail/sketch.js, learning/nature-of-code/3.4-polar-coordinates/spiral/index.html, learning/nature-of-code/3.4-polar-coordinates/spiral/sketch.js
@shiffman As long as the description looks good this is ready to merge.
=> Adding page for NOC 3.4

_CodingChallenges/154-tic-tac-toe-minimax.md
https://reddragonnm.github.io/chess-ai/
**Instagram:**
**Twitter:**
=> Minimax Algorithm Contribution: Chess AI in js

_CodingChallenges/086-beesandbombs.md
You can view a gif of it working here: https://github.com/mawesome4ever/Dependancies/blob/master/Cube_Waves_Challenge.gif
If you have a Roblox account, you can view the animation by clicking "play" here: https://www.roblox.com/games/6011930452/Cube-Wave-Challenge
**Instagram:**
**Twitter:**
=> Ported it over to Roblox

_learning/nature-of-code/3.4-polar-coordinates.md
https://editor.p5js.org/o/full/iw051O24I
=> Nature of Code 3.4 Contribution: Rainbow Spiral

.gitignore, _scripts/generate-youtube-descriptions.js
- Switched to using _descriptions instead of just descriptions to improve local Jekyll build times.
- Moved link to web page to above the fold in the description.
- Added links to web editor sketches.
- Added previous video link.
- Made it so when there's a playlist that's included in the previous and next video urls.
=> YouTube descriptions generator improvements

_beginners/p5js/2.1-mousex-mousey.md
Link for Demo here:
https://singhkartikey679.github.io/Doodler/
or
https://singhkartikey679.github.io/Doodler/index.html
**Instagram:**
**Twitter:**
=> Doodler with Color Options

_learning/nature-of-code/3.6-graphing-sine.md, learning/nature-of-code/3.6-graphing-sine/circular-wave-exercise/index.html, learning/nature-of-code/3.6-graphing-sine/circular-wave-exercise/sketch.js, learning/nature-of-code/3.6-graphing-sine/graphing-wave/index.html, learning/nature-of-code/3.6-graphing-sine/graphing-wave/sketch.js, learning/nature-of-code/3.6-graphing-sine/playing-with-period/index.html, learning/nature-of-code/3.6-graphing-sine/playing-with-period/sketch.js, learning/nature-of-code/3.6-graphing-sine/sine-wave-graph-exercise/index.html, learning/nature-of-code/3.6-graphing-sine/sine-wave-graph-exercise/sketch.js
@shiffman The usual, should be good to go if the description looks good unless you see any problems.
=> Adding page for NOC 3.6

_learning/nature-of-code/2.2-mass-acceleration.md
750 circles of different mass and one moving attractor. Looks satisfyingly organic and wormy :-)
https://editor.p5js.org/ralphcrutzen/full/4svW7L1Km
**Instagram:**
**Twitter: @ralphcrutzen**
=> Contribution: lots of movers and a moving attractor

_learning/nature-of-code/3.4-polar-coordinates.md
Link to demo here:
https://editor.p5js.org/The_Exceptionist/full/WHBCQIck2
Its based on this tutorial as well as the the coding challenge of clock with arcs.
**Instagram:**
**Twitter:**
=> clock with colorful trails

_CodingChallenges/074-clock.md
Link to the result:
https://editor.p5js.org/The_Exceptionist/full/WHBCQIck2
**Instagram:**
**Twitter:**
=> Clock with trails

_learning/nature-of-code/3.5-simple-harmonic-motion.md
=> Weird rainbow generator by Abhay and Simon!!

_learning/nature-of-code/3.5-simple-harmonic-motion.md
=> Adding Yoyo Craziness!!

_learning/nature-of-code/3.7-additive-waves.md, learning/nature-of-code/3.7-additive-waves/P5/index.html, learning/nature-of-code/3.7-additive-waves/P5/sketch.js, learning/nature-of-code/3.7-additive-waves/P5/wave.js
@shiffman if the description looks good it should be ready to merge.
=> Adding page for NOC 3.7

_learning/nature-of-code/3.7-additive-waves.md
=> Adding some color full sine waves which has some sliders also!

CodingChallenges/CC_042.1_markov-chain/Processing/CC_042_1_markov-chain/CC_042_1_markov_chain/CC_042_1_markov_chain.pde
=> Adding Coding Challenge #42.1 in Processing for the Coding Train website

CodingChallenges/CC_042.2_markov-chain-names/Processing/CC_042_2_markov-chain-names/CC_042_2_markov_chain_names/CC_042_2_markov_chain_names.pde, CodingChallenges/CC_042.2_markov-chain-names/Processing/CC_042_2_markov-chain-names/CC_042_2_markov_chain_names/data/names.txt
Yesterday I did part 1, today is part 2.
=> Ported CC_042_2_markov-chain-names to Processing

_learning/nature-of-code/3.7-additive-waves.md
Link to demo here: https://editor.p5js.org/FelixCpp/full/tpdbXUCtQ
**Instagram:**
**Twitter:**
=> 3.7 Additive Waves contribution from FelixCPP

_learning/nature-of-code/3.7-additive-waves.md
Link: https://editor.p5js.org/Thysce/full/4gv4aJWxd
https://editor.p5js.org/Thysce/full/4gv4aJWxd
=> add my contribution, made with ❤️

_CodingChallenges/159-simple-pendulum-simulation.md
Adding these variation for the pendulum! @violetcraze I'll merge this if it passes tests but I may have missed some details so feel free to review and let me know if I did! (I didn't add the code to local repo folders for example).
=> Pendulum Variations

_CodingChallenges/159-simple-pendulum-simulation.md
As requested by Adam at https://twitter.com/shiffman/status/1363221496018178055
Realistic simulation of a PID controller working on a cart-pendulum system. Limitations: the controller only works on the angle not the position, and adding realistic drag or damping made the differential equations a bit too hard to be much fun anymore :) so, no damping. Animation: https://twitter.com/ednl/status/1363211452631425025 or https://www.instagram.com/p/CEHhf6YlB0C/
https://ednl.github.io/pidcart/
**Instagram:**
**Twitter:**
=> Contribution: pendulum on a cart

_CodingChallenges/159-simple-pendulum-simulation.md
Simulation of a Simple Pendulum written in Python.
Link to Source Code: https://github.com/kkin1995/simulations/tree/main/simple-pendulum
**Link to live project, video, or image (Sample):** https://www.youtube.com/watch?v=G7EJsikYbrs
**Twitter:**@karankinariwala
=> Added community contribution

_CodingChallenges/159-simple-pendulum-simulation.md
link to contributution:https://codepen.io/indra737/pen/oNYeOQx
**Instagram:**
**Twitter:**
=> Colourful Pendulum

CodingChallenges/CC_160_spring_forces/simple-spring-port/cc160_simple_spring_port/cc160_simple_spring_port.pde, CodingChallenges/CC_160_spring_forces/simple-spring/index.html, CodingChallenges/CC_160_spring_forces/simple-spring/sketch.js, CodingChallenges/CC_160_spring_forces/soft-spring-port/cc160_soft_spring_port/Particle.pde, CodingChallenges/CC_160_spring_forces/soft-spring-port/cc160_soft_spring_port/Spring.pde, CodingChallenges/CC_160_spring_forces/soft-spring-port/cc160_soft_spring_port/cc160_soft_spring_port.pde, CodingChallenges/CC_160_spring_forces/soft-spring/index.html, CodingChallenges/CC_160_spring_forces/soft-spring/particle.js, CodingChallenges/CC_160_spring_forces/soft-spring/sketch.js, CodingChallenges/CC_160_spring_forces/soft-spring/spring.js, CodingChallenges/CC_160_spring_forces/spring-oop-port/cc160_spring_oop_port/Particle.pde, CodingChallenges/CC_160_spring_forces/spring-oop-port/cc160_spring_oop_port/Spring.pde, CodingChallenges/CC_160_spring_forces/spring-oop-port/cc160_spring_oop_port/cc160_spring_oop_port.pde, CodingChallenges/CC_160_spring_forces/spring-oop/index.html, CodingChallenges/CC_160_spring_forces/spring-oop/particle.js, CodingChallenges/CC_160_spring_forces/spring-oop/sketch.js, CodingChallenges/CC_160_spring_forces/spring-oop/spring.js, CodingChallenges/CC_160_spring_forces/spring-vector-port/cc160_spring_vector_port/cc160_spring_vector_port.pde, CodingChallenges/CC_160_spring_forces/spring-vector/index.html, CodingChallenges/CC_160_spring_forces/spring-vector/sketch.js, _CodingChallenges/160-spring-forces.md
@shiffman should be good to go if everything looks good.
As a side note maybe don't push this until the video is public because it will appear on the home page.
=> Adding page for CC160

_CodingChallenges/160-spring-forces.md
Demonstration: https://editor.p5js.org/Galitan-dev/present/tMm6zujat
Source: https://editor.p5js.org/Galitan-dev/sketches/tMm6zujat
We can chose the particle to move. 
I check the nearest particle and move it to he mouse position.
(I added contribution category)
- Yes I would be happy to have my project shared on The Coding Train's social media!
=> Adding contribution: "Grab Any Spring Particle"

_CodingChallenges/159-simple-pendulum-simulation.md
Link to demo: https://editor.p5js.org/jkenzer/full/a-l3Gxark
**Instagram:**
**Twitter:**
=> Pendulum Contribution: Up Down Left Right

landing-page.html
I think we don't use Patreon anymore.
=> Removing the Patreon reference from the supporting section

_CodingChallenges/159-simple-pendulum-simulation.md
https://pendulums-sarvagya.glitch.me/
**Instagram:**
**Twitter:**
=> pendulum website

_CodingChallenges/160-spring-forces.md
Link to demo here: https://editor.p5js.org/leolewan/full/g_Dh6JvL1
https://editor.p5js.org/leolewan/full/g_Dh6JvL1
**Instagram:** @leolewan
**Twitter:** @leolewan
=> Spring Force Contribution - Grass

_CodingChallenges/160-spring-forces.md
link to demo: https://editor.p5js.org/josephgabriel666/full/ATtE9vhUE
What it does? Particles are linked each other and to the ground;
Size and color are changed for more happiness;
Thanks for your work!
**Instagram: https://www.instagram.com/youpjoseph/**
=> Mistake Are Beautiful

_CodingChallenges/160-spring-forces.md
Here is the link to the demo: https://editor.p5js.org/YileXu/sketches/nNc0tDl9t
**Instagram: jiagi_**
**Twitter:**
=> Simplified Wilberforce Pendulum Demo

_learning/nature-of-code/4.1-particle-system-simulation.md, learning/nature-of-code/4.1-particle-system-simulation/P5/index.html, learning/nature-of-code/4.1-particle-system-simulation/P5/particle.js, learning/nature-of-code/4.1-particle-system-simulation/P5/sketch.js
@shiffman The usual, if the description looks good this should be good to go.
=> Adding Page for NOC 4.1

_beginners/p5js/2.1-mousex-mousey.md, _more/archive/p5js/2.1-mousex-mousey.md, beginners/p5js/2.1-mousex-mousey/P5/sketch.js, more/archive/p5js/2.1-mousex-mousey/P5/index.html, more/archive/p5js/2.1-mousex-mousey/P5/sketch.js
@shiffman I left the description the same as the old version. Should be good to go. I moved the old video into the archive and left the contributions on the new video.
=> Updating page p5js 2.1 for New Video

_CodingChallenges/114-bubble-sort.md
=> Sorting visualization using HTML,CSS,JS

_CodingChallenges/052-random-walk.md
This makes it look like stars are forming
**Instagram:**
**Twitter:**
=> I added my own version which includes spacing 

_learning/ml5/4.1-save-load-model.md
=> Contribution

_learning/ml5/4.1-save-load-model.md
=> Upside down Particles system

_learning/nature-of-code/4.2-particle-emmiters.md, learning/nature-of-code/4.2-particle-emitters/particle-emitters-color/emitter.js, learning/nature-of-code/4.2-particle-emitters/particle-emitters-color/index.html, learning/nature-of-code/4.2-particle-emitters/particle-emitters-color/particle.js, learning/nature-of-code/4.2-particle-emitters/particle-emitters-color/sketch.js, learning/nature-of-code/4.2-particle-emitters/particle-emitters-with-movers/attractor.js, learning/nature-of-code/4.2-particle-emitters/particle-emitters-with-movers/emitter.js, learning/nature-of-code/4.2-particle-emitters/particle-emitters-with-movers/index.html, learning/nature-of-code/4.2-particle-emitters/particle-emitters-with-movers/mover.js, learning/nature-of-code/4.2-particle-emitters/particle-emitters-with-movers/particle.js, learning/nature-of-code/4.2-particle-emitters/particle-emitters-with-movers/sketch.js, learning/nature-of-code/4.2-particle-emitters/particle-emitters/emitter.js, learning/nature-of-code/4.2-particle-emitters/particle-emitters/index.html, learning/nature-of-code/4.2-particle-emitters/particle-emitters/particle.js, learning/nature-of-code/4.2-particle-emitters/particle-emitters/sketch.js, learning/nature-of-code/4.2-particle-emitters/particles-following-mouse/emitter.js, learning/nature-of-code/4.2-particle-emitters/particles-following-mouse/index.html, learning/nature-of-code/4.2-particle-emitters/particles-following-mouse/particle.js, learning/nature-of-code/4.2-particle-emitters/particles-following-mouse/sketch.js
@shiffman should be good to go if everything looks good
=> Adding page for NOC 4.2

_CodingChallenges/124-flocking-boids.md
Link to demo: https://jeremymuller.com/color-flocking-using-p5js/
https://jeremymuller.com/color-flocking-using-p5js/
**Instagram:** jeremysmuller
**Twitter:** jeremysmuller
=> Flocking boids contribution: color flocking

_CodingChallenges/154-tic-tac-toe-minimax.md
Link to demo here: https://impossible-tictactoe.web.app/
https://impossible-tictactoe.web.app/
**Instagram:**
**Twitter:**
https://twitter.com/ikramhasandev
=> tic-tac-toe contribution: an impossible ai made using flutter

_learning/nature-of-code/4.2-particle-emmiters.md
https://editor.p5js.org/DanielL/full/3Q-JY7VGG
**Instagram:**
**Twitter:**
=> community contribution - Fireworks

_learning/nature-of-code/4.2-particle-emmiters.md
=> System using Images

_CodingChallenges/161-pi-from-random.md
Added a graph visualization of PI value prediction in p5js.
Source code: https://editor.p5js.org/PhoenixCreation/sketches/s7nPBmL94
Presentation view: https://editor.p5js.org/PhoenixCreation/present/s7nPBmL94
**Instagram:** [phoenixcreationweb](https://instagram.com/phoenixcreationweb)
**Twitter:** [PhoenixCrea2ion](https://twitter.com/PhoenixCrea2ion)
=> Adding community Contribution from PhoenixCreation

_learning/nature-of-code/4.2-particle-emmiters.md
I did not do the way you did!
**Instagram:**
**Twitter:**
=> Particle system with movers

_CodingChallenges/124-flocking-boids.md
**Link to live project:**
https://boids.cubedhuang.com
=> boids contribution: optimized and customizable implementation

_CodingChallenges/116-lissajous.md
Link to File here:  https://github.com/TamsP/Processing/tree/main/Lissajous_Curve
=> Lissajous Curve contribution: Colorful With Text

Tutorials/16-javascript-es6/16.17-inheritance/P5/index.html, Tutorials/16-javascript-es6/16.17-inheritance/P5/particle.js, Tutorials/16-javascript-es6/16.17-inheritance/P5/sketch.js, Tutorials/16-javascript-es6/16.17-inheritance/P5/square.js, Tutorials/16-javascript-es6/16.18-polymorphism/P5/index.html, Tutorials/16-javascript-es6/16.18-polymorphism/P5/particle.js, Tutorials/16-javascript-es6/16.18-polymorphism/P5/sketch.js, Tutorials/16-javascript-es6/16.18-polymorphism/P5/square.js, _CodingChallenges/138-angry-birds.md, _Tutorials/16-javascript-es6/16.17-inheritance.md, _Tutorials/16-javascript-es6/16.18-polymorphism.md, _learning/nature-of-code/4.2-particle-emmiters.md
=> Adding pages for p5 16.17 and 16.18

_learning/nature-of-code/4.3-particle-inheritance.md, learning/nature-of-code/4.3-particle-inheritance/P5/confetti.js, learning/nature-of-code/4.3-particle-inheritance/P5/emitter.js, learning/nature-of-code/4.3-particle-inheritance/P5/index.html, learning/nature-of-code/4.3-particle-inheritance/P5/particle.js, learning/nature-of-code/4.3-particle-inheritance/P5/sketch.js
@shiffman Should be good to merge if the description looks good.
Working on inheritance and polymorphism videos. If I merge that the unit tests on this will break but I'll update this pull request if I merge those before you release this video.
=> Adding page for NOC 4.3

_challenges/coding-in-the-cabana/004-worley-noise.md
Repository link: https://github.com/TWallage/Generate_Worley_Noise
=> Worley Noise with python pygame

_CodingChallenges/030-phyllotaxis.md
Phyllotaxis with simple DOM elements to control parameters
https://editor.p5js.org/Chudroy/sketches/s8XZ3Nsu-
**Instagram:https://www.instagram.com/nicolas.garitagoitia/**
**Twitter:**
=> phyllotaxis contribution

_CodingChallenges/074-clock.md
Link to demo here: https://editor.p5js.org/Abhinav_programmer/full/l-AgllorM
**Instagram: alka_abhinav**
**Twitter: Abhinav20709644**
=> Clock: arc system instead of analog hand system

_learning/index.md
in depth => in-depth
added 'from'
api => APIs
**Instagram:**
**Twitter:**
=> Fixed little English punctuations

_CodingChallenges/013-reactiondiffusion-p5.md
blog: http://www.michielbraat.nl/blog/reaction-diffusion/  (interactive simulation at the end of the page!)
source: https://github.com/Proinn/reaction_diffusion_three_js
**Instagram:**
**Twitter:**
=> Reaction diffusion contribution: THREE.js + blog

_CodingChallenges/051.1-astar.md
Demo here:  https://sulay35.github.io/Astar-pathfinding/
https://sulay35.github.io/Astar-pathfinding/
**Instagram:**
@sulaydgt
**Twitter:**
=> A* pathfinding : Custom grid drawing system

_more/talks/mouse-learning.md, more/talks/mouse-learning/if-else-background/index.html, more/talks/mouse-learning/if-else-background/sketch.js, more/talks/mouse-learning/mouse-learns/index.html, more/talks/mouse-learning/mouse-learns/sketch.js
Missed some p5.js sketches from the talk so adding those now.
=> Adding Mouse Learning p5 Sketches

_learning/ml5/4.1-save-load-model.md
Demo:
https://editor.p5js.org/wojtekpaszo/full/fwu4HG9Yr
**Instagram:**
https://www.instagram.com/eeeeeeehmm/
=> ParticleSystemsInheritance: Boxy fire

_learning/ml5/4.1-save-load-model.md
Demo:
https://editor.p5js.org/wojtekpaszo/full/K7eR48Dqe
**Instagram:**
https://www.instagram.com/eeeeeeehmm
=> ParticleSystemTextures contribution: burning torch

_learning/nature-of-code/4.2-particle-emmiters.md
EPILEPSY WARNING!!!
Link to demo here: https://editor.p5js.org/wojtekpaszo/full/0VBVCl_Qa
**Instagram:**
https://www.instagram.com/eeeeeeehmm
=> Particles_emitters contribution: Glittering particles!

_CodingChallenges/011-perlinnoiseterrain.md
=> I can scroll through this!

_beginners/p5js/1.1-introduction.md
url: https://editor.p5js.org/abukar455a/full/tAqJWfqBo
**Instagram:**
**Twitter:**
=> Drawing face with colours

_beginners/p5js/2.1-mousex-mousey.md
source: https://editor.p5js.org/abukar455a/sketches/ZAstiKhjy
**Instagram:**
**Twitter:**
=> Growing circle and changing colours

_CodingChallenges/160-spring-forces.md
https://editor.p5js.org/Angul/full/CV_d01Y3K
=> Springy pendulum

_CodingChallenges/125-fourier-series.md
Fourier Series Visualization using vanilla JavaScript with options to customize output
see here: https://suhelmakkad.github.io/Fourier-Series-Visualization/
**Instagram:**
**Twitter:**
=> Visualization using vanilla javascript

_CodingChallenges/130.1-fourier-transform-drawing.md
Drawing with Fourier Series in vanilla JS With Options to customize output. 
see here: https://suhelmakkad.github.io/DFT/
**Instagram:  @SuhelMakkad **
**Twitter: @SuhelMakad **
=> Drawing with Fourier Series in vanilla JS

_beginners/p5js/2.1-mousex-mousey.md
Link to my animation: https://editor.p5js.org/orshemesh5020/full/YaPirmpAo
**Instagram:**
**Twitter:**
=> moving ball animation

_CodingChallenges/085-the-game-of-life.md
you'll be able to find the codebase in the public dir on the github repo
source: "https://github.com/ricoloic/game-of-life"
url: "https://editor.p5js.org/ricoloic/present/bLSOAUNGT"
**Instagram:**
**Twitter:**
=> Game Of Life more object oriented

_CodingChallenges/100.1-neuroevolution-flappy-bird.md
https://editor.p5js.org/atulbindal85/sketches/QnsDq15Wp
=> Voice t-rex

_challenges/coding-in-the-cabana/005-marching-squares.md
Adding a 3D version of marching squares (aka marching cubes) done in P5
https://nasirkhalid24.github.io/P5-Computational-Geometry/MarchingCubes/index.html
=> Adding P5 Marching Cubes

CodingChallenges/CC_162_self_avoiding_walk/3d/index.html, CodingChallenges/CC_162_self_avoiding_walk/3d/sketch.js, CodingChallenges/CC_162_self_avoiding_walk/3d/spot.js, CodingChallenges/CC_162_self_avoiding_walk/alpha-random-walk/index.html, CodingChallenges/CC_162_self_avoiding_walk/alpha-random-walk/sketch.js, CodingChallenges/CC_162_self_avoiding_walk/backtracking/index.html, CodingChallenges/CC_162_self_avoiding_walk/backtracking/sketch.js, CodingChallenges/CC_162_self_avoiding_walk/backtracking/spot.js, CodingChallenges/CC_162_self_avoiding_walk/basic/index.html, CodingChallenges/CC_162_self_avoiding_walk/basic/sketch.js, CodingChallenges/CC_162_self_avoiding_walk/bezier/index.html, CodingChallenges/CC_162_self_avoiding_walk/bezier/sketch.js, CodingChallenges/CC_162_self_avoiding_walk/bezier/spot.js, CodingChallenges/CC_162_self_avoiding_walk/recursion/index.html, CodingChallenges/CC_162_self_avoiding_walk/recursion/sketch.js, _CodingChallenges/162-self-avoiding-walk.md
Still needs video id but otherwise should be good.
=> Adding Page for Self Avoiding Walk Challenge

_CodingChallenges/085-the-game-of-life.md
https://aditya-ds-1806.github.io/coding-challenges/game-of-life
**Twitter:** https://twitter.com/Aditya18062000
=> Game of Life community contribution

_CodingChallenges/162-self-avoiding-walk.md
https://editor.p5js.org/arnavraspberrypi/present/-RI1f2-__   (you will have to copy this link till the last underscore '_' and paste in the browser)
**Instagram:**
**Twitter:**
=> My random walk(completely random)

_learning/nature-of-code/5.1-autonomous-agents.md, _learning/nature-of-code/5.2-seek.md, learning/nature-of-code/5.2-seek/arrive/index.html, learning/nature-of-code/5.2-seek/arrive/sketch.js, learning/nature-of-code/5.2-seek/arrive/vehicle.js, learning/nature-of-code/5.2-seek/pursue/index.html, learning/nature-of-code/5.2-seek/pursue/sketch.js, learning/nature-of-code/5.2-seek/pursue/vehicle.js, learning/nature-of-code/5.2-seek/seek/index.html, learning/nature-of-code/5.2-seek/seek/sketch.js, learning/nature-of-code/5.2-seek/seek/vehicle.js, learning/nature-of-code/5.2-seek/sliders/index.html, learning/nature-of-code/5.2-seek/sliders/sketch.js, learning/nature-of-code/5.2-seek/sliders/vehicle.js
Good to go if the description looks good.
=> Adding page for NOC 5.2 seek

_CodingChallenges/115-snake-game-redux.md
I've redone some basic functions and made a more polished UI, running in nodejs, also added a point counter, the canvas is sized based on the window size at page load (start and end screen added)
```js
{
author: {
name: "Loïc Rico",
url: "https://github.com/ricoloic"
},
url: "https://invincible-ivy-coffee.glitch.me/",
source: "https://github.com/ricoloic/snake-game"
}
```
-
=> Snake Game, custom canvas sizing based on window size, better UI

_CodingChallenges/115-snake-game-redux.md
https://editor.p5js.org/apsyll/sketches/q6cS3yGRF
play snake on and with your face.
alternatively use the arrow keys
**Instagram:**
**Twitter:**
=> adding ml5 facemesh to control the game

_beginners/p5js/2.1-mousex-mousey.md
Link to it here: https://editor.p5js.org/Marcu/sketches/Xh-SWY6YH7
**Instagram:**
**Twitter:**
=> 2.2 exercise - growing circle

_beginners/p5js/2.1-mousex-mousey.md
ive changed my username, sorry for that, I thought i changed it but I didnt
**Instagram:**
**Twitter:**
=> p5 2.1 name update

_beginners/p5js/2.4-random.md
Link to it here: https://editor.p5js.org/MarcuOrSomething/sketches/AoqDHp2l4
**Instagram:**
**Twitter:**
=> 2.4 p5 contribution

_CodingChallenges/021-mandelbrot-p5.md
Just an other contribution to the Mandelbot show #21
https://editor.p5js.org/Basz/present/RNzUk1pLn
**Instagram:** https://www.instagram.com/bas.vogel/
**Facebook:** https://www.facebook.com/bas.vogel/
**Website:** https://basvogel.nl
=> Contribution to Mandelbot #21

_CodingChallenges/021-mandelbrot-p5.md
Made mistake in URL structure - it seems to need 2 (for URL of Contributor and for Presentation of Contribution).
**Instagram:**
**Twitter:**
=> Correcting URL structure in my Contribution to #21

_learning/nature-of-code/5.3-flee-pursue-evade.md, learning/nature-of-code/5.3-flee-pursue-evade/evade/sketch.js, learning/nature-of-code/5.3-flee-pursue-evade/evade/vehicle.js, learning/nature-of-code/5.3-flee-pursue-evade/flee/index.html, learning/nature-of-code/5.3-flee-pursue-evade/flee/sketch.js, learning/nature-of-code/5.3-flee-pursue-evade/flee/vehicle.js, learning/nature-of-code/5.3-flee-pursue-evade/pursue-bouncing-ball/index.html, learning/nature-of-code/5.3-flee-pursue-evade/pursue-bouncing-ball/sketch.js, learning/nature-of-code/5.3-flee-pursue-evade/pursue-bouncing-ball/vehicle.js, learning/nature-of-code/5.3-flee-pursue-evade/pursue-slider/index.html, learning/nature-of-code/5.3-flee-pursue-evade/pursue-slider/sketch.js, learning/nature-of-code/5.3-flee-pursue-evade/pursue-slider/vehicle.js, learning/nature-of-code/5.3-flee-pursue-evade/pursue-wander/index.html, learning/nature-of-code/5.3-flee-pursue-evade/pursue-wander/sketch.js, learning/nature-of-code/5.3-flee-pursue-evade/pursue-wander/vehicle.js, learning/nature-of-code/5.3-flee-pursue-evade/pursue/index.html, learning/nature-of-code/5.3-flee-pursue-evade/pursue/sketch.js, learning/nature-of-code/5.3-flee-pursue-evade/pursue/vehicle.js
=> Adding page for NOC 5.3

_learning/nature-of-code/5.2-seek.md
https://editor.p5js.org/manthanmji/full/ToPnrBrro
=> added my version as community contribution

_CodingChallenges/004-purplerain.md
Link to view the sketch at full screen: https://editor.p5js.org/andreasuarezsanchez027/full/LdnrGDnLz
**Instagram:**
**Twitter:**
=> Purple Rain: Controling the rain

_CodingChallenges/074-clock.md
Link to view the sketch at full screen: https://editor.p5js.org/Drea007/full/ICxxEXm69
**Instagram:**
**Twitter:**
=> Clock: Black & White analog clock

_CodingChallenges/007-solarsystemgenerator.md
Link to view the full sketch: https://editor.p5js.org/Drea007/full/5-vqHY3Te
**Instagram:**
**Twitter:**
=> 2D Solar System Simulator

_CodingChallenges/085-the-game-of-life.md
p5.js: https://editor.p5js.org/unta1337/sketches/K_zh1sVY_
**Instagram:**
**Twitter:**
=> Game of Life Contribution: Now with Interactions!

_CodingChallenges/004-purplerain.md
https://relaxing-rain.netlify.app/
**Instagram:**
**Twitter:**
=> rain with perlin noise wind

_CodingChallenges/052-random-walk.md
Two random walkers collide to form a new random walker 
When the 🔵Blue Random Walker collides with the 🔴Red Random Walker they create the 🟣Purple Random Walker
Link to demo here: https://ayaan-surkhi.github.io/Random-Walkers_Color-Combo/
=> Random Walk contribution: walkers collide creating a new walker

_CodingChallenges/001-starfield.md
Link to view the full sketch: https://editor.p5js.org/Drea007/full/CMNe5j1Kt
**Instagram:**
**Twitter:**
=> Starfield: Controling the shape of the stars

_CodingChallenges/162-self-avoiding-walk.md
https://editor.p5js.org/butkeraites/sketches/AWcZE5WBI
**Instagram:** butkeraites
**Twitter:** Renan_But
=> Self avoiding walk contribution: Colored dots

_CodingChallenges/149-tic-tac-toe.md
https://tic-tac-toe-resizable.netlify.app/
**Instagram:**
**Twitter:**
=> added variable sized tic tac toe with React JS

_CodingChallenges/095-approximating-pi.md
Using circumference to get the value of π 
π = circumference/(2*r)
**Link to demo: https://ayaan-surkhi.github.io/Approximating-Pi/**
=> Approximating Pi Contribution: Using circumference to get the value of π

_learning/nature-of-code/5.4-arrive.md
My version: https://editor.p5js.org/Chrispykins/sketches/OnqcFW-PY
**Twitter:** @Chrispykins
=> Arrive with Vector Field by Chris Gallegos

_CodingChallenges/003-snake-game-p5.md
https://csnake.netlify.app
https://csnake.netlify.app
**Instagram:**
**Twitter:**
=> Added an implementation in C that runs in browser

_CodingChallenges/085-the-game-of-life.md
My contribution to this challenge in Python 
https://youtu.be/y41E_EzUJ0M 
I would be happy to have my project shared on The Coding Train's social media!
**Twitter:**
@PathikGhugare
=> Game Of Life challenge contribution

_CodingChallenges/027-fireworks.md
3D effect => The fireworks get their size increased as they fall down and disappear.
You can also set each time whether you want the fireworks to be MONOCOLOR or MULTICOLOR by pressing its corresponding HTML button.
**Instagram:**
**Twitter:**
=> Fireworks with 3D effect

_CodingChallenges/071-minesweeper.md
```yaml
- title: "clasic bomb-sweeper"
author:
name: "Loïc Rico"
url: https://github.com/ricoloic/
video_id: m4FEp0jb0RA
url: https://ricoloic.github.io/mine-sweeper/
source: https://github.com/ricoloic/mine-sweeper/
```
https://ricoloic.github.io/mine-sweeper/
=> basic mine sweeper, added images and difficulty selection + win & lose state

_CodingChallenges/004-purplerain.md
https://tuffstuff2k7.github.io/Rain/
**Instagram:**
**Twitter:**
=> My version - Purple Rain in Processing

_CodingChallenges/055-roses.md
Makes beautiful, amazing art using hypotrochoid or epitrochoid curves that change over time and layer colors.  Mess with variables to get different art.  Click the sketch to pause.  
Video showing it: https://www.youtube.com/watch?v=jNWaAh3Irjw&t=1s
Code: https://editor.p5js.org/StevesMakerspace/sketches/dqCrfr642
**Twitter:@SteveMakerspace**
**YouTube: https://www.youtube.com/channel/UCJjYUJudUW67Tg79jtF_rpQ**
=> Spirograph Art-Maker

_CodingChallenges/159-simple-pendulum-simulation.md
The damping force will depend on the length of the pendulums' arms. The longer the arms are, the stronger will be the damping force.
**Instagram:**
**Twitter:**
=> Opposite pendulums simulation adding damping force

_CodingChallenges/022-juliaset.md
https://github.com/M87K452b/julia-set-with-shaders/blob/main/render/julia-set-render-1280x720.gif
**Instagram:**
**Twitter:**
=> Added Project - Julia set with GLSL shaders and P5js

_GuestTutorials/004-emily-xie-matrix-digital-rain.md
https://github.com/M87K452b/raining-food/blob/main/render/rainingFood.gif
**Instagram:**
**Twitter:**
=> Added Project - Raining Food Emojis

_CodingChallenges/004-purplerain.md
I have added my version of purple rain :)
Link to the code - [Purple Rain](https://editor.p5js.org/Krish2811/full/ZKmu9Zml7)
**Link to live project:**
[Purple Rain](https://editor.p5js.org/Krish2811/full/ZKmu9Zml7)
=> 🚀 Added my version

_CodingChallenges/028-metaballs.md
https://e4494s.neocities.org/metaballs.html
**Instagram:**
**Twitter:**
=> Suggested new contribution for metaballs challenge

_CodingChallenges/145-2d-ray-casting.md
=> update source link

_CodingChallenges/127-snowflake-brownian.md
https://e4494s.neocities.org/snowflake.html
https://e4494s.neocities.org/snowflake.html
=> Suggested new contribution for Brownian Snowflake challenge

_CodingChallenges/163-bezier.md
new video idea (which I committed directly to main by accident)
shorter title for website (new title idea will stay just on YouTube for now?) cc @duskvirkus
=> update Bezier video

_CodingChallenges/163-bezier.md
Demo link: https://editor.p5js.org/ilmnarayana/full/_vyuj8rli
**Instagram:**
**Twitter:**
=> Bezier Curve LERP Animations (2-10 points)

CodingChallenges/CC_041_ClappyBird/Processing/CC_041_ClappyBird/Bird.pde, CodingChallenges/CC_041_ClappyBird/Processing/CC_041_ClappyBird/CC_041_ClappyBird.pde, CodingChallenges/CC_041_ClappyBird/Processing/CC_041_ClappyBird/Pipe.pde
Hello, I got this working well with Processing's Audio library and hopefully it will help a little bit to get more people to use it. Unfortunately, there are no sliders native to Processing, so I just had to hard code values for the audio thresholds instead of using sliders like in the original. I made sure these values work well to register clapping, however. I figured this would be better than nothing!
- [ x ] I would be happy to have my project shared on The Coding Train's social media!
**Instagram:**
**Twitter:**
=> Ported ClappingBird to Processing4

_CodingChallenges/163-bezier.md
link to demo: https://editor.p5js.org/alonjazz/sketches/pHoT3Nfh0
https://editor.p5js.org/alonjazz/sketches/pHoT3Nfh0
**Instagram:**
**Twitter:**
=> Bézier curve contribution: animated n point Bézier

_learning/nature-of-code/5.3-flee-pursue-evade.md
https://editor.p5js.org/DanielL/full/EBHVYNqTJ
**Instagram:**
**Twitter:**
Note:
I'm sorry, I accidentially got  the title of my contribution wrong in the previous pull request.
=> Community contribution (corrected wrong title)

_learning/nature-of-code/5.4-arrive.md
https://editor.p5js.org/DanielL/full/3Q_k9lUO8
https://preview.p5js.org/DanielL/present/3Q_k9lUO8
**Instagram:**
**Twitter:**
=> Community contribution - Nature of Code 5.4

_CodingChallenges/130.1-fourier-transform-drawing.md
in this demo user can manually play with the circles size speed (frequency) and starting angle (phase)
and see what comes out
or you can draw your own, and see how it translates to circles.
you can also see the y access only getting the wave data itself
a word of advice, to actually see what's going on if you manually enter circles use very low frequency (smaller then 0.01)
https://5ffvz.csb.app/
=> Add Mikes Fourier contribution with draw + numbers

_CodingChallenges/010.1-maze-dfs-p5.md
https://immodal.github.io/maze-lightning/
**Twitter:** @NCImmodal
=> Community Contribution: Lightning Strikes

_learning/nature-of-code/5.5-wander.md, learning/nature-of-code/5.5-wander/3d/index.html, learning/nature-of-code/5.5-wander/3d/sketch.js, learning/nature-of-code/5.5-wander/3d/vehicle.js, learning/nature-of-code/5.5-wander/deleting-positions/index.html, learning/nature-of-code/5.5-wander/deleting-positions/sketch.js, learning/nature-of-code/5.5-wander/deleting-positions/vehicle.js, learning/nature-of-code/5.5-wander/displacement/index.html, learning/nature-of-code/5.5-wander/displacement/sketch.js, learning/nature-of-code/5.5-wander/displacement/vehicle.js, learning/nature-of-code/5.5-wander/main/index.html, learning/nature-of-code/5.5-wander/main/sketch.js, learning/nature-of-code/5.5-wander/main/vehicle.js, learning/nature-of-code/5.5-wander/perlin-noise/index.html, learning/nature-of-code/5.5-wander/perlin-noise/sketch.js, learning/nature-of-code/5.5-wander/perlin-noise/vehicle.js, learning/nature-of-code/5.5-wander/sliders/index.html, learning/nature-of-code/5.5-wander/sliders/sketch.js, learning/nature-of-code/5.5-wander/sliders/vehicle.js
=> Adding page for NOC 5.5

_CodingChallenges/029-smartrockets.md
Added a dartboard as the target and darts instead of rectangles and used rejection sampling to select parents for crossover and added the time taken by the dart to reach the target as a factor in determining the fitness.
Link to demo: https://ayaan-surkhi.github.io/Smart-Darts/
**Instagram:**
**Twitter:**
=> Smart Rockets contribution: Added a dartboard as target and used rejection sampling

_CodingChallenges/085-the-game-of-life.md
=> Game of Life in SDL2 EMSCRIPTEN

_CodingChallenges/003-snake-game-p5.md
Source code at https://github.com/David-Emmanuel-No1/Snake-Game
=> Snake Game

_learning/nature-of-code/3.3-angles-and-vectors.md
This is just a fun play around site that I dont know what to do with at the moment, But Ill have fun figuring it out.
Link to demo: http://itchynaps.com/nature/public_html/Ch3.3/
Yet again I am having issues(bleh) I couldnt get the sketch to run in the p5 editor, but Im sure its something simple I overlooked.
link to source: https://editor.p5js.org/typhona/sketches/N5zF8uDoy
**Instagram:**
**Twitter:**
=> Psychad-Angle

_CodingChallenges/076-10print.md
=> 10PRINT PI with emojis

_CodingChallenges/163-bezier.md
Currently, the final curve is drawn by iteration over the points and drawing lines which improves the performance.
TODO: I will implement a better solution to draw the final curve soon
**Link to live project, video, or image:** https://editor.p5js.org/ayushkoul00/full/t1POcpzme
=> Added N degree/points bezier Curves

_learning/ml5/4.1-save-load-model.md
Live Demo URL : https://preview.p5js.org/ehdrbdndns/present/pj6ZYn2Y8
**Instagram:**
**Twitter:**
=> Make Firecracker

_CodingChallenges/163-bezier.md
Add Bezier Curves by Mavyfaby
**Instagram:** [@mavyfaby](https://instagram.com/mavyfaby)
**Twitter:** [@mavyfaby](https://twitter.com/mavyfaby)
=> Add Bezier Curves by Mavyfaby

_CodingChallenges/163-bezier.md
Link to demo: https://editor.p5js.org/bewies/full/ZDIWpyv1Z
Link to source code: https://editor.p5js.org/bewies/sketches/ZDIWpyv1Z
**Instagram:**
**Twitter:**
=> Bezier Contribution: Curves in a 3D-box with WebGL

_CodingChallenges/006-mitosis-p5.md, _CodingChallenges/024-perlinnoiseflowfield.md, _CodingChallenges/071-minesweeper.md, _CodingChallenges/076-10print.md, _CodingChallenges/090-floyd-steinberg-dithering.md, _CodingChallenges/117-seven-segment.md, _CodingChallenges/147-chrome-dinosaur.md, _CodingChallenges/155-kaleidoscope-snowflake.md, _CodingChallenges/163-bezier.md
Hello, I recently changed my username from Ivan-Denisovich-py to DenisovichDev that resulted all the links to be broken in my Coding Challenge contributions. That's why I've fixed all my broken links in this pull request.
=> Updated broken links

_CodingChallenges/074-clock.md
=> added rubik's clock

_CodingChallenges/034-dla.md
https://david-beale.github.io/Diffusion/
https://youtu.be/u7vx0SZpAkw
**Instagram:**
**Twitter:**
=> DLA contribution

_CodingChallenges/012-lorenzattractor.md
https://david-beale.github.io/Attractors/
**Instagram:**
**Twitter:**
=> Lorenz contribution

_learning/nature-of-code/2.3-friction.md
Link to demo here: https://editor.p5js.org/sapperlot/full/IF7W75Y6m
Instagram: "https://www.instagram.com/sapperlotproductdesign"
Twitter: "https://twitter.com/sapperlotdesign"
=> friction: primula

_CodingChallenges/034-dla.md
=> added DLA community contrib

_learning/programming-with-text/3.1-the-ritajs-library.md
Link to demo here: https://editor.p5js.org/sapperlot/full/VcDz8KZbD
**Instagram:**
**Twitter:**
=> Angular Motion - Fortune Weel with colors

_CodingChallenges/163-bezier.md
I just started learning about CG and got a lot of fun with this challenge. Excited to make more!
**Link to live project, video, or image:** [https://codepen.io/cassiofb-dev/full/yLzbOKK](https://codepen.io/cassiofb-dev/full/yLzbOKK)
**Instagram:**
**Twitter:** [@cassiofb_dev](https://twitter.com/cassiofb_dev)
=> Add my variant of Bézier Curve

_beginners/p5js/3.1-conditional-statements.md
Checkout the demo here: https://editor.p5js.org/yathy2007/full/Fl5orgMuQ
Press mouse button to interact.
https://editor.p5js.org/yathy2007/full/Fl5orgMuQ
**Instagram:**
**Twitter:**
yathy2007
=> Added a code example for conditionals.

_CodingChallenges/154-tic-tac-toe-minimax.md
https://theabbie.github.io/TicTacToe/
**Instagram:** @sasta_abbie
**Twitter:** @theabbiee
=> Add Animated Tic Tac Toe

_beginners/p5js/5.1-function-basics.md
Checkout the demo: https://editor.p5js.org/yathy2007/full/Nyhp2Hdtw
https://editor.p5js.org/yathy2007/full/Nyhp2Hdtw
**Instagram:**
**Twitter:**
yathy2007
=> Added a better lollipop example.

_beginners/p5js/7.1-what-is-an-array.md
Checkout the demo: https://editor.p5js.org/yathy2007/full/jdwQTinI1
https://editor.p5js.org/yathy2007/full/jdwQTinI1
**Instagram:**
**Twitter:**
yathy2007
=> Added a new code example for arrays

_Courses/data-and-apis/1.1-fetch.md
Checkout the demo here: https://codepen.io/yathy2007/full/ZEXXpPY
https://codepen.io/yathy2007/full/ZEXXpPY
**Instagram:**
**Twitter:**
yathy2007
=> Added another example for fetch

_Courses/data-and-apis/1.2-tabular-data.md
Checkout the demo here: https://editor.p5js.org/yathy2007/full/nPr8Kpa4g
https://editor.p5js.org/yathy2007/full/nPr8Kpa4g
**Instagram:**
**Twitter:**
yathy2007
=> Added a code example for tabular data.

_Courses/data-and-apis/2.1-server-side-node.md
Checkout the demo here: https://codepen.io/yathy2007/full/mdBBxPN
https://codepen.io/yathy2007/full/mdBBxPN
**Instagram:**
**Twitter:**
yathy2007
=> Added a sketch for showing the user location.

_CodingChallenges/121.1-logo-interpreter.md
[https://editor.p5js.org/jnthbdn/full/VNDnzpaJY](https://editor.p5js.org/jnthbdn/full/VNDnzpaJY)
**Instagram:** [@jnthbdn](https://www.instagram.com/jnthbdn/)
**Twitter:** [@jnthbdn](https://twitter.com/Jnthbdn)
=> Simple LOGO parser (with a railroad diagram !! :steam_locomotive:)

_CodingChallenges/085-the-game-of-life.md
https://ash205.github.io/Game-of-life/
=> 085-the-game-of-life Contribution

_CodingChallenges/027-fireworks.md
https://editor.p5js.org/louisjamesgray2000/full/o8HbsCH60
**Instagram:**
**Twitter:**
=> Fireworks contribution; WEBGL

_CodingChallenges/124-flocking-boids.md
Link to demo here: https://editor.p5js.org/sponkyblox/full/Nbs8fr1nX
**Instagram:**
**Twitter:**
=> Flocking Contribution: Multicellular organism Creator

_CodingChallenges/005-space-invaders-p5.md
try demo here : https://editor.p5js.org/hussainsalih.github@gmail.com/full/oR8ZU1nT2
**Instagram:**
**Twitter:**
=> Adding my code

_CodingChallenges/155-kaleidoscope-snowflake.md
Rotated sketch 90 degrees. Added save to transparent background or black. Mouse wheel controls brush size. Added undo(just last drawn). Added instructions.
Remember! Right click drag to draw.
GitHub link: https://github.com/markcosmic/Processing-3-Max-Kaleidoscope.git
**Instagram:**
**Twitter:**
=> Kaleidoscope Snowflake contribution:

_CodingChallenges/010.1-maze-dfs-p5.md
Url : https://editor.p5js.org/vignesh2002/sketches/nhhCexHrI
**Instagram:**
**Twitter:**
=> maze-dfs-contibution: increased Performance by eliminating arrays

package-lock.json, package.json
=> Flocking simulation with UI controls and video capture

_CodingChallenges/124-flocking-boids.md
https://ycaneroltests.github.io/flocking.html
=> Add contribution to 124-flocking-boids

_CodingChallenges/145-2d-ray-casting.md
The Live Project: [Loïc Rico](https://rico.studio/sketches/ray-casting)
The Project Repo/sketch: [personal-webpage · GitHub](https://github.com/ricoloic/personal-webpage/tree/master/src/routes/sketches/ray-casting)
My Github Profile: https://github.com/ricoloic
**[LIVE PROJECT](https://rico.studio)**
**Twitter:**
[loicrico](https://twitter.com/loicrico1)
=> Ray Casting W/ editable boundaries

_CodingChallenges/098.1-quadtree.md
my self: [LOÏC RICO](https://github.com/ricoloic)
[Souce code](https://github.com/ricoloic/personal-webpage/blob/master/src/routes/sketches/flocking/Flocking.jsx)
[LIVE DEMO](https://rico.studio/sketches/flocking)
=> Quadtree integrated with flocking simulation

_CodingChallenges/123.1-chaos-game.md
my self: [LOÏC RICO](https://github.com/ricoloic)
[source code](https://github.com/ricoloic/personal-webpage/blob/master/src/routes/sketches/chaos-game/ChaosGame.jsx)
[LIVE DEMO](https://rico.studio/sketches/chaos-game)
=> Ricos chaos game

_CodingChallenges/024-perlinnoiseflowfield.md
my self: [LOÏC RICO](https://github.com/ricoloic)
[source code](https://github.com/ricoloic/personal-webpage/blob/master/src/routes/sketches/flow-field/FlowField.jsx)
[LIVE DEMO](https://rico.studio/sketches/flow-field)
=> Flowfield with personalized colors and controls

_CodingChallenges/130.1-fourier-transform-drawing.md
Link to demo here: https://codepen.io/leimapapa/pen/ZEaOERd
https://codepen.io/leimapapa/pen/ZEaOERd
**Instagram:**
**Twitter:**
=> Fourier-transform drawing: SVG Laser Cutter

_CodingChallenges/165-slide-puzzle.md
Link to demo here:  https://editor.p5js.org/kfahn/full/QFe-ulhZS
**Instagram:**
**Twitter:**
=> sliding puzzle with new digital art

_CodingChallenges/154-tic-tac-toe-minimax.md
https://mess-zone.github.io/ai-tic-tac-toe/index.html
**Instagram:**
**Twitter:**
=> Best of 3 Tic Tac Toe

_learning/nature-of-code/5.5-wander.md
Link to the Github repo: https://github.com/Yamen-Malik/Steering-Behaviors
**Twitter:@yamen_malik2
=> Added My java version to the contributions

_CodingChallenges/035.1-tsp.md
Hello 👋🏼 . I'm Varun Irani. I have implemented, using the videos at The Coding Train, three different approaches to solving the traveling salesperson problem in the Processing 3 IDE Python Mode. Please do review the code and notify me of any changes to be made. Thank you.
**Instagram:** [@pianist_ears](https://www.instagram.com/pianist_ears/)
=> Traveling Salesperson - Processing 3 - Python

_CodingChallenges/160-spring-forces.md
Link to demo: https://editor.p5js.org/Codefish/full/y9mXtyz6g
**Instagram:**
**Twitter:**
=> Cloth simulation with spring system

_CodingChallenges/166-ascii-image.md
Video: https://youtu.be/fJMaec6zi9k
**Instagram:**
**Twitter:**
=> Add my contribution in ASCII art coding challenge

_CodingChallenges/166-ascii-image.md
Paste or type in a string of text and the characters will be sorted by their visual density to allow for usage in an auto-generated ascii image
https://editor.p5js.org/jhrtn/sketches/a2pibVqFZ
=> ASCII contrib: sort text string by visual density

_CodingChallenges/166-ascii-image.md
[image2ascii](https://github.com/KarthikRIyer/image2ascii)
**Instagram:** rkarthikiyer
**Twitter:** karthik_r_iyer
=> Add contribution (image2ascii in Rust)

_CodingChallenges/167-prime-spiral.md
link: https://editor.p5js.org/codingtrain/full/0Ud-XsaYb
**Instagram:**
**Twitter:**
=> Ulam Prime Spiral in python with pyglet

_CodingChallenges/167-prime-spiral.md
I have tried to build the prime spiral on the terminal using c++ 
Link to repository: https://github.com/coastaldemigod/creative-coding/tree/main/prime-spiral
https://github.com/coastaldemigod/creative-coding/blob/main/prime-spiral/ulam-spiral-ss.jpg
**Instagram:** https://www.instagram.com/shiv.a.n.sh/
**Twitter:** https://twitter.com/coastaldemigod
=> 167-prime-spiral contribution: prime spiral using c++

_CodingChallenges/126-toothpicks.md
https://github.com/vinnyI-afk/Toothpicks-Coding-Challenge
=> Toothpicks contribution: LÖVE2D Lua port

_learning/programming-with-text/1.1-introduction.md
Accelerate to Mouse in Python via pyglet module
**Instagram:**
**Twitter:**
=> Accelerate to Mouse in Python via pyglet

_CodingChallenges/078-simple-particle-system.md
I used the particle system to create smoke and fire and then added a similar system to add wind.
[https://github.com/Vikram-Bhat/CodingChallengeContributions/blob/main/particlesystem.pde](https://github.com/Vikram-Bhat/CodingChallengeContributions/blob/main/particlesystem.pde)
**Instagram:**
**Twitter:**
=> Contribution: "Campfire with Occasional Breeze"

_learning/nature-of-code/2.5-gravitational-attraction.md
Link to demo: https://editor.p5js.org/Codefish/full/jjeVYNiS8
**Instagram:**
**Twitter:**
=> Adding mutual attraction example

_CodingChallenges/027-fireworks.md
Link to demo: https://editor.p5js.org/Nostrada/full/vIjcEqrzn
**Instagram:**
**Twitter:**
=> Firework contribution: more colorful fireworks

_CodingChallenges/088-snowfall.md
https://editor.p5js.org/Kora-Lee/full/uyvc7UpAo
https://leekora.wixsite.com/artportfo
**Instagram:**
horizon_kl
**Twitter:**
=> 088 Snowfall Contribution: Skating Music Box

_CodingChallenges/021-mandelbrot-p5.md, _CodingChallenges/024-perlinnoiseflowfield.md
- [Interactive Mandelbrot Set with Shaders](https://vharivinay.github.io/mandelbrot-wShaders/)
- [Interactive Flowfield visualization using noise](https://vharivinay.github.io/generative/flowfiled/)
**Instagram:**
**Twitter:**
=> Added 2 entries - (1) _CodingChallenges/021-mandelbrot-p5.md; (2)_CodingChallenges/024-perlinnoiseflowfield.md

_CodingChallenges/051.1-astar.md
<https://www.youtube.com/watch?v=wRnOoiepbnE>
**Instagram:**
**Twitter:**
=> astar pathfinding for hex grid in processing

_CodingChallenges/077-recursion.md
Add Code of Recursion shows the geometry
**Instagram:**
**Twitter:**
=> Adding Recursion Code

_CodingChallenges/085-the-game-of-life.md
=> Game of life playground Contribution

_CodingChallenges/096-visualizing-pi.md, _CodingChallenges/100.1-neuroevolution-flappy-bird.md
=> Added project contribution to Coding Challenges 96 & 100
