- code_challenges/StarField/Star.pde
- code_challenges/StarField/StarField.pde
- some explanatory comments added, trying to support the learning.
- changed some “width” to “width/2” to show the whole 800 stars in the
canvas. (with the “width” value, some of theme were placed outside of the
real canvas).
> comments and "width" correction

- code_challenges/Reaction-Diffusion_p5.js/sketch.js
> Fixing colour component of reaction diffusion code challenge

- challenges/CC_34_DLA/walker.js
There was a minor bug in the `checkStuck` function.
(a+b)^2 = a^2 + b^2 + 2ab
> Bug in the distance checking

- sockets/public/sketch.js
pulling from https://github.com/CodingRainbow/Rainbow-Code
> fixed canvas and ellipse size

- challenges/CC_06_Mitosis_p5.js/cell.js
- challenges/CC_06_Mitosis_p5.js/sketch.js
Array was never declared. This breaks the code.
> Fixed missing list

- challenges/CC_29_SmartRockets/sketch.js
> Unused rocket

- challenges/CC_55_Roses_p5/index.html
- challenges/CC_55_Roses_p5/sketch.js
Removing decimal from input slider and boosted the range
Adding reduce denominator function for the loop
Only trigger draw when input data is changed
> Adding reduce denominator function for the loop

- challenges/CC_60_Butterfly_Wings/sketch.js
Per one of my earlier pull requests, resubmitted because I went off scope on that one.
The new loop requires changing da to keep the resolution the same.
> merge drawing steps into one loop

- challenges/CC_06_Mitosis_p5.js/sketch.js
The link to the video had a typo in it.
> Clean the comments

- challenges/CC_59_Steering_Text_Paths/README.md
Hello,
can you add my community low poly variation?
> Add community variation

- challenges/CC_59_Steering_Text_Paths/README.md
Just finished my variant, was hoping to add to the list.  Words morph into one another and added a splash of colour :)
Also source code was migrated to typescript (ES6).
> Added variant to the README

- challenges/CC_61_fractal_spirograph/README.md
Hello,
I created modification for your fractal spirograph challenge. It can render very large image. There is example https://raw.githubusercontent.com/JosefKuchar/p5-projects/master/CC_61_fractal_spirograph_large_render/render/render10000.png
> Create README.md and add first community variation

- challenges/CC_61_fractal_spirograph/README.md
Hello,
I added a simple demo page (https://josefkuchar.github.io/p5-projects/CC_61_fractal_spirograph_large_render/), so I think it's better to have this page as example
> Add demo page

- challenges/CC_61_fractal_spirograph_p5.js/index.html
- challenges/CC_61_fractal_spirograph_p5.js/libraries/p5.js
- challenges/CC_61_fractal_spirograph_p5.js/orbit.js
- challenges/CC_61_fractal_spirograph_p5.js/sketch.js
A literal translation of challenge 61 (Fractal Spirograph) into p5.js
> Translate challenge 61 into p5.js

- challenges/CC_27_Fireworks_2D_p5/firework.js
- challenges/CC_27_Fireworks_2D_p5/particle.js
- challenges/CC_27_Fireworks_2D_p5/sketch.js
Just updated this coding challenge with some consistent spacing and general clean up
I also added links to the site, patreon and video
> Add links, consistent spacing

- challenges/CC_31_FlappyBird/Bird.pde
- challenges/CC_31_FlappyBird/CC_31_FlappyBird.pde
- challenges/CC_31_FlappyBird/Pipe.pde
Added the links and made code a bit easier to read, also, I moved the gravity variable to the CC_31_FlappyBird.pde since it was already global. I think it's best to have all of the globals in a single place, even if they are only used in one file, I'll be happy to revert the change if you don't agree :)
> Add links, clean the code

- challenges/CC_59_Steering_Text_Paths/README.md
I know I'm a bit late but it just took a bit longer than planned.
I added a choice of fonts, vehicles 'split' and 'join' to accommodate for the needs of the new string and you can choose any colours you want.
> Added my variant to the README

- natureofcode/5.18_matter_intro/README.md
Hope the formatting is OK?
I aimed to put in useful and relevant links, but without cluttering too much.
> Creation of readme, now in more suitable directory

- challenges/CC_62_plinko/README.md
Created a readme doc for CC 62 Plinko. This has a table of links to other repos of this same project.
> Plinko README.md

- challenges/CC_03_Snake_game_p5.js/README.md
Adding README for variations of the Snake game (also my first p5.js project)
Thanks for the videos!
> Create README.md for CC_03_Snake_game_p5.js

- challenges/CC_63_unikitty_flag/CC_63_unikitty_flag.pde
I locked the whole left column of the flag, so it will connected to the pole.
`for(int i = 0; i < particles[0].length; i += 1){
particles[0][i].lock();
}`
> Better locking of the flag

- challenges/CC_01_StarField/README.md
- challenges/CC_02_MengerSponge/README.md
- challenges/CC_03_Snake_game_p5.js/README.md
- challenges/CC_04_PurpleRain/README.md
- challenges/CC_05_Space_invaders_p5.js/README.md
- challenges/CC_06_Mitosis_p5.js/README.md
- challenges/CC_07_SolarSystemGenerator/README.md
- challenges/CC_08_SolarSystemGenerator3D/README.md
- challenges/CC_09_SolarSystemGenerator3D_texture/README.md
- challenges/CC_10_Maze_DFS_p5.js/README.md
I have only added README in the folders for which a corresponding video exists, using the video descriptions with minor edits.
> Add README for first 10 coding challenges

- challenges/CC_67_2_binary_tree_viz/README.md
also added a link to my community variant in the README.md
> added README.md to CC_67_2_binary_tree_viz

- Processing/12_kinect/SimpleParticleSystem/ParticleSystem.pde
> fixed particle system vector origin

- challenges/CC_68_BFS_kevin_bacon/readme.md
I made a ruby version of the Breadth-First-Search code. Thought it was worth sharing
> Updated readme with link to ruby version

- challenges/CC_34_DLA/readme.md
Hey! I've made a quick and simple Processing version of the original P5Js/Javascript.
If you like it, please feel free to include the link in your repo.
> readme with Processing version link

- challenges/CC_30_phyllotaxis_p5.js/README.md
I like mathematical representation of things in nature, so naturally I went a little overboard with this one.   
Be sure to check out the gallery.
> Added readme.md with my version of the phyllotaxis challenge

- challenges/CC_59_Steering_Text_Paths/README.md
This is my first ever pull request. I added my project version to the readme file of the coding challenge 59.
> I added my project to readme. My first ever pull request! 

- challenges/CC_69_steering_evolution/README.md
// nex generation automation based on vehicles' healthiest survivor + some fine tinuning to the genetic algorithm
// press alt for switch debug on/off
// mouse press for adding new vehicles
> implementation of Evolve_Steering_Behaviors

- challenges/CC_65_2_binary_tree_viz/README.md
Adding a link to Simon Tiger's version of the binary tree
> Adding Simon Tiger's version of the binary tree

- CodingChallenges/CC_35_TSP/CC_35.4_TSP_GA/README.md
Added a community variation GitHub pointer and brief description.
> Added a community variation

- CodingChallenges/CC_35_TSP/CC_35.4_TSP_GA/README.md
@shiffman As discussed, here you go :)
> Added Port to typescript

- CodingChallenges/CC_71_minesweeperREADME.md
I have also added the previous users variation above mine (his pull request is still open - this should cover both)
@shiffman As noted above I have added the previous users variation which is still an open pull request
> Added variants file for CC_71 minesweeper

- CodingChallenges/CC_69_steering_evolution/README.md
Hello Daniel!
Can I add my variation of the Evolutionary-Steering-Behaviors  to the readme file?
> Update README.md(My variation)

- CodingChallenges/CC_17_SpaceColonizer_p5/tree.js
- Line 37: init record to max_dist instead of the abitrary 100000
- Line 45: remove the redundant condition checking
- Line 70: only reset if branch is attracted to some leaves, rather than reset all branches
> Minor improvements in tree grow()

- CodingChallenges/README.md
Hi, I've updated the readme.md to have a link between each folder and the corresponding coding challenge so it's easier to track which ones need to be ported from one language to the other. it's still pending to add a link for each coding challenge to each video on YouTube ;)
> Add a list of all coding challenges with a link to his folder

- CodingChallenges/CC_73_Frogger/README.md
Added Readme file to Frogger Coding Challenge with video links and a Community Variation.
> Added Readme file to Frogger Coding Challenge

- CodingChallenges/CC_50_2_CirclePackingImage/README.md
Fade out circles after time and use camera...
> Add Readme for Coding Challenge 50.2 (Circle Packing) with Link to own Variation

- CodingChallenges/CC_72_Frogger/CC_72_Frogger_original/CC_72_Frogger_original.pde
- CodingChallenges/CC_72_Frogger/CC_72_Frogger_original/Car.pde
- CodingChallenges/CC_72_Frogger/CC_72_Frogger_original/Frog.pde
- CodingChallenges/CC_72_Frogger/CC_72_Frogger_original/Log.pde
- CodingChallenges/CC_72_Frogger/CC_72_Frogger_original/Rectangle.pde
- CodingChallenges/CC_72_Frogger/CC_72_Frogger_refactored/CC_72_Frogger_refactored.pde
- CodingChallenges/CC_72_Frogger/CC_72_Frogger_refactored/Frog.pde
- CodingChallenges/CC_72_Frogger/CC_72_Frogger_refactored/Lane.pde
- CodingChallenges/CC_72_Frogger/CC_72_Frogger_refactored/Obstacle.pde
- CodingChallenges/CC_72_Frogger/CC_72_Frogger_refactored/Rectangle.pde
- CodingChallenges/CC_72_Frogger/README.md
- CodingChallenges/SimplePerceptron/Perceptron.pde
- CodingChallenges/SimplePerceptron/SimplePerceptron.pde
- CodingChallenges/SimplePerceptron/Training.pde
- Courses/intelligence_learning/session4/SimplePerceptron/Perceptron.pde
- Courses/intelligence_learning/session4/SimplePerceptron/SimplePerceptron.pde
- Courses/intelligence_learning/session4/SimplePerceptron/Training.pde
Moved Perceptron away from the coding challenges to the intelligence and learning session 4 folder
> Changed Coding Challenges numbering

- CodingChallenges/CC_31_FlappyBird_p5.js/README.md
Added the link to community examples of README.md
> Made a version of flappy bird.

- CodingChallenges/CC_51_astar/sketch.js
- CodingChallenges/CC_51_astar/spot.js
> fix typo line 29

- CodingChallenges/CC_74_Clock/README.md
Wall clock with realistic second hand movement.
> Submit Link to Clocks

- CodingChallenges/CC_74_Clock/README.md
Thanks Daniel, I had much fun!
> Added my clock to the README!

- CodingChallenges/CC_74_Clock/README.md
[Physics Based Clock](https://codepen.io/Alca/full/boeGBP/) - [Source](https://codepen.io/Alca/pen/boeGBP/right)
Made using [p5.js](https://p5js.org) and [Matter.js](http://brm.io/matter-js/).
The scene is set on load to have hidden pillars acting as walls and a cup at the bottom or each column. The time in hours and minutes are checked against the previously known time. Once the time has changed, it updates the last known time and triggers some squares to fall into view. The amount, position, color, and text label of the squares is all based on the time they are to display. From left to right, the columns are hours, minutes, and seconds. Hours and minutes drop in immediately while the seconds gradually fall every second during the minute they're counting up from. A highlighted hour and …
> Add Alca's Physics Based Clock

- CodingChallenges/CC_74_Clock/README.md
I made a binary clock, added the link in the readme. But here it is:
[Binary Clock](http://147lo.ch/clock-p5), [Source](http://147lo.ch/clock-p5-source)
> Update README so my clock is in

- CodingChallenges/CC_74_Clock/README.md
Atom trimmed some other lines. Sorry for the complication.
> Add Dave Briccetti’s 3D clock

- CodingChallenges/CC_74_Clock/README.md
> Adding my coding challenge sketch

- challenges/CC_29_SmartRockets/dna.js
- challenges/CC_29_SmartRockets/population.js
- challenges/CC_29_SmartRockets/rocket.js
- challenges/CC_29_SmartRockets/sketch.js
Documented the java script files of the smart rockets challenge
> Commented Smart Rockets located in challenges

- bots/node4_b_followbot/bot.js
If you follow someone, follow bot works again. It tweets like '.@yourTwitterName do you like rainbows'. So, to prevent this, we make an if clause using your twitter screenName.
> Update to Follow Bot

- CodingChallenges/CC_76_10PRINT/README.md
> Add twitter hashtag for more examples

- CodingChallenges/CC_35_TSP/CC_35.4_TSP_GA/ga.js
Using the 8th power for the fitness-function as described in your tutorial https://www.youtube.com/watch?v=HzaLIO9dLbA&feature=youtu.be&t=3m00s
Now, even 30 cities results in a nice route.
> update genetic programming example for TSP

- CodingChallenges/CC_76_10PRINT/README.md
* Edited community edition 10Print links to follow the format - [Demo] | [Source]
* Added Codepen demo for some projects
> Update README for 10Print Challenge

- CodingChallenges/CC_76_10PRINT/README.md
Added a small 10print doodle in A-Frame/threejs to the examples.
> add 10print 3D example from Michael Hazani

- CodingChallenges/CC_76_10PRINT/README.md
> Add 10PRINT example by WOLFI3654

- CodingChallenges/CC_77_Recursion/README.md
(And fix the formatting on another entry)
[Demo](https://codepen.io/Alca/full/pWaZaX/) | [Source](https://codepen.io/Alca/pen/pWaZaX/right)
[![Demo](https://i.gyazo.com/46786e3395933503d8021eaee0b05adc.gif)](https://i.gyazo.com/46786e3395933503d8021eaee0b05adc.mp4)
Click for mp4 version
> Add Alca's Recursion

- CodingChallenges/CC_76_10PRINT/README.md
My animated, infinite 10PRINT challenge using HTML and CSS instead of Canvas.
Demo: https://codepen.io/Alca/full/zEoBRq/
Source: https://codepen.io/Alca/pen/zEoBRq/right
> Add Alca's 10PRINT

- CodingChallenges/CC_76_10PRINT/README.md
> Added my submission

- CodingChallenges/CC_78_Simple_Particle_System/README.md
[Demo](https://codepen.io/Alca/full/MEVaBg) | [Source](https://codepen.io/Alca/pen/MEVaBg/right)
> Add Alca's Simple Particle System

- CodingChallenges/CC_76_10PRINT/README.md
Added Mark Uraine's 10print example to the list.
> Addition from Mark Uraine

- CodingChallenges/CC_76_10PRINT/README.md
Updated the demo and source paths for my submission
> Updated the demo and source paths

- CodingChallenges/CC_77_Recursion/README.md
Added my own version and reformatted the Community Editions
> Updated Readme

- CodingChallenges/CC_80_Voice_Chatbot_with_p5.Speech/README.md
Sorry for the trouble, but I’ve updated the YouTube video, which requires a change to the link. Thanks!
> Update Dave Briccetti’s “Stupid Nonsense Spoken Sentences”

- Tutorials/P5JS/p5.js/09/9.15_p5.js_2D_Arrays/index.html
- Tutorials/P5JS/p5.js/09/9.15_p5.js_2D_Arrays/libraries/p5.dom.js
- Tutorials/P5JS/p5.js/09/9.15_p5.js_2D_Arrays/libraries/p5.js
- Tutorials/P5JS/p5.js/09/9.15_p5.js_2D_Arrays/libraries/p5.sound.js
- Tutorials/P5JS/p5.js/09/9.15_p5.js_2D_Arrays/sketch.js
- Tutorials/P5JS/p5.js/09/9.17_p5.js_Arguments/index.html
- Tutorials/P5JS/p5.js/09/9.17_p5.js_Arguments/libraries/p5.dom.js
- Tutorials/P5JS/p5.js/09/9.17_p5.js_Arguments/libraries/p5.js
- Tutorials/P5JS/p5.js/09/9.17_p5.js_Arguments/libraries/p5.sound.js
- Tutorials/P5JS/p5.js/09/9.17_p5.js_Arguments/sketch.js
> Added tutorial 9.15 & 9.17 code

- Tutorials/P5JS/p5.js/09/9.01_p5.js_Transformation_Pt.1/index.html
- Tutorials/P5JS/p5.js/09/9.01_p5.js_Transformation_Pt.1/libraries/p5.dom.js
- Tutorials/P5JS/p5.js/09/9.01_p5.js_Transformation_Pt.1/libraries/p5.js
- Tutorials/P5JS/p5.js/09/9.01_p5.js_Transformation_Pt.1/libraries/p5.sound.js
- Tutorials/P5JS/p5.js/09/9.01_p5.js_Transformation_Pt.1/sketch.js
- Tutorials/P5JS/p5.js/09/9.02_p5.js_Transformation_Pt.2/index.html
- Tutorials/P5JS/p5.js/09/9.02_p5.js_Transformation_Pt.2/libraries/p5.dom.js
- Tutorials/P5JS/p5.js/09/9.02_p5.js_Transformation_Pt.2/libraries/p5.js
- Tutorials/P5JS/p5.js/09/9.02_p5.js_Transformation_Pt.2/libraries/p5.sound.js
- Tutorials/P5JS/p5.js/09/9.02_p5.js_Transformation_Pt.2/sketch.js
- Tutorials/P5JS/p5.js/09/9.03_p5.js_Transformation_Pt.3/index.html
- Tutorials/P5JS/p5.js/09/9.03_p5.js_Transformation_Pt.3/libraries/p5.dom.js
- Tutorials/P5JS/p5.js/09/9.03_p5.js_Transformation_Pt.3/libraries/p5.js
- Tutorials/P5JS/p5.js/09/9.03_p5.js_Transformation_Pt.3/libraries/p5.sound.js
- Tutorials/P5JS/p5.js/09/9.03_p5.js_Transformation_Pt.3/sketch.js
(issue #293)
Note that 9.3 and 9.2 are actually the exact same (also in the tutorials), but I included it anyway.
> Added tutorial 9.1-9.3 code

- Tutorials/P5JS/p5.js/09/9.19_p5.js_Prototypes/index.html
- Tutorials/P5JS/p5.js/09/9.19_p5.js_Prototypes/libraries/p5.dom.js
- Tutorials/P5JS/p5.js/09/9.19_p5.js_Prototypes/libraries/p5.js
- Tutorials/P5JS/p5.js/09/9.19_p5.js_Prototypes/libraries/p5.sound.js
- Tutorials/P5JS/p5.js/09/9.19_p5.js_Prototypes/sketch.js
- Tutorials/P5JS/p5.js/09/9.20_p5.js_Polar_Coordinates/index.html
- Tutorials/P5JS/p5.js/09/9.20_p5.js_Polar_Coordinates/libraries/p5.dom.js
- Tutorials/P5JS/p5.js/09/9.20_p5.js_Polar_Coordinates/libraries/p5.js
- Tutorials/P5JS/p5.js/09/9.20_p5.js_Polar_Coordinates/libraries/p5.sound.js
- Tutorials/P5JS/p5.js/09/9.20_p5.js_Polar_Coordinates/sketch.js
> Added tutorial code for 9.19 & 9.20

- CodingChallenges/CC_10_Maze_DFS/CC_10_Maze_DFS.pde
- CodingChallenges/CC_10_Maze_DFS/README.md
- CodingChallenges/CC_10_Maze_DFS/cell.pde
> Ported CC 10 to Processing

- CodingChallenges/CC_01_StarField_p5.js/README.md
Added README.md for community versions
Added my version of the challenge to the readme
> Add community version for Coding Challenge #1

- CodingChallenges/CC_82_Image_Chrome_Extension_The_Ex-Kitten-sion/README.md
v1 (Thank you for making the video series.)
> Relaxing bears extension added

- CodingChallenges/CC_03_Snake_game_p5.js/README.md
Hola!
I added my variation of the snake game.
🌈 thanks!!
> elena-in-code variation

- CodingChallenges/CC_76_10PRINT/sketch.js
Just modified it from 0.9 to 0.5.
> the probability was set too high.

- CodingChallenges/CC_12_LorenzAttractor/README.md
- CodingChallenges/Coding_Challenge__76__10PRINT_Processing/Coding_Challenge__76__10PRINT_Processing.pde
Made Processing version of 10PRINT.
it is taking 0.5 as probability , not 0.9  as stated in Pull request #320
> Added Coding Challenge 76 10PRINT Processing #267 and README of CC_12_LorenzAttractor #128 .

- CodingChallenges/CC_86_beesandbombs/README.md
> Hear is a example with a link to my code

- CodingChallenges/CC_86_beesandbombs/README.md
Added my version of the challenge, and removed the link that links to this page.
> Added my version of the challenge

- CodingChallenges/CC_86_beesandbombs/README.md
Just adding a link to the readme
> Adding my contribution

- CodingChallenges/CC_74_Clock_Processing/CC_74_Clock_Processing.pde
- CodingChallenges/CC_74_Clock_Processing/README.md
- CodingChallenges/CC_77_Recursion_Processing/CC_77_Recursion_Processing.pde
- CodingChallenges/CC_77_Recursion_Processing/README.md
- CodingChallenges/CC_78_Simple_Particle_System_Processing/CC_78_Simple_Particle_System_Processing.pde
- CodingChallenges/CC_78_Simple_Particle_System_Processing/Particle.pde
- CodingChallenges/CC_78_Simple_Particle_System_Processing/README.md
> Processing port for CC 74, 77 and 79

- CodingChallenges/CC_86_beesandbombs/README.md
I changed my Github username, just updating the links.
> Changed my name

- CodingChallenges/CC_86_beesandbombs/README.md
Includes toggle to change between Flowing and Stationary Rainbow colours
> Added my variant to the @beesandbombs challenge

- _CodingChallenges/19-superellipse.md
- _CodingChallenges/28-metaballs.md
- _CodingChallenges/38-work-interactor.md
- _CodingChallenges/39-madlibs.md
- _CodingChallenges/40.3-tf-idf.md
- _CodingChallenges/41-clappy-bird.md
- _CodingChallenges/42.1-markov-chains.md
- _CodingChallenges/42.2-markov-chains.md
- _CodingChallenges/45-firebasesavingdrawing.md
- _CodingChallenges/74-clock.md
Referring to issue #373 
Every video from the coding challenge playlist (https://www.youtube.com/playlist?list=PLRqwX-V7Uu6ZiZxtDDRCi6uhfTH4FilpH) now has a .md file.
Pull requesting so @nilsweb can take a look at it before merging.
> Added last few .md files to _CodingChallenges

- CodingChallenges/CC_15_FractalTreeArray_Processing/Branch.pde
- CodingChallenges/CC_15_FractalTreeArray_Processing/CC_15_FractalTreeArray_Processing.pde
Added Processing Version for Fractal Tree Array (Object Oriented)
Used ArrayList instead of Arrays (Java Arrays have a deterministic size, the ArrayLists are more than Javascript Arrays)
> Added Processingversion of CC_15_FractalTreeArray #267

- CodingChallenges/CC_01_StarField/README.md
Changed the readme to add a link to the swift version of this Coding Challenge.
I thought I would be a nice idea to create Swift versions of each Coding Challenge. So I started with the first one and made it available on Github. Hope you enjoy it and will accept the link to my version of the challenge.
> Swift implementation of the first Coding Challenge

- CodingChallenges/CC_89_langtonsant/README.md
- _CodingChallenges/89-langtonsant.md
Referring to issue #400,
Thought it'd be good to try one out before I start bulk-moving them and find out I did something wrong. Let me know if this looks good or if anything should be different.
> Try-out for converting community contributions to the new website

- _CodingChallenges/90-floyd-steinberg-dithering.md
Added the contributions section and my contribution.
> Added 'contributions'

- _CodingChallenges/69.4-steering-evolution.md
fixed bug preventing it to show on the webpage
> Update 69.4 for contribution

- _Streams/117.2_Unit_Testing_and_CI_with_CircleCI_Part_2.md
Livestream #117.2, fully linked
> Livestream #117.2

- _Streams/119_Solving_Merge_Conflicts_and_XOR_Problem.md
Livestream  #119 almost fully updated, lacks links to "Resolving merge conflicts" and "XOR Problem" due to the videos not being uploaded yet.
> Livestream #119

- _CodingChallenges/93-double-pendulum.md
p5.js version with drag+drop and variable sliders
> Add contribution to #93

- _CodingChallenges/14-fractaltree.md
Here is my example of recursive fractal tree animation on codepen.
> My contribution to Fractal Tree Conding Challenge

- _jekyll/includes/2-base/navigation.html
This should take care of this
https://github.com/CodingTrain/website/issues/420
> Added link to github in the header

- _CodingChallenges/17-spacecolonizer.md
The tree used space-colonization algorithm and will eventually grow a sakura flower represented as a bright purplish-pink circle
> Sakura tree blossoms

- _CodingChallenges/10.4-maze-dfs-p5.md
It's not much, but it's something :)
> Adding my version of the maze generator

- _Streams/112-happy-holidays.md
> Livestream #112

- _CodingChallenges/94.1-2048.md
Added a reference to my C# / Discord BOT project.
- The repository contains the C# version, Discord BOT implementation AND my own Coding Challenge videos.
> 2048 Contribution - C# + Discord BOT

- README.md
Sir i find that writing in this way will be more easy for understanding.
> Sentence correction

- _CodingChallenges/94.3-2048.md
Classic 2048 game in rapid mode with chain reaction type addition. 
Created in javascipt using jquery framework & juery touchSwipe add-on for swipe events in mobile browser.
Supports both swipe & arrow keys.
> Please add my custom version of 2048

- _Tutorials/16-javascript-es6/16.7-reduce.md
> Fixed incorrect video id

- _CodingChallenges/94.1-2048.md
> Add my contribution

- _CodingChallenges/51.1-astar.md
Added in a little ES6 + restart with new random map a moment after the algorithm completes
> Add contribution to #51

- CONTRIBUTING.md
As suggested by @shiffman in #495.
Closes #495.
> Added a notice to include a URL to the running example in a PRs description in CONTRIBUTING.md

- _CodingChallenges/90-floyd-steinberg-dithering.md
I was so exited to submit my contribution, I forgot to check the links work. I just fixed them.
> Fixed broken links to coding challange 90.

- CodingChallenges/CC_57_Earthquake_Viz/README.md
A 3D version of Dan Shiffman's Coding Challenge 57: Earthquake Data Visualization in p5.js.
> Adding a link to code under community editions

- _CodingChallenges/95-approximating-pi.md
- _CodingChallenges/96-visualizing-pi.md
- _CodingChallenges/97.1-book-of-pi.md
- _CodingChallenges/97.2-book-of-pi.md
Added .md files for Coding Challenges 95, 96, 97.1 and 97.2
Path to the code to be added when the code is uploaded to the repo.
> Added CC95 to CC97(missing code repo link)

- _Streams/122-filter-sort-2048.md
- _Streams/123.1-doodle-classifier.md
- _Streams/123.2-doodle-classifier-continued.md
- _Streams/124-upcoming.md
- _Streams/124.1-linting-neuroevolution.md
- _Streams/124.2-linting-neuroevolution-continued.md
- _Streams/125-loadbytes-pull-request.md
- _Streams/126.1-pi-day.md
- _Streams/126.2-pi-day-continued.md
Added Live Stream 122 to 126 to the /_Streams directory
> Added Live Stream 122 to 126

- _CodingChallenges/10.1-maze-dfs-p5.md
- _CodingChallenges/10.4-maze-dfs-p5.md
- _CodingChallenges/46.2-asteroids-part-2.md
- _CodingChallenges/51.1-astar.md
- _CodingChallenges/51.2-astar.md
- _CodingChallenges/69.1-steering-evolution.md
- _CodingChallenges/69.4-steering-evolution.md
- _CodingChallenges/94.1-2048.md
- _CodingChallenges/94.3-2048.md
- unit_testing/yaml.test.js
> Enforce multi part contributions restrictions

- _CodingChallenges/74-clock.md
I added my contribution to the 74th Coding Challenge about making a clock!
> Added a contribution

- _CodingChallenges/50.1-circlepackinganimated.md
Fixup PR #543
Make link to gif not start download
> Fixup: Add (existing) contribution to Coding Challenge 50 (website)

- _CodingChallenges/98.1-quadtree.md
- _CodingChallenges/98.2-quadtree.md
**Added the following files based on info from Youtube videos:**
_CodingChallenges/98.1-quadtree.md
_CodingChallenges/98.2-quadtree.md
(The date in part 2 might need modification once the youtube video is listed.)
**Added my contribution with Mouse-Wheel control to range size**
For live example see https://alpha.editor.p5js.org/full/HkDKgnIcz
For Source see: https://github.com/romibi/p5.js-Playground/tree/master/CC_98_QuadTree
**Open Questions:**
- Are readme.md files in the CodingChallenges/ subfolders with contributions now unwanted or still welcome?
- Is that correct that contributions in these files always have to be in part 1?
>  Coding Challenge 98: Add quadtree.md files and contribution

- _CodingChallenges/97.1-book-of-pi.md
Based on Coding Challenge 97.1 I implemented the idea to represent the digits of pi with polygons where the number of edges equals the corresponding digit. [Here](https://github.com/VegaVen2ra/CC_97_Book_of_Pi_Polygons/blob/master/bookofpi-1million-polygons.pdf) I uploaded the created pdf.
> Book of Pi with polygons

- _CodingChallenges/99-color-predictor.md
I have created a version where training data is based on color contrast rather then on a set threshold.
> Add a contribution

- _CodingChallenges/95-approximating-pi.md
I made a p5 version of this sketch:
http://mogensmeissner.tk/coding/examples/pi/p5/empty-example/index.html
> Update 95-approximating-pi.md Community contribution

- CodingChallenges/CC_100_NeuroEvolution_FlappyBird/ga.js
ahh... looks like you have left some vars in your code.
> vars to let

- CodingChallenges/CC_29_SmartRockets/population.js
"eqaul" should be spelled "equal"
> fixed a typo

- CodingChallenges/CC_103_Flames/CC_103_Flames.pde
Here's the code with an important bug fix!
Correct:
```java
newC = newC * 0.25 - brightness(c5);
buffer2.pixels[index4] = color(newC);
```
Incorrect:
```java
newC = newC - brightness(c5);
buffer2.pixels[index4] = color(newC * 0.25);
```
> Code for Challenge 103: Fire Effect

- CodingChallenges/CC_103_Flames/CC_103_Flames.pde
those are clearly not 2D water ripples
> fixed the coding challenge's name in the comment

- _CodingChallenges/103-fire-effect.md
Added my version of the Fire Effect coding challenge.
> Added 103-fire-effect contribution

- CodingChallenges/CC_104_tf_linear_regression/index.html
- CodingChallenges/CC_104_tf_linear_regression/sketch.js
- Tutorials/P5JS/16_promises/11_promises/index.html
- Tutorials/P5JS/16_promises/11_promises/sketch.js
- Tutorials/P5JS/16_promises/12_promises_make_your_own/index.html
- Tutorials/P5JS/16_promises/12_promises_make_your_own/sketch.js
- Tutorials/P5JS/16_promises/13_16_async_await/index.html
- Tutorials/P5JS/16_promises/13_16_async_await/sketch.js
cc @blinkityblank 
Unfortunately I didn't bother to save the code in between each and every Promises video. So the last code example is just the end result of 16.13-16.16. If anyone would like to help separate out the code for each video I'd love that!
> code from promises and linear regression challenge

- _CodingChallenges/105-polynomial-regression-tfjs.md
Hi,
just a quick pull request to add my own version to the projects contributions.
[Live Demo](https://hablwgq.github.io/coding/p5js%20polynomial%20regression/)
> Add own contribution to polynomial regression

- _CodingChallenges/064.1-forward-kinematics.md
Based on the result Dan shows in coding challenge 64.2 "inverse kinematics".
live example: 
http://www.quillaja.net/snakes/sketch.html
code:
http://www.quillaja.net/snakes/
https://github.com/quillaja/p5-sketches/tree/master/kinematics
> Added a community contribution to CC64.2

- _CodingChallenges/105-polynomial-regression-tfjs.md
Polynomial Regression in p5.js with sliders for degree and learning rate
> Add Community Contribution to CC105

- CodingChallenges/CC_057_Earthquake_Viz/sketch.js
- CodingChallenges/CC_057_Earthquake_Viz_Processing/CC_057_Earthquake_Viz_Processing.pde
- CodingChallenges/CC_058_EarthQuakeViz3D/CC_058_EarthQuakeViz3D.pde
- CodingChallenges/CC_073_Acrostic/sketch.js
- Tutorials/P5JS/16_promises/11_promises/sketch.js
- Tutorials/P5JS/16_promises/13_16_async_await/sketch.js
- Tutorials/P5JS/p5.js/10/10.05_p5.js_Working_With_APIs/sketch.js
- Tutorials/P5JS/p5.js/10/10.06_p5.js_api_query_user_input/sketch.js
- Tutorials/P5JS/p5.js/10/10.08_p5.js_Wordnik_API/sketch.js
- Tutorials/P5JS/p5.js/10/10.09_p5.js_New_York_Times_API/sketch.js
- Tutorials/P5JS/p5.js/10/10.10_p5.js_giphy_api/sketch.js
> Convert HTTP urls to HTTPS

- CodingChallenges/CC_108_barnsley_fern/CC_108_barnsley_fern.pde
Here is the code to link to from the markdown page @blinkityblank.
> Challenge 108 Barnsley Fern Code

- _CodingChallenges/108-barnsley-fern.md
Added a link to a C++ implementation of the Barnsley Fern algorithm which renders the fern in a console with unicode characters.
https://www.youtube.com/watch?v=3Q5tAWkAEBc
> Added a community contribution.

- _CodingChallenges/109-subscribers-map.md
> add first contribution to mapping coding challenge

- CodingChallenges/CC_089_langtonsant/README.md
I am adding my contribution to the langton's ant coding challenge, langton's paint brush.  This is my first contribution, and I am honestly a little confused on the process, so thank you for bearing with me. There are screenshots in the screenshot folder of my repository. After reading the contribution guideline I see that the code in the repository should match the code in the youtube tutorials. I definitely borrowed ideas from the youtube video, but I did start with a blank file so the codes are quite a bit different. 
Here is the link to the screenshot of my contribution: https://github.com/Leighzer/Langtons_Paint_Brush/blob/master/langtons_paint_brush/Screenshots/PNG/screen-2751.png
> Adding Langton's Paint Brush

- _CodingChallenges/101-may-the-4th.md
thanks for inspiring a really fun project
> add javascript implementation

- Courses/intelligence_learning/session7/07_12_color_classifier/colorData.json
- Courses/intelligence_learning/session7/07_12_color_classifier/index.html
- Courses/intelligence_learning/session7/07_12_color_classifier/sketch.js
- Courses/intelligence_learning/session7/07_??_color_classifier/colorData.json
- Courses/intelligence_learning/session7/07_??_color_classifier/index.html
- Courses/intelligence_learning/session7/07_??_color_classifier/sketch.js
- Courses/intelligence_learning/session7/07_??_download_data/index.html
- Courses/intelligence_learning/session7/07_??_download_data/sketch.js
Right now there are three folders. 07_12 represents the code from the end of video 7.12. I saved at two other points during the 12 part series. I have no idea which videos they match with. Ideally I would love help getting the code uploaded that matches the end of each video.
Playlist:
https://www.youtube.com/playlist?list=PLRqwX-V7Uu6bmMRCIoTi72aNWHo7epX4L
@nonas-hunter this is something I would love help with!
@blinkityblank note that the link to the community version can be added to all the videos:
Classifer:  https://codingtrain.github.io/ColorClassifer-TensorFlow.js
Code: https://github.com/CodingTrain/ColorClassifer-TensorFlow.js
Data collection: https://codingtrain.github.io/CrowdSourceColorData
Code: https://github.com/CodingTrain/CrowdSourceColorData
And in theory we could add …
> Code for Session 7 Intelligence and Learning

- _CodingChallenges/011-perlinnoiseterrain.md
* Adding contribution section
* Adding Three.JS Implementation
> Adding 011 Coding Challenge Contribution

- Courses/intelligence_learning/session7/7_1_color_classifier/sketch.js
- Courses/intelligence_learning/session7/7_2_color_classifier/sketch.js
- Courses/intelligence_learning/session7/7_3_color_classifier/index.html
- Courses/intelligence_learning/session7/7_3_color_classifier/sketch.js
- Courses/intelligence_learning/session7/7_4_color_classifier/index.html
- Courses/intelligence_learning/session7/7_4_color_classifier/sketch.js
I added the code for videos 3 and 4 which covers visualizing the data. The code works perfectly as shown in the video :)
I did not do any extra formatting or styling so final product looks the exact same way it does at the end of each video.
I also added author comments to the beginning of the code for videos 1 & 2.
> Session 7 - Video 3 & 4

- CodingChallenges/CC_110_recaman/index.html
- CodingChallenges/CC_110_recaman/sketch.js
- CodingChallenges/CC_110_recaman_music/index.html
- CodingChallenges/CC_110_recaman_music/sketch.js
> code for recaman challenge 110

- _CodingChallenges/110.1-recaman-sequence.md
Hello, I've modified the code so that the arc is animated instead of appearing all at once,
in my codepen the time between new numbers is set at 1s (1000ms).
Hopefully I modified the file correctly :)
link to working example: https://codepen.io/jacekWyroba/full/ajyaJE/
> Recamán's Sequence - Part 1 animated arc

- CodingChallenges/CC_112_3D_Rendering/CC_112_3D_Rendering.pde
- CodingChallenges/CC_112_3D_Rendering/matrix.pde
- CodingChallenges/CC_113_Hypercube/CC_113_Hypercube.pde
- CodingChallenges/CC_113_Hypercube/P4Vector.pde
- CodingChallenges/CC_113_Hypercube/matrix.pde
- CodingChallenges/CC_114_BubbleSortViz/CC_114_BubbleSortViz.pde
- Courses/beginner_ml5/04_feature_extractor_classification/index.html
- Courses/beginner_ml5/04_feature_extractor_classification/sketch.js
- Courses/beginner_ml5/05_feature_extractor_regression/index.html
- Courses/beginner_ml5/05_feature_extractor_regression/sketch.js
Code for challenges 112-114 and the new ml5 tutorial videos
> Coding Challenge 112-114 and ml5 video code

- _CodingChallenges/107-sandpiles.md
Finally figured out how to contribute to the coding train, so I'm currently adding all of my previous things ! 😃
I actually have two contributions for this that are kinda related so I made two different sections
> Added my contribution to Coding Challenge #107

- _CodingChallenges/110.1-recaman-sequence.md
Finally figured out how to contribute to the coding train, so I'm currently adding all of my previous things ! 😃
> Added my contribution to Coding Challenge #110

- _CodingChallenges/114-bubble-sort.md
I created this with P5.js in like 15 minutes, so ist not very advanced but it fulfills ist purpose :)
> Added my implemention of the bubblesort visualizer

- _CodingChallenges/056-attraction-repulsion.md
https://github.com/XoMute/Python/blob/master/Attraction%20and%20Repulsion%20Forces/particles_demo.gif
> Added my contribution to Coding Challenge #56

- unit_testing/package.json
As per: https://github.com/jsdom/jsdom/issues/2304
> fixing testing issue?

- _CodingChallenges/071-minesweeper.md
Fix part of remarks in issue #723
> Fix KO url contribution

- _config.yml
- _jekyll/layouts/video.html
- assets/css/3-layouts/_video.sass
Fixed Issue #654.
Added View Code button and adjusted proper SASS.
Added GitHub url to config.yml to generate View Code link.
> Added View Code buttons to Tutorials

- _CodingChallenges/116-lissajous.md
Added Coding Challenge Contribution to 116-lissajous.md
> Added contribution

- _Tutorials/9-additional-topics/9.9-minimum-spanning-tree.md
My contribution: [Prim's Algorithm Visualized](https://editor.p5js.org/Bixbite/sketches/SJk59LrKX)
> Added p5.js Tutorial 9.9 file, and a contribution

- _CodingChallenges/116-lissajous.md
> Community Contribution CC116

- _CodingChallenges/021-mandelbrot-p5.md
> Add community contribution CC21

- _CodingChallenges/116-lissajous.md
I would like to submit my contribution for the Lissajous Table coding challenge.
I plan on adding the ability to change the number of circles shown on the screen!
I would love it if this would pass and the gh-page gets listed under the Coding Challenge!
Thanks in advance!
> Another Lissajous Table contribution

- _CodingChallenges/114-bubble-sort.md
- _CodingChallenges/115-snake-game-redux.md
Snake Game Tutorial using Vanilla JS
> Community Contribution CC #115

- _CodingChallenges/117-seven-segment.md
Added a seven segment display which supports multiple digits: https://editor.p5js.org/full/SkqBEHGs7
> Added multiple digit seven segment display

- _CodingChallenges/117-seven-segment.md
Clicking the individual segments will toggle them on/off. Pressing a numpad number key will display the corresponding number.
https://gfycat.com/EsteemedDamagedLadybird
> Add contribution to CC 117

- _CodingChallenges/113-hypercube.md
Site visualizes cubes of n-dimensions (up to 12, currently) and allows animated rotation of any planes. Live code is at https://aaronjenson.github.io/Projection/.
> Add contribution to 113-hypercube

- CodingChallenges/CC_117_7_Segment_Display/CC_117_7_Segment_Display.pde
- _CodingChallenges/117-seven-segment.md
Add Code for Challenge 117: Seven Segment Display #771
Processing version for the seven segment code made on code challenge number 117
> Solving Issue #771 - Add processing version for coding challenge 117 - seven segment display

- _CodingChallenges/117-seven-segment.md
Wrote a seven segment display visualisation and tried to use a cascading switch statement to exploit that some numbers can be drawn as a combination of other numbers.
> Added a community contribution o/

- _CodingChallenges/115-snake-game-redux.md
- _CodingChallenges/116-lissajous.md
- _config.yml
- _jekyll/layouts/video.html
- unit_testing/formats.js
fix #738 Adds the option to add a web_editor
> Add web editor to video page

- CodingChallenges/CC_024_PerlinNoiseFlowField_Processing/Particle.pde
- CodingChallenges/CC_024_PerlinNoiseFlowField_Processing/flowfield.pde
- CodingChallenges/CC_024_PerlinNoiseFlowField_Processing/perlin_noise_flow_field.pde
- _CodingChallenges/024-perlinnoiseflowfield.md
> added a processing version of Perlin Noise Flow Field challenge

- _CodingChallenges/085-the-game-of-life.md
I built a version of Game of Life that allows the user to edit the grid, to pause and to change the framerate.
https://doxanthropos.github.io/sketchbook/2018101901/
> Community Contribution: Game of Life in p5 with editable grid

- CodingChallenges/CC_107_sandpiles_p5.js/index.html
- CodingChallenges/CC_107_sandpiles_p5.js/sketch.js
This PR first adds a straight port (only the required changes) of the Processing code, and then adds some changes on top of that to make it run faster (since it was being very slow - less than 0.4 fps on my PC).
I tried to keep the final result close to the original Processing code, and kept the changes in a separate commit so people can see what I changed (and hopefully why) if they want to.
> Add port to p5.js of coding challenge 107 (sandpiles)

- Tutorials/P5JS/16_promises/13_16_async_await/sketch.js
> Switch from let to const

- _jekyll/layouts/base.html
> Added the "lang" attribute on "html" for accessibility reasons (#792)

- _CodingChallenges/117-seven-segment.md
Sebastien Raynaud' contribution for #117 Seven Segment Display
> Added coding challenge contribution

- _CodingChallenges/116-lissajous.md
You can find a working version of my contribution here:
https://codepen.io/lpato/full/KGebJa/
> Add contribution to the Lissajous CC

- _CodingChallenges/119-binary-decimal-conversion.md
Based on the binary visualization from Challenge 119, I build an ASCII to binary visualization: https://doxanthropos.github.io/sketchbook/2018102301/
> Community contribution to #119: Ascii to binary converter

- _CodingChallenges/117-seven-segment.md
URL: https://codepen.io/Alca/full/aRqozv/
Source: https://codepen.io/Alca/pen/aRqozv
> Add my 7-segment display contribution

- _CodingChallenges/117-seven-segment.md
Coding Challenge 117 Seven Segment Display =)
> Maksuel's contribution =)

- _CodingChallenges/024-perlinnoiseflowfield.md
- _CodingChallenges/060-butterfly-wings.md
- _CodingChallenges/069.1-steering-evolution.md
- _CodingChallenges/069.5-steering-evolution.md
- _CodingChallenges/107-sandpiles.md
- _CodingChallenges/108-barnsley-fern.md
- _CodingChallenges/113-hypercube.md
Coding Challenges Contributions
- CC 024
- CC 060
- CC 069.5
- CC 107
- CC 108
- CC 113
> Add CC Contributions

- _CodingChallenges/121-logo-interpreter.md
https://davebsoft.com/software/logo-3d/
> Add 3D Logo Experiment

- Courses/beginner_ml5/06_feature_extractor_load_save/index.html
- Courses/beginner_ml5/06_feature_extractor_load_save/sketch.js
(this is the code from 11/9 live stream. I'm not sure if I should make this two examples or just one? For now the loading is commented out.)
> Code from save/load live stream

- _CodingChallenges/118.1-mastodon-fractal-tree.md
- Mention @chopokopx@botsin.space with RGB values to get a drawing
> Contribution for Mastodon bot

- _CodingChallenges/094.1-2048.md
> Repair contribution issue

- _CodingChallenges/021-mandelbrot-p5.md
https://twitter.com/dedowsdi/status/1063024950808764417
> Mandelbrot Set in OpenGL, smooth histogram colored

- _CodingChallenges/121.1-logo-interpreter.md
Add my logo interpreter to the page
> Add a link to my logo interpreter

- _CodingChallenges/123.1-chaos-game.md
https://aaserver.net/projects/The_Chaos_Game/
> New contribution

- _CodingChallenges/123.1-chaos-game.md
My version of the Chaos Game, with sliders to control various parameters, and leveraging vector properties to color the pixels.
> Contribution from John Pisello (John30013)

- _CodingChallenges/124-flocking-boids.md
Added QuadTree optimization to the p5.js web editor sketch so we can crank up the size of those flocks.
> QuadTree community contribution

- _CodingChallenges/124-flocking-boids.md
Colorful regular polygons flocking
[https://editor.p5js.org/jcponce/sketches/BkCDZSR1V](url)
> Sharing colorful regular polygons flocking

- _CodingChallenges/124-flocking-boids.md
My Contribution to coding challenge #124.
added small Creatures, Predators, Avoiders, Food, Poison etc.
> Contribution to coding challenge #124 : Evolution Aquarium

- _CodingChallenges/124-flocking-boids.md
I added a quadtree optimization and created 8 different scenes for the same flock, with different colors and values for the alignment, cohesion and seperation and some added properties. 
link: https://editor.p5js.org/n-athan/full/SJV0l4EgE
> Added contribution to challenge #124

- _CodingChallenges/124-flocking-boids.md
It uses p5.js, three.js and a custom made feedback-buffer-object engine to calculate the accelerations, velocities and positions of 25.600 particles (160*160) using the GPU.
> Contributing my 3D flocking simulator (25.600 particles)

- _jekyll/includes/3-modules/code-variation-dropdown.html
@nilsweb What do you think about that? Was that thought?
> Added target="_blank" to code-variation-dropdown.html

- _CodingChallenges/108-barnsley-fern.md
Using C++ and GLUT libraries. Compilation/execution instructions are in the README of the linked repository.
> Added my C++ implementation of the Barnsley Fern

- _CodingChallenges/125-fourier-series.md
Rainbow Fourier seres: Sawtooth
> Rainbow Fourier seres: Sawtooth

- CodingChallenges/CC_116_Lissajous/P5/curve.js
- CodingChallenges/CC_116_Lissajous/P5/index.html
- CodingChallenges/CC_116_Lissajous/P5/sketch.js
Simple changes for javascript.
> Transcribe Lissajous to javascript.

- CodingChallenges/CC_113_Hypercube/P5/P4Vector.js
- CodingChallenges/CC_113_Hypercube/P5/index.html
- CodingChallenges/CC_113_Hypercube/P5/matrix.js
- CodingChallenges/CC_113_Hypercube/P5/sketch.js
Would love to create a better matrix math library or use one of the existing ones. The .array() function, and set() operators of the p5.Vector would seem to make this easier, but the arrays are one dimensional, so it really feels like there needs to be a matrix class, with corresponding conversions. (and I am thinking out loud: inside p5.js)
I say this because I used similar, **but slightly different code** for another one of the samples. Then I used that one to create **a slightly different one** I hooked up to the Barnsley Fern example (which was doing the algebraic equivalent).
> Transcribe Hypercube to javascript.

- _CodingChallenges/102-2d-water-ripple.md
Oh C'mon this is valid YAML. I checked it. CircleCi has it in for me I'm sure
> WaterRipple Update

- CodingChallenges/CC_019_Superellipse/P5/index.html
- CodingChallenges/CC_019_Superellipse/P5/sketch.js
- _CodingChallenges/019-superellipse.md
Fixes #801
@shiffman Could you please confirm that this is the code from the video 🥇 I will port this challenge to Processing and add the web editor version later on.
> Code for CC19

- _CodingChallenges/125-fourier-series.md
Added a link to a processing program I wrote based on this CodingChallenge.
> Added contribution.

- CodingChallenges/CC_128_SketchRNN_Snowflakes/P5/index.html
- CodingChallenges/CC_128_SketchRNN_Snowflakes/P5/sketch.js
- CodingChallenges/CC_129_Koch_Snowflake/P5/index.html
- CodingChallenges/CC_129_Koch_Snowflake/P5/segment.js
- CodingChallenges/CC_129_Koch_Snowflake/P5/sketch.js
- CodingChallenges/CC_129_Koch_Snowflake/Processing/CC_129_Koch_Snowflake/CC_129_Koch_Snowflake.pde
- CodingChallenges/CC_129_Koch_Snowflake/Processing/CC_129_Koch_Snowflake/Segment.pde
> Snowflake SketchRNN and Koch Snowflake Code

- _CodingChallenges/127-snowflake-brownian.md
Implemented spatial partitioning to check intersections faster and some other refactoring stuff
Only draw particles once and don't clear screen
Bonus spiderweb-like snowflake mode created by accident
link to demo gif:
https://thumbs.gfycat.com/SaneBelovedHerring-size_restricted.gif
> Add Optimized Brownian Snowflake in Processing

- _CodingChallenges/127-snowflake-brownian.md
This PR adds the ES6 Brownian Snowflake to the Brownian Snowflake
challenge.
> ES6 Brownian Snowflake

- _CodingChallenges/129-koch-snowflake.md
Here's [my version of the Koch Snowflake challenge.](https://stellartux.github.io/CC129/)
> Added contribution to 129-koch-snowflake.md

- _Tutorials/9-additional-topics/9.1-transformations-part-1.md
This solves the issue mentioned in #825.
@meiamsome Thanks for the quick fix.
> Contribution from PR#825

- _CodingChallenges/129-koch-snowflake.md
Polygonal Shape Koch Star with real-time configuration.
> Contribution to CC #129 - KochStar

- CodingChallenges/CC_119_Binary_to_Decimal_Conversion/Processing/CC_119_Binary_to_Decimal_Conversion/CC_119_Binary_to_Decimal_Conversion.pde
- CodingChallenges/CC_119_Binary_to_Decimal_Conversion/Processing/CC_119_Binary_to_Decimal_Conversion/bit.pde
This is the part 1 episode converted to Processing.
> Transcribe Binary_To_Decimal to Processing.

- CodingChallenges/CC_120_Bit_Shifting/Processing/CC_120_Bit_Shifting/Button.pde
- CodingChallenges/CC_120_Bit_Shifting/Processing/CC_120_Bit_Shifting/CC_120_Bit_Shifting.pde
- CodingChallenges/CC_120_Bit_Shifting/Processing/CC_120_Bit_Shifting/Label.pde
- CodingChallenges/CC_120_Bit_Shifting/Processing/CC_120_Bit_Shifting/bit.pde
Note that I created a class for Label and for Button, that are not in the original, since in p5.js DOM objects were used for these. I thought that even with the extra classes, this made the original much easier to transition from Javascript to Processing.
> Transcribe Bit_Shifting to Processing.

- CodingChallenges/CC_019_Superellipse/Processing/CC_019_Superellipse/CC_019_Superellipse.pde
- CodingChallenges/CC_019_Superellipse/Processing/CC_019_Superellipse/Slider.pde
This is the super ellipse episode transcribed to processing.
In the original episode, using p5.js, a DOM object was used for the slider. I created a simple slider for use in Processing so that the code in the main file would retain a resemblance to the p5.js version.
> Transcribing Superellipse to Processing.

- _CodingChallenges/127-snowflake-brownian.md
A JavaScript implementation of Challenge 127 with slight optimizations inspired by the Processing implementation by BoltMan
> Add "Brownian Crystal Snowflake" by PyBlend

- CodingChallenges/CC_046_Asteroids/Processing/CC_046_Asteroids/Asteroid.pde
- CodingChallenges/CC_046_Asteroids/Processing/CC_046_Asteroids/CC_046_Asteroids.pde
- CodingChallenges/CC_046_Asteroids/Processing/CC_046_Asteroids/Laser.pde
- CodingChallenges/CC_046_Asteroids/Processing/CC_046_Asteroids/Ship.pde
The game asteroids in processing.
> Transcribe Asteroids sample to Processing.

- CodingChallenges/CC_029_SmartRockets/Processing/CC_029_SmartRockets/CC_029_SmartRockets.pde
- CodingChallenges/CC_029_SmartRockets/Processing/CC_029_SmartRockets/Dna.pde
- CodingChallenges/CC_029_SmartRockets/Processing/CC_029_SmartRockets/Population.pde
- CodingChallenges/CC_029_SmartRockets/Processing/CC_029_SmartRockets/Rocket.pde
Ok, I took a few liberties with this one. If you would like, I can transcribe this closer to the actual video.
> Transcribe SmartRockets to Processing.

- CodingChallenges/CC_034_DLA/Processing/CC_034_DLA/CC_034_DLA.pde
- CodingChallenges/CC_034_DLA/Processing/CC_034_DLA/Walker.pde
This one was pretty simple and quick.
> Transcribe DLA to Processing

- _CodingChallenges/117-seven-segment.md
Opps i'm bit late.
You Must Watch This Watch :laughing:
> Contribution To CC #117 - Glowing LED Watch

- CodingChallenges/CC_054.1_StarPatterns/Processing/CC_054_StarPatterns/CC_054_StarPatterns.pde
- CodingChallenges/CC_054.1_StarPatterns/Processing/CC_054_StarPatterns/Edge.pde
- CodingChallenges/CC_054.1_StarPatterns/Processing/CC_054_StarPatterns/Hankin.pde
- CodingChallenges/CC_054.1_StarPatterns/Processing/CC_054_StarPatterns/Polygon.pde
- CodingChallenges/CC_054.1_StarPatterns/Processing/CC_054_StarPatterns/Slider.pde
Ok, I admit, I am a _**cheater cheater pumpkin eater**_. I re-used the Slider control I built for one of the previous challenges. The values given to the slider in the sample are reversed, but I did not update the Slider to handle the case where values are given in the reverse direction. (what is this world coming to?)
> Transcribe "Star Patterns" to Processing.

- _CodingChallenges/047-pixelsorting.md
My Quick Sorting algorithm for Pixel Sorting.
> My Quick Sorting algorithm for Pixel Sorting.

- CodingChallenges/CC_051_astar/Processing/CC_051_astar/CC_051_astar.pde
- CodingChallenges/CC_051_astar/Processing/CC_051_astar/Spot.pde
Several dynamic arrays here, so I used the ArrayList and its methods.
Can re-write for pure arrays on request.
> Transcribe A-star to Processing.

- assets/css/2-base/_navigation.sass
> Mobile nav animation fix

- _CodingChallenges/023-supershape2d.md
Add P5.gui which add more control to the supershape.
> Super Shape with more Controls

- _CodingChallenges/025-spheregeometry.md
> Spherical Geometry WEBGL

- _CodingChallenges/026-supershape3d.md
> 3D SuperShape with WEBGL

- _CodingChallenges/016-lsystem.md
Try out The [Demo](https://anuraghazra.github.io/LSystemCreator/)
With L-SystemCreator you can create your own L-Systems.
I also added some predefined L-Systems, you can find most of them on [Wikipedia Page](https://en.wikipedia.org/wiki/L-system)
But, i also found some interesting ones,
You should try these
* **Krishna Chakra** (made-up name)
* **Anklets Of Krishna**
* Snake Kolam
* Honeycomb
------
* Save your artwork in localStorage
* Load predefined Settings
* Create your own L-System (go nuts, considering performance)
> Contribution to CC #16 : L-SystemCreator

- CodingChallenges/CC_035.4_TSP_GA/P5/ga.js
> Removed one of the ";"

- CodingChallenges/CC_069_steering_evolution/Processing/CC_069_steering_evolution/CC_069_steering_evolution.pde
- CodingChallenges/CC_069_steering_evolution/Processing/CC_069_steering_evolution/Vehicle.pde
@shiffman I am pretty sure you would like to use plain arrays in this one, but the way the code is written makes this a bit more complicated in Java.
But, let me know if you want me to give it another go.
> Transcribe "steering evolution" to Processing.

- CodingChallenges/CC_065.2_binary_tree_viz/Processing/CC_065_2_binary_tree_viz/CC_065_2_binary_tree_viz.pde
- CodingChallenges/CC_065.2_binary_tree_viz/Processing/CC_065_2_binary_tree_viz/Node.pde
- CodingChallenges/CC_065.2_binary_tree_viz/Processing/CC_065_2_binary_tree_viz/Tree.pde
The tree representation overdraws itself in a lot of instances. It is a very complicated spacial problem as the space required potentially doubles with each row.
This version is a straight port of the original code.
I saw this interesting article on drawing binary trees: http://llimllib.github.io/pymag-trees/
Perhaps that is an episode? :)
There are many others online. Some of the more interesting ones show insertions with tree rotations of red-black/AVL trees, and stuff like that.
> Transcribe "binary tree viz" to Processing.

- CodingChallenges/CC_065.1_binary_tree/Processing/CC_065_1_binary_tree/CC_065_1_binary_tree.pde
- CodingChallenges/CC_065.1_binary_tree/Processing/CC_065_1_binary_tree/Node.pde
- CodingChallenges/CC_065.1_binary_tree/Processing/CC_065_1_binary_tree/Tree.pde
This has no graphical component.
Note: I set noLoop(), but is there some equivalent to noCanvas()?
> Transcribe "binary tree" to Processing.

- _CodingChallenges/130-fourier-transform-drawing.md
Project: https://wwl5q1434k.codesandbox.io/
Project Description:
Epicycles redraws a loop which was drawn by the user inside canvas (at least tries if you give a hard one).
The source code has to be refactored a lot and comments and ReadMe file has to be added.
There are three phases when you open the url.
1) where you draw a single loop and hit start. (loop will be closed after drawing)
2) circles trying to fit the shape by increasing number of circles. (you can adjust the number of circles by slider provided and hit start again)
3) where the Epicycles draws the loop
and reset button clears canvas and let you start from phase 1.
> Contribution added. Epicycles redrawing a user drawn loop.

- _CodingChallenges/130-fourier-transform-drawing.md
Adding example with unicorn train driver
> Rainbow Epicycles: Unicorn train driver

- _CodingChallenges/130-fourier-transform-drawing.md
Hi, sorry I forgot to add a link. Also, I think it is more accurate to say "orbits" in the title. Thanks. :)
> Change "epicyles" by orbits and added link

- _CodingChallenges/055-roses.md
this is the only way i know how to change a pull request.
> changed my previous pull request

- _CodingChallenges/105-polynomial-regression-tfjs.md
https://bohdandrahan.github.io/Polynomial-Regression-with-TensorFlow.js/
> Add community contributions to  CC_105_tf_polynomial_regression

- _CodingChallenges/131-bouncing-dvd-logo.md
I ran the tests locally and they pass not sure why @blinkityblank's pull request failed but will merge this one instead when the time comes to release.
> adding markdown file for 131 again dup #1064

- _CodingChallenges/131-bouncing-dvd-logo.md
https://editor.p5js.org/brunoruchiga/full/bmAOI_p9F
> Add contribution: Bouncing DVD Logo in 3D

- _CodingChallenges/131-bouncing-dvd-logo.md
> Community contribution [Bouncing 90s Screensaver]

- _CodingChallenges/131-bouncing-dvd-logo.md
I've used my [verlet.js](https://github.com/anuraghazra/verlet.js) physics engine to create Bouncing DVD Logo with verlet physics.
I love :heart: verlet physics.
demo : https://anuraghazra.github.io/CanvasFun/VerletDVDLogo
> Added Contribution to #131 - VerletDVDLogo

- _CodingChallenges/078-simple-particle-system.md
Wow, this looks amazing, I found that just by adding simple CSS filters to the canvas can make the particles look very blended and smooth. Awesome.......... :100: 
Play around with sliders in the GUI, and also added some cool textures, for example fire and emitters.
demo : https://anuraghazra.github.io/CanvasFun/particleSystem/
```css
canvas {
filter : blur(3px) contrast(10);
}
```
> Added Contribution to #78 - Realistic ParticleSystem

- _CodingChallenges/132-fluid-simulation.md
A contribution with a simple animation about flow around a circle. Thanks!
> Flow around circle

- _CodingChallenges/133-times-tables-cardioid.md
> Add my times tables

- _CodingChallenges/131-bouncing-dvd-logo.md
My program can understand when the dvd logo is going to hit the corner and reproduce a sound that can be timed to drop as soon as the logo hits the corner
> Innovative corner hit prediction

- _CodingChallenges/134-heart-curve.md
LoveHearts.
Happy V-day
demo: https://anuraghazra.github.io/CanvasFun/LoveHearts/
> Added Contribution To CC #134 | LoveHearts

- _CodingChallenges/133-times-tables-cardioid.md
Old (now broken): https://muskar.github.io/p5jsfun/
New: https://askebv.github.io/p5jsfun/
> Fixed contribution link on challenge 133

- _CodingChallenges/136-polar-perlin-noise-loops.md
Adding my contribution. Thanks
> Rainbow Perlin Noise loop in 3d

- _CodingChallenges/136-polar-perlin-noise-loops.md
I added Jacob's polar noise to a bezier curve project already underway.
> Bezier Curve Polar Noise contribution.

- _CodingChallenges/024-perlinnoiseflowfield.md
(Also I added web editor for steering text without a pull request by accident so this will run those tests.)
> web editor for flow field

- _CodingChallenges/124-flocking-boids.md
Hi :)
I worked on a full Java version of the FlockingSimulation. 
Thinking about it, making this a gradle probject was maybe a bit overhead, but it works relativly smoothly. Since Processing and P5 provide a nice Vector-Implementation but Java not, I alsohad to add a small Vector-Datatype, maybe someone will reuse this ^^ It got the relevant methods like sub/add/dist/setMag/normaliez etc.
Was definitly a bit more tricky redoing this in java :)
https://github.com/scorixear/FlockingSimulation
> Flocking in JavaFX

- _CodingChallenges/136.1-polar-perlin-noise-loops.md
i create a caracters noise loop, i guess
> my contribution to the codig challenge!!

- _CodingChallenges/124-flocking-boids.md
This is flocking demonstrated using a different model, called the Vicsek Model, used in scientific research regarding flocking and swarming behaviour.
Demo: https://codepen.io/tihawk/full/vPXebG
> add contribution flocking in 3D

- _CodingChallenges/022-juliaset.md
I know this is an old challenge, but I thought it will be nice to share. :)
This is a p5.js version of the Julia set showing its relationship with the Mandelbrot set.
Link: [https://jcponce.github.io/complex/mandelbrotjulia/](https://jcponce.github.io/complex/mandelbrotjulia/)
Thanks!!!
> Adding a contribution for Julia set

- _CodingChallenges/136.1-polar-perlin-noise-loops.md
https://editor.p5js.org/sventi555/full/NT68eSZPq
Move the slider to make it more wiggly!
> added "Wavy Field" by Stephen Edwards

- _CodingChallenges/011-perlinnoiseterrain.md
Interestingly this runs super slow with p5 `0.7.3` but speedy with `0.7.2` probably worth looking into sometime!
> web editor code

- _CodingChallenges/139-pi-collisions.md
Originally, Simon Tiger made a video about rhis, showing his version. However, his version didnt work for more than 2 digits, so i remade it from scratch in p5 using typescript
> Fast p5 pool pi ts implementation

- _CodingChallenges/139-pi-collisions.md
Here you go!
https://github.com/CodingTrain/Pi-Day-2019
> Adding my Processing Community Contribution

- _CodingChallenges/139-pi-collisions.md
Pi Day Collisions With Visualizing Optics (kind of).
demo : https://anuraghazra.github.io/CanvasFun/PiDayCollisions/
> Added Contribution to CC #139 (PiDayCollisions)

- _CodingChallenges/090-floyd-steinberg-dithering.md
[https://github.com/figraham/exploringdithering](https://github.com/figraham/exploringdithering)
> Adding My Community Contribution to CC90

- _CodingChallenges/136.1-polar-perlin-noise-loops.md
After viewing the tutorial of polar Perlin noise, I created a sketch which generates tree rings at random. Demo at the following link
https://shrirambo.github.io/p5Gallery/Resources/Tree%20Rings/blogpost.html
Added a grunge effect to make it a bit more realistic.
> Contribution: Random tree rings.

- _CodingChallenges/140-leibniz-formula-pi.md
https://saahil-khatkhate.github.io/Interactive-Leibniz-Pi-Visualization/
Link to my Project! ^^
> Adding my Community Contribution!

- _CodingChallenges/140-leibniz-formula-pi.md
I tried to visualize Leibniz Formula in a different way.
demo: https://anuraghazra.github.io/CanvasFun/LeibnizPIViz/
> Added Contribution To CC #140 (LeibnizPIViz)

- _CodingChallenges/049-obamamosaic.md
https://editor.p5js.org/jnsjknn/full/gKQv1Z_4E
> p5 version using random pictures

- _CodingChallenges/140-leibniz-formula-pi.md
I used an other way to display the leibniz formula using circles rather than a graph. ^^
Source: https://editor.p5js.org/EspritOrgue/sketches/T6TFIIjZ-
Demo: https://editor.p5js.org/EspritOrgue/present/T6TFIIjZ-
> Addind my contribution to the Leibniz Formula CC

- _CodingChallenges/016-lsystem.md
I made a stochastic L-system to draw generative trees with leaves here.
This can be seen here: https://ameya98.github.io/WebPPL/generative_art/
I am currently trying to perform inference with WebPPL over L-systems, as an experiment of my own.  This is currently only visible in the console. This doesn't affect the drawing of the tree, or any other graphics.
All feedback welcome!
> Added my L-system demo as a contribution. (CodingChallenge #16)

- _CodingChallenges/071-minesweeper.md
> Updated formatting for my Beesweeper

- CodingChallenges/CC_035.4_TSP_GA/P5/ga.js
- CodingChallenges/CC_035.4_TSP_GA/P5/sketch.js
- CodingChallenges/CC_069_steering_evolution/P5/sketch.js
- CodingChallenges/CC_069_steering_evolution/P5/vehicle.js
- _CodingChallenges/035.4-tsp.md
- _CodingChallenges/035.5-tsp.md
- _CodingChallenges/069.1-steering-evolution.md
- _CodingChallenges/069.2-steering-evolution.md
- _CodingChallenges/069.3-steering-evolution.md
- _CodingChallenges/069.4-steering-evolution.md
- _CodingChallenges/069.5-steering-evolution.md
Adding web editor for Coding Challenge 35 and 69
> Minor fixes for CC 35, 69 plus web editor

- _CodingChallenges/139-pi-collisions.md
Really enjoyed that video, keep it up!
> Adding contribution

- _CodingChallenges/143-quicksort.md
I will probably add releases or a webgl version soon.
> Add my CC 143 contribution

- _CodingChallenges/141-mandelbrot-pi.md
by this program, one can visualize the nth order of mandelbrot set or Multibrot set
https://github.com/sahiljindalthebest/MandelBrot-Set
PS:- Maybe i have entered a wrong link, but this is my first contribution, so pls forgive me :'(
> Adding my contribution in Mandelbort set

- _CodingChallenges/142.1-rubiks-cube.md
Hey, I added a contribution made in the unity game engine. Programmed in a more physical way of thinking about the cube.
> Added my contribution

- _CodingChallenges/116-lissajous.md
Including another version of the code challenge made by Guilherme Santos
> Update 116-lissajous.md with gui-santos version of the challenge

- _CodingChallenges/142.2-rubiks-cube.md
challenge 142 rubik's cube part 2
> adding code repo to markdown page

- _CodingChallenges/125-fourier-series.md
Hi, I made an extended Fourier Series Audiovisualisation. It features multiple waveforms, audio and playable notes using the keyboard.
See a live demo at: https://editor.p5js.org/mohragk/full/BkMiw4KxV
> Fouries Series Audiovisualisation Contribution

- _CodingChallenges/100.1-neuroevolution-flappy-bird.md
Uses Neuro Evolution in another game!!
link to the sketch:  https://www.openprocessing.org/sketch/701026
> Add my sketch

- Courses/natureofcode/11.3_neuroevolution_tfjs.js/bird.js
- Courses/natureofcode/11.3_neuroevolution_tfjs.js/ga.js
- Courses/natureofcode/11.3_neuroevolution_tfjs.js/index.html
- Courses/natureofcode/11.3_neuroevolution_tfjs.js/nn.js
- Courses/natureofcode/11.3_neuroevolution_tfjs.js/pipe.js
- Courses/natureofcode/11.3_neuroevolution_tfjs.js/sketch.js
Goes with https://youtu.be/cdUNkwXx-I4
> neuroevolution example code with tf.js

- _CodingChallenges/144-black-hole-visualization.md
demo: https://anuraghazra.github.io/FlockingBlackHole
Flocking Boids + Ship + Black Hole (3 in 1)
Click To Add More Black Holes.
Use Arrow Keys To Control Your Ship
> Added Contribution To CC 144: FlockingBlackHole

- _CodingChallenges/144-black-hole-visualization.md
Something fun I made in P5js. Drawing photon orbits around a spinning black hole. Also the interesting surfaces of the black hole are drawn. 
You can change the parameters of the orbit which are: the spin of the black hole and the radius of the orbit.
url: https://bongo0.github.io/Kerr-orbits/
source: https://github.com/bongo0/Kerr-orbits
> Update 144-black-hole-visualization.md; Photon orbits around a black hole

- CodingChallenges/CC_144_Black_Hole_Newtonian/P5/blackhole.js
- CodingChallenges/CC_144_Black_Hole_Newtonian/P5/photon.js
- CodingChallenges/CC_144_Black_Hole_Newtonian/P5/sketch.js
@gruselhaus do you think it makes sense to include this version too here on GitHub or the links from the code to the web editor is enough?
https://editor.p5js.org/codingtrain/sketches/4DvaeH0Ur
> minor edits to CC 144 code headers

- _CodingChallenges/144-black-hole-visualization.md
Running Version: https://editor.p5js.org/Eddershaw/full/dPJZX05Yq
Or GIF preview:
Much Appreciated,
Louis Eddershaw
> Update 144-black-hole-visualization.md with Contribution

- _CodingChallenges/089-langtonsant.md
I know, I'm late, and I'm not even sure I'm doing this the right way, but here goes nothing !
> Added my own contribution

- assets/css/1-tools/_vars.sass
- assets/css/2-base/_ctas.sass
- assets/css/2-base/_footer.sass
- assets/css/2-base/_landing-page.sass
- assets/css/2-base/_navigation.sass
Nav Before:
Nav After:
Button before and after:
Before:
After:
Before:
After:
> darken some colors to meet WCAG AA

- _CodingChallenges/136.1-polar-perlin-noise-loops.md
Perlin Noise GIF Loops https://editor.p5js.org/JohnyDL/sketches/wZv0CEz7c
> Adding Contribution to 136.2

- _CodingChallenges/143-quicksort.md
https://bohdandrahan.github.io/Sorting-Visual
> add contribution to coding  challenge 143

- _CodingChallenges/145-2d-ray-casting.md
I'm adding my example, where you can add and remove boundaries.
> Adding my community contribution

- _CodingChallenges/145-2d-ray-casting.md
A raycaster attempt with a changeable FOV, wall generation and improved algorithm to reduce fisheye.
https://editor.p5js.org/nicholassb753@gmail.com/present/kwblsMmLZ
> Ray Casting w/o rotation

- _CodingChallenges/145-2d-ray-casting.md
Adding Contribution to CC145 https://editor.p5js.org/JohnyDL/present/dCnLlChlO
> Adding Contribution to CC145

- _CodingChallenges/145-2d-ray-casting.md
Uses SVG, lets you add multiple line obstacles, ray sources, and have varying colors and angles to cast rays out of
Running Demo:
https://nem0-97.github.io/RayCasting/index.html
> Added new contribution

- CodingChallenges/CC_146_Rendering_Ray_Casting/P5/boundary.js
- CodingChallenges/CC_146_Rendering_Ray_Casting/P5/index.html
- CodingChallenges/CC_146_Rendering_Ray_Casting/P5/particle.js
- CodingChallenges/CC_146_Rendering_Ray_Casting/P5/ray.js
- CodingChallenges/CC_146_Rendering_Ray_Casting/P5/sketch.js
- _CodingChallenges/145-2d-ray-casting.md
- _CodingChallenges/146-rendering-ray-casting.md
Preparing Coding Challenge 146 for release.
> Coding Challenge 146 Rendering Ray Casting

- _CodingChallenges/146-rendering-ray-casting.md
This builds off the code at the end of the coding challenge to correct for geometrical distortions.
> [CC 146] Add contribution with geometrical distortions correction

- _CodingChallenges/145-2d-ray-casting.md
A 2D maze where you can only see thanks to ray casting.
Demo: https://editor.p5js.org/SebastienR/sketches/2rGNT5FNS
> Adding my contribution (Challenge #145)

- _CodingChallenges/010.3-maze-dfs-p5.md
- _jekyll/includes/3-modules/link-list.html
- _jekyll/layouts/video.html
- unit_testing/formats.js
Thank you @figraham for this suggestion.
Fixes #1340
> Adding a feature to add recommended community references

- _CodingChallenges/146-rendering-ray-casting.md
@gruselhaus, Thanks for adding this feature. Let me know if I used the format correctly.
Link to reference: [https://www.youtube.com/watch?v=xW8skO7MFYw](https://www.youtube.com/watch?v=xW8skO7MFYw)
> Trying out new Community References

- _jekyll/layouts/video.html
- assets/css/2-base/_navigation.sass
Also changed outline color for nav links again for better consistency across browsers.
Completed fix for issue #1229
> Added label for previous/next video button

- _CodingChallenges/145-2d-ray-casting.md
Hi!
I've made a 2nd example because it shows something in both the Nicky Kase explorable explanation and the RedBlobGames explorable explanation. Because, in one of their examples, they've only casted rays in the directions which just hit an end of a wall. This optimizes the code.
> Adding my community contribution (again)

- _CodingChallenges/146-rendering-ray-casting.md
example shows the view from the perspective of a being living in a 2D klein bottle universe (with height added to make it more palatable to us 3D beings). Inspired by "The Shape of Space" by Jeffrey Weeks. User can add "stakes" into the universe to help comprehend the geometry/topology.
> Added klein bottle contribution

- _CodingChallenges/142.1-rubiks-cube.md
Multi-sized cubes with no colors inside.
> Rubik's Cube CC

- 404.md
I found that no 404 page was defined in the project and this is an idea of how it can be. Thanks for every Coding Challenges
> Add 404 to the website

- _CodingChallenges/121.1-logo-interpreter.md
My [original Pull request](https://github.com/CodingTrain/Logo/pull/10) was respectfully declines. At the same time I would love to see my work among others.
You can [open the App](https://fabritsius.github.io/logo-code-editor) using [this URI](https://fabritsius.github.io/logo-code-editor). Examples are different almost every time, reload the page to see next.
> Add contribution by @fabritsius

- _CodingChallenges/100.1-neuroevolution-flappy-bird.md
Hello! this is ping pong game with neuroevolution
Here is the link:
https://github.com/sushantPatrikar/pingpongAI/blob/master/README.md
> Ping Pong with neuroevolution (Update 100.1-neuroevolution-flappy-bird.md)

- _CodingChallenges/124-flocking-boids.md
Boids written in python using pygame.
screenshot: https://imgur.com/a/GTUMf0e
> Add my python boids implementation

- _CodingChallenges/034-dla.md
https://bohdandrahan.github.io/Diffusion-Limited-Aggregation/
> add contribution to #34

- _CodingChallenges/147-chrome-dinosaur.md
Hi! I've improved the code by doing the following:
* Adding a checkbox for toggling the voice control on/off
* Improved "Train Spawning" technique:
Extra variables:
```javascript
const spacing = 80;
let timer = spacing;
let r = 1;
```
In `draw`:
```javascript
timer--;
if (timer <= 0) {
timer = 0;
r = random(1);
if (r < 0.015) {
trains.push(new Train());
timer = spacing;
}
}
```
> Adding my contribution to Chrome Dino Game

- _CodingChallenges/132-fluid-simulation.md
I tried my best to write this challenge in p5.js. 
Due to the nature of the challenge and the unreadable code of the source the best way to describe what I was doing is captured in [this picture](https://i.kym-cdn.com/photos/images/original/000/234/765/b7e.jpg). 
Unfortunately I could not locate the bug, and the fluid still does not behave properly. 
I spent waaay too much time trying to fix it, so I decided to share it as it is. 
The source: https://github.com/bohdandrahan/Fluid-simulation
> add contribution to challenge #132

- _CodingChallenges/076-10print.md
Link to demo here: https://editor.p5js.org/codingtrain/full/YBL4TaBkW
> 10Print contribution: circles instead of lines

- _CodingChallenges/076-10print.md
Link to demo:  https://editor.p5js.org/igor/full/kRaxw1_gu
> 10PRINT contribution: arcs instead of lines

- _CodingChallenges/074-clock.md
I added the github-pages link for my contribution to the Coding Challenge 74 (Clock) and updated the source url of my repository.
> Updated my contribution

- _CodingChallenges/005-space-invaders-p5.md
Alien Shooter
https://rinovethamoses97.github.io/Space-Invaders-Game/public/index.html
> contribution added

- _CodingChallenges/052-random-walk.md
Link to demo here: https://editor.p5js.org/mikakruschel/full/QchVIhVlH
> Random walk contribution: Visualizing Pi

- _CodingChallenges/125-fourier-series.md
A short program in functional style
> Added my implementation of coding challenge

- CodingChallenges/CC_148_Gift_Wrapping/P5/index.html
- CodingChallenges/CC_148_Gift_Wrapping/P5/sketch.js
- _CodingChallenges/148-gift-wrapping.md
Hoping to release this today after finalizing thumbnail and captions. This pull requests includes the markdown file and the p5.js code.
> Coding Challenge 148

- _CodingChallenges/065.1-binary-tree.md
I created my own version of the Binary Search Tree Coding Challenge, and I wanted to share it. I believe I followed all the directions to add the contribution, but let me know if there is anything else I need to do.
[Link to the visualization]( https://scolin16.github.io/Binary-Tree/)
> Add contribution.

- _CodingChallenges/125-fourier-series.md
I did this challenge in python using pygame.
> Add my python implementation

- _CodingChallenges/148-gift-wrapping.md
Simple implementation of CC 148 in processing. [https://gist.github.com/figraham/c6633e69cefb7b14328cadd4b47ec00a](https://gist.github.com/figraham/c6633e69cefb7b14328cadd4b47ec00a)
> Jarvis March Contribution - CC 148

- _CodingChallenges/148-gift-wrapping.md
Improved visuals: https://editor.p5js.org/undefined/present/-st9ZFxBS
Divide & Conquer: https://editor.p5js.org/undefined/present/nSWqjnOJU
> Added 2 contributions

- CodingChallenges/CC_149_Tic_Tac_Toe/P5/index.html
- CodingChallenges/CC_149_Tic_Tac_Toe/P5/sketch.js
- _CodingChallenges/149-tic-tac-toe.md
> Coding Challenge 149 - Tic Tac Toe

- _CodingChallenges/138-angry-birds.md
Hi,
Great tutorial and coding challenge! This version was made on the Koji platform.
Here is a link to the [running game](https://angrybird.withkoji.com/).
Love your videos!
Warmly,
Miles
> Add contribution

- _CodingChallenges/149-tic-tac-toe.md
url: https://sayan01.github.io/Tic-Tac-Toe/javascript/
source: https://github.com/sayan01/Tic-Tac-Toe
> TicTacToe Contribution: human vs human, (click)

- _CodingChallenges/145-2d-ray-casting.md
Link to Game https://milchreis.github.io/Flashy/
> Adding Flashy to contributions

- _CodingChallenges/149-tic-tac-toe.md
https://editor.p5js.org/TheTastefulToastie/sketches/EZWUlidf1
> Tic Tac Toe Animated

- _CodingChallenges/149-tic-tac-toe.md
We got the src and view URLs the wrong way around 🤫
> Swap src and view URLs

- _CodingChallenges/115-snake-game-redux.md
Link to game: https://milchreis.github.io/Snake3D/
> Adding Snake

- _CodingChallenges/085-the-game-of-life.md
link to the project here:  https://editor.p5js.org/greggelong/present/VGD6wwYTv
> The game of life with images and history

- _CodingChallenges/149-tic-tac-toe.md
Demo Here: https://editor.p5js.org/ilmnarayana/full/o-pkHOuVq
Source Here: https://editor.p5js.org/ilmnarayana/sketches/o-pkHOuVq
> Re-sizable Tic-Tac-Toe Human vs Human (click)

- _CodingChallenges/149-tic-tac-toe.md
https://giphy.com/gifs/ZBbpPDY0WLMIe8Bu2r/fullscreen
> added my version

- _CodingChallenges/071-minesweeper.md
link to demo: https://aloksbd.github.io/Game-Sprint/1-minesweeper/index.html
My first attempt to data oriented approach. Is it correct??
> Minesweeper Contribution: data oriented approach

- _CodingChallenges/149-tic-tac-toe.md
With the change I'm adding my version of the coding challenge
> Adding my version of the coding challenge

- _CodingChallenges/149-tic-tac-toe.md
Link Demo: https://editor.p5js.org/arthurrc/sketches/1ItYNEQGl
*Winner shows in Console.
> Tic-Tac-Toe Contribution: Colors instead of XO's

- _CodingChallenges/149-tic-tac-toe.md
Nothing special, practiced my use of map function for mousePressed. Lines drawn when winner found.  First Github pull request.
https://editor.p5js.org/James-Lang/full/swRhflZpi
> Coding Challenge #149 Contribution H vs C

- _CodingChallenges/149-tic-tac-toe.md
My take on the Tic Tac Toe coding challenge. My goal was to make it as simple as possible.
Link to the sketch: https://editor.p5js.org/daviddostal/sketches/F9mv0IRaJ
Fullscreen: https://editor.p5js.org/daviddostal/full/F9mv0IRaJ
> Tic-Tac-Toe Contribution: 2 players (simple)

- _CodingChallenges/093-double-pendulum.md
Preview url: https://gitlab.com/MisterBiggs/double_pendulum/blob/master/animation.webm
> Ported the double pendulum to Processing.py

- _CodingChallenges/076-10print.md
Rainbow 10Pring link:  https://codepen.io/XMODS/full/wOjwVG
> Rainbow 10Print

- _Tutorials/10-working-with-data/10.2-what-is-json-part-1.md
Demo link: https://github.com/GRFreire/load-saveJSONwithNODE
Load/Save JSON without p5 (using nodeJS) using a simple node library.
> what-is-json-part-1 contribution: using nodeJS

- _CodingChallenges/149-tic-tac-toe.md
Community contribution for the tic-tac-toe coding challenge
Link: https://www.openprocessing.org/sketch/740544
> tic-tac-toe player vs ai

- _CodingChallenges/071-minesweeper.md
https://editor.p5js.org/Zykatious/sketches/vaRBSL6d8
> Added a Hexagon-based version of Minesweeper

- _CodingChallenges/076-10print.md
NON-10PRINT Rainbow Characters Print link:  https://codepen.io/XMODS/full/eqBJwo
> Add community contribution 10Print variation

- _CodingChallenges/130.1-fourier-transform-drawing.md
Here is the project demo: https://onesandzer0s.github.io/Fourier/
You just put an SVG path in the input on the bottom, and you’re good to go
> Fourier Series Contribution: vanilla JS with SVg

- _CodingChallenges/116-lissajous.md
Refactored Coding Challenge#16, [Lissajous Curves](https://thecodingtrain.com/CodingChallenges/116-lissajous.html)
[Fullscreen](https://editor.p5js.org/HariKrishnan/full/uGdTrs9uB)
[Source](https://editor.p5js.org/HariKrishnan/sketches/uGdTrs9uB)
> Refactored the code, reduced to 41LOC.

- _CodingChallenges/149-tic-tac-toe.md
Here is the demo of my code: https://editor.p5js.org/atasoglu/full/ih2JEeRj5
> 149tictactoe contrubition: basic & without p5.dom

- _CodingChallenges/010.1-maze-dfs-p5.md
Link to demo here: https://editor.p5js.org/sylvainberube/full/doxwlc9US
> Maze Generator: hexagons instead of squares

- _CodingChallenges/009-solarsystemgenerator3d-texture.md
url: https://github.com/CatalaHD/SolarSystemProcessing
> My own contribution adding a skybox to the system

- _jekyll/layouts/video.html
https://github.com/CodingTrain/website/issues/830
> switch see it live to live demo

- _CodingChallenges/081.1-circle-morphing-part-1.md
View live demo: https://datramt.github.io/the-four-emotions/
View source: https://github.com/datramt/the-four-emotions
> all-the-feels contribution

- _CodingChallenges/093-double-pendulum.md
Link: https://github.com/dtj2011/Double-Pendulum
Live: https://codepen.io/dtj2011/pen/XvXaWW
Press start to begin animations
> Pure Javascript Implementation with better aesthetics and Slider

- _Courses/data-and-apis/0.2-Setup.md
- _Courses/data-and-apis/2.1-server-side-node.md
- _Tutorials/19-workflow/19.1-introduction.md
- _Tutorials/19-workflow/19.2-vscode.md
- _Tutorials/19-workflow/19.3-shell.md
- _Tutorials/19-workflow/19.4-git.md
- _Tutorials/19-workflow/19.5-node.md
- _Tutorials/19-workflow/19.6-python.md
- _Tutorials/19-workflow/index.md
> Adding Workflow Playlist to Website

- _CodingChallenges/141-mandelbrot-pi.md
Hi! I would like to add this contribution for the Mandelbrot set challenge. Here is the demo:
[https://jcponce.github.io/complex/mandelbrotexplorer/](https://jcponce.github.io/complex/mandelbrotexplorer/)
Thanks!!!
> My contribution for this challenge

- _CodingChallenges/012-lorenzattractor.md
Hello again, here is my contribution for this challenge. Demo here:
[https://jcponce.github.io/calculus/velfields/Lorenz/](https://jcponce.github.io/calculus/velfields/Lorenz/)
Thank you!!! :)
> Lorenz attracto contribution

- _CodingChallenges/030-phyllotaxis.md
Hi again dear community. This is my last contribution for today. Here is the demo:
[https://jcponce.github.io/sketches/sunflowerSphere/](https://jcponce.github.io/sketches/sunflowerSphere/)
Thank you! :) Have a great day!!!
> My last contribution for today

- _CodingChallenges/149-tic-tac-toe.md
Link: https://editor.p5js.org/IMPorbis/sketches/rH9vPGABt
> Adding my Version of the TicTacToe

- _CodingChallenges/147-chrome-dinosaur.md
Link to demo here: https://codepen.io/leimapapa/full/zVoJWz
const ww = window.innerWidth;
const hh = window.innerHeight;
//jump logic:
if (ww > hh) {
this.vy = -(height / 20);
} else {
this.vy = -35;
}
//obstacle speed logic:
if (ww > hh) {
this.x -= 16;
} else {
this.x -= 6;
}
> Chrome Dino: responsive jump height/obstacle speed

- _CodingChallenges/136.1-polar-perlin-noise-loops.md
Link to demo here: https://codepen.io/leimapapa/full/gEMGPr
> Suncircle styling

- _CodingChallenges/066-timer.md
Link to demo here: https://codepen.io/leimapapa/pen/qeaWoP
> Count Up and Down Timers

- _CodingChallenges/076-10print.md
Link to demo: https://editor.p5js.org/neerb/full/k4_2WOkRe
Link to source: https://github.com/neerb/10PRINT-Perlin-Noise-Terrain
> 10Print Contribution:  Perlin Noise Terrain Generation

- _CodingChallenges/044.1-afinn111sentimentanalysis.md
Links to demos: https://codepen.io/leimapapa/pen/JwWYKo  https://codepen.io/leimapapa/pen/KEgorL
> AFINN Sentiment Demos

- _CodingChallenges/030-phyllotaxis.md
Link to demo here: https://codepen.io/leimapapa/full/yZKyoq
This uses the phyllotaxis logic and only draws the prime numbers within the phyllotaxis spiral
> Prime Spiral Phyllotaxis

- _CodingChallenges/087-3Dknots.md
Hi here is my contribution for the 3d knots in p5.js. Demo: 
[https://www.dynamicmath.xyz/calculus/3d-curves/knots/](https://www.dynamicmath.xyz/calculus/3d-curves/knots/)
Thanks.
> Families of 3d knots in p5.js

- _CodingChallenges/021-mandelbrot-p5.md
Hi dear community, 
Here is my contribution for this challenge. Yesterday I accidentally added in the wrong challenge (https://thecodingtrain.com/CodingChallenges/141-mandelbrot-pi.html), but I guess it is ok, since they are related. Here is the demo:
[https://jcponce.github.io/complex/mandelbrotexplorer/](https://jcponce.github.io/complex/mandelbrotexplorer/)
Thanks! Have a great day!
> Adding my contribution Mandelbrot set explorer

- _CodingChallenges/067-pong.md
demo - https://aloksbd.github.io/Game-Sprint/2-pong/index.html
> Pong contribution - with ai

- _CodingChallenges/040.1-wordcounts-p5.md
Live demo found here: https://codepen.io/leimapapa/full/gNozyp
> p5.js Word Cloud Generator

- _CodingChallenges/029-smartrockets.md
Live demo found here: https://codepen.io/leimapapa/full/QJwjwE
> Smart Rockets in Logo

- _CodingChallenges/046.1-asteroids-part-1.md
A more complicated, but hopefully still understandable, version of the game.
game url: https://editor.p5js.org/dmfabritius/present/jdcQ8K0ho
game source: https://editor.p5js.org/dmfabritius/sketches/jdcQ8K0ho
> add Sprite Asteroids version

- _CodingChallenges/003-snake-game-p5.md
demo: https://aloksbd.github.io/Game-Sprint/3-snake/index.html
> snake contribution: teleporting wall

- assets/css/2-base/_navigation.sass
pull request according to 
https://github.com/CodingTrain/website/issues/1470
> Fixed toolbar (no it wasnt broken ^^)

- _CodingChallenges/148-gift-wrapping.md
Graham Scan Algorithm. Number of points and Frame Rate can be varied by sliders.
url: https://editor.p5js.org/ilmnarayana/full/w2cC9kqA_
source: https://editor.p5js.org/ilmnarayana/sketches/w2cC9kqA_
> Graham Scan Algorithm Implemented

- _CodingChallenges/149-tic-tac-toe.md
Basic Tik Tac Toe but in 3D
link:   https://editor.p5js.org/JeanLoup/sketches/3AOnKAWfF
> 3D Tic Tac Toe

- _CodingChallenges/076-10print.md
Including 10PRINT with a maze crawler function by Volfegan
> Added 10PRINT with a maze crawler function

- _CodingChallenges/098.1-quadtree.md
Implemented a Quadtree system to detect Voronoi points
source: https://github.com/volfegan/PixelGlitch (under PixelGlitch_Voronoi_filter_Krab)
> KrabCode Voronoi filter boosted by Quadtree system

- _CodingChallenges/136.1-polar-perlin-noise-loops.md
Link to demo: https://www.openprocessing.org/sketch/739862
> Add Contribution to Polar Perlin Noise Loops

- _CodingChallenges/005-space-invaders-p5.md
demo: https://aloksbd.github.io/Game-Sprint/4-spaceinvaders/index.html
> Space-Invaders Contribution - nothing special

- _CodingChallenges/044.1-afinn111sentimentanalysis.md
Uses afinn 111 sentiment analysis to mimick human facial expressions conversationaly using emoji's.  The beginning test of a more ambitious AI project of mine. Demo here: https://igotapochahontas.github.io/Liza/
> Working on an AI that's EMOJIonal

- _CodingChallenges/074-clock.md
Source Code: https://editor.p5js.org/abhijeetmankani/sketches/WKtYu4-Cd
Fullscreen: https://editor.p5js.org/abhijeetmankani/full/WKtYu4-Cd
A Simple Analog Clock With Hour And Minute Smoothing
> Simple Analog Clock With Hour And Minute Smoothing

- _CodingChallenges/149-tic-tac-toe.md
Link to demo here: https://gumkoman.github.io/3-in-a-row-extended-tic-tac-toe/
From tic tac toe i created 3 in a row a game where you can put x/o anywhere but at lowest level of selected column, I think that it may be great to see tic tac toe AI changed to play this game
> 149-TicTacToe contribution: 3 in a row from tic tac toe

- _CodingChallenges/035.1-tsp.md
A vizualization of 2-opt algorithm solving the travelling salesman problem.
> TSP with 2-opt

- _CodingChallenges/148-gift-wrapping.md
Animation of multiple convex hull generation algorithms.
https://omareq.github.io/convex-hull/
> Add community contribution

- _CodingChallenges/137-4d-opensimplex-noise-loop.md
I would like to share this sketch. A combination of simplex noise to create creatures and flocking. Demo:
[https://jcponce.github.io/sketches/flockknots/](https://jcponce.github.io/sketches/flockknots/)
Thanks.
> Flocking simplex-noise knot creatures

- _CodingChallenges/078-simple-particle-system.md
Link to demo: https://www.openprocessing.org/sketch/459864
> Simple Particle System Contribution: Color Smoke

- _CodingChallenges/138-angry-birds.md
Live demo here: https://codepen.io/leimapapa/full/GPKYpo
> OU vs. Texas College Football Version

- _CodingChallenges/059-steering-text-paths.md
Added my Creative Coding project. 
It is a combination of both this Coding Challenge and the Guest Tutorial on Matrix style Digital Rain made by Emily Xie ( https://youtu.be/S1TQCi9axzg )
> Added Fallingnumbers Flee From Mouse

- _CodingChallenges/149-tic-tac-toe.md
Link to Game: https://editor.p5js.org/The_Suspect/full/pIXzX8FAZ
> Just some shapes

- _CodingChallenges/059-steering-text-paths.md
Added my version of this Coding Challenge. I combined both this tutorial and the tutorial on the Guest tutorial "Matrix Digital Rain in p5" by Emily Xie.
> Added Falling Numbers Flee From Mouse

- _CodingChallenges/005-space-invaders-p5.md
source: https://editor.p5js.org/minoger/sketches/ul4KYn9JP
> my version of space invaders

- _CodingChallenges/145-2d-ray-casting.md
Link to demo here: https://matheuslrsouza.github.io/particle-filter-js/
> Raycasting contribution: Self driving robot

- _CodingChallenges/014-fractaltree.md
Sketch - https://editor.p5js.org/imtusharsharma/full/FcyznC4KW
Source - https://editor.p5js.org/imtusharsharma/sketches/FcyznC4KW
> Added contribution for fractal forest

- _CodingChallenges/035.1-tsp.md
It's a version of SA used for solving TSP using a 2-opt move (shifting pairs of edges) as a mutaion. Constants are somewhat random, so it probably can be done much better, but the results look decent.
> TSP with simulated annealing

- _CodingChallenges/149-tic-tac-toe.md
Link to repo here: https://gitlab.com/RohanJaisimha/M-E-N-A-C-E-/
> Tic Tac Toe with Machine Learning Contribution

- _CodingChallenges/074-clock.md
Url: https://editor.p5js.org/abhijeetmankani/sketches/K553n5FlB
Along with this, I've corrected 1 of my earlier typing mistake which occurred when I uploaded the 'Simple Analog Clock With Minute And Hour Smoothing' contribution.
> Rainbow Analog Clock With Minute And Hour Smoothing

- _CodingChallenges/148-gift-wrapping.md
Graham's scan algorithm. using a generator function in p5js
Source code https://editor.p5js.org/KeesKolber/sketches/bzvB_7qKf
> Graham's scan algorithm using a genrator function

- _CodingChallenges/052-random-walk.md
This time, the random walk has colours which depend on the direction the random walks goes to. This creates a satisfying pattern in the background once sped up a 1000 times (there is an option to do so).
Link to the demonstration is here: https://editor.p5js.org/hanxyn888@gmail.com/full/uSlG5StqX
> Random Walk Contribution: Colours

- _Tutorials/10-working-with-data/10.8-wordnik-api.md
Link to demo: https://editor.p5js.org/mikakruschel/full/SJD4mWnAX
> Wordnik API Contribution: Hangmen

- _CodingChallenges/136.1-polar-perlin-noise-loops.md
Hi, I would like to share this fun sketch. Demo: 
[https://editor.p5js.org/jcponce/full/cWHhxwgxl](https://editor.p5js.org/jcponce/full/cWHhxwgxl)
Thanks
> A noise loop with characters

- _CodingChallenges/042.1-markov-chains.md
`js-markov` was my first ever JavaScript library which I have made. I got inspired by this challenge so much that I have improved the code and even started teaching other 8th graders about Markov Chains!
> Added `js-markov`

- _CodingChallenges/074-clock.md
link to the running version : https://editor.p5js.org/martin@multiarts.ch/full/Hk3o7UQ07
note: I tried some others links in the contributor's list and some of them don't work.
> Modern Radio Clock contribution

- _CodingChallenges/149-tic-tac-toe.md
DEMO:
url: "https://editor.p5js.org/ilmnarayana/full/_-JTT51Qt"
source: "https://editor.p5js.org/ilmnarayana/sketches/_-JTT51Qt"
> Tic-Tac-Toe PvsAI Min-Max with alpha-beta pruning

- _CodingChallenges/149-tic-tac-toe.md
Not a new contribution. Changed the title of last contribution which is made by me. changed "Min-Max" to "Minimax"
> changed the title of last contribution.

- _CodingChallenges/148-gift-wrapping.md
This was improvised and I did not do any research so I can try to come up in my own way with a solution. You can sadly not see it step-by-step since I realized I could do it right at the end. Oops! My bad ;)
> Added my contribution to the list

- _CodingChallenges/030-phyllotaxis.md
Link to demo: https://jonas-skywalker.github.io/phyllotaxis-contribution/
> 030Phyllotaxis Generator Contribution

- _CodingChallenges/071-minesweeper.md
Link to demo: http://www.claesgill.com/trollsweeper
> Minesweeper contribution: Trolls instead of mines

- _CodingChallenges/035.1-tsp.md
GA for TSP with a 2-opt move as a mutation and no crossover. As a fitness function I used f(s) = av - len(s), where len is length of the path s, and av is a value more than most of the pathlengths and of the same order. After some constant tweaking I managed to make it work as good as 2-opt and faster than simulated annealing.
> TSP with Genetic algorithm

- _CodingChallenges/147-chrome-dinosaur.md
this was done in processing, so all the source code and files are in the github repo:
https://github.com/yarondms/Dino
> YaronDms Contribution: collision detection

- _CodingChallenges/085-the-game-of-life.md
[https://figraham.github.io/react-game-of-life/](https://figraham.github.io/react-game-of-life/)
> Community Contribution to CC85

- _CodingChallenges/056-attraction-repulsion.md
Hi,
I made a gravity simulation based on coding challenge 56
here's the link: https://github.com/matiasvlevi/Gravity-Simulation
> 56-attraction-repulsion (gravity simulation)

- _CodingChallenges/067-pong.md
Link to demo: https://carlsen66.github.io/CC_067_Pong%20AI/
> Pong with AI and Human against AI

- _CodingChallenges/100.1-neuroevolution-flappy-bird.md
Link to demo: https://carlsen66.github.io/neuroevolution-flappybird_color/
> Flappy Bird AI with Color and random pipe speed

- _CodingChallenges/004-purplerain.md
link to demo : https://carlsen66.github.io/CC_004_PurpleRain_JC.js/
> Purple Rain with wind

- _CodingChallenges/132-fluid-simulation.md
> Adding Community Contribution for CC132 on behalf of @SuperSimon81

- _CodingChallenges/067-pong.md
Link to the Demo of the Contribution : https://editor.p5js.org/aryan.chharia@gmail.com/full/lP_zBPh_l
> Pong contribution, redesign with tiles.

- _CodingChallenges/108-barnsley-fern.md
This Fern now presents with the colors of the rainbow
> barney's fern rainbow

- _CodingChallenges/001-starfield.md
https://github.com/MSivonen/Starfield
> Add rotating starfield

- _CodingChallenges/108-barnsley-fern.md
trying to correct the name from Barney to barnsley
> 108-barnsley-fern-rainbow

- _CodingChallenges/014-fractaltree.md
I have written Daniel's code in the java version of processing, than i also added an options window, where you can edit every property of the tree while running. Link: https://github.com/RipplB/Recursive-fractal-tree
Pictures:  https://drive.google.com/open?id=1gU3AKZp_Fc0qxWjhS18lQ9tYpXeVfI1H
> Dynamically customizable implementation in java

- _CodingChallenges/130.1-fourier-transform-drawing.md
new links.
url: "https://editor.p5js.org/ilmnarayana/full/u_sBUlk1Q"
source: "https://editor.p5js.org/ilmnarayana/sketches/u_sBUlk1Q"
> Updated links which are not working.

- _CodingChallenges/064.1-forward-kinematics.md
added new contribution with socket.io example of kinematic snake as an npm package and standalone js bundle to use in browser
> new contribution #64.1 with socket.io example of snake

- _CodingChallenges/001-starfield.md
Link to demo here: https://editor.p5js.org/AminCodingChallenge/full/aoIBBYSgY
> Starfield Contributions: Interactive Viewing Angle

- _CodingChallenges/001-starfield.md
I add the source link and make correct my contribution links: https://editor.p5js.org/AminCodingChallenge/sketches/aoIBBYSgY
> Starfield contribution: Interactive Viewing Angle

- _CodingChallenges/145-2d-ray-casting.md
explore procedurally generated caves with raycasting. framerate is bad for large maps.
https://editor.p5js.org/davidgraygs4@gmail.com/full/oUXmojdXi
https://editor.p5js.org/davidgraygs4@gmail.com/sketches/oUXmojdXi
> raycasting contribution

- _CodingChallenges/002-mengersponge.md
Link to demo here: https://editor.p5js.org/AminCodingChallenge/full/3S1QjYwAy
> Menger Sponge Fractal Contribution: Sponge Plus

- _CodingChallenges/003-snake-game-p5.md
link to demo here: https://editor.p5js.org/AminCodingChallenge/full/9QYlaqrgV
> The Snake Game contribution: Touch Snake Game

- _CodingChallenges/004-purplerain.md
link to demo here: https://editor.p5js.org/AminCodingChallenge/full/hxRaq59Xt
> Purple Rain contribution: Rainy Night

- _CodingChallenges/005-space-invaders-p5.md
Link to demo here: https://editor.p5js.org/AminCodingChallenge/full/U3xEo8Ifg
> Space Invaders contribution: Simple Spaceship Game

- _CodingChallenges/006-mitosis-p5.md
link to demo here: https://editor.p5js.org/AminCodingChallenge/full/nUyR3Xnpf
> Mitosis Simulation contribution: non-overlapping

- _CodingChallenges/051.1-astar.md
https://editor.p5js.org/davidgraygs4@gmail.com/sketches/uruzV8DkX
> updated links to most recent version

- _CodingChallenges/113-hypercube.md
https://editor.p5js.org/davidgraygs4@gmail.com/sketches/492uCszzp
> 4D projection contribution

- _CodingChallenges/112-3d-rendering.md
I have implemented a custom 3d render without any WebGL
> 3d-2d projection contribution

- _CodingChallenges/112-3d-rendering.md
https://editor.p5js.org/davidgraygs4@gmail.com/full/n3YFHyz0D
> updated link to most recent version

- _CodingChallenges/124-flocking-boids.md
Link to demo: https://editor.p5js.org/gmanen/present/HF0OH8ATr
> Adding contribution: Flocking with predators

- _CodingChallenges/031-flappybird.md
https://editor.p5js.org/sebastien.lorentz/present/ht-gL0Z4o
Flappy bird with the original graphics and soundtrack
> Flappy Bird

- _CodingChallenges/011-perlinnoiseterrain.md
https://editor.p5js.org/sebastien.lorentz/sketches/dVLMU3-mG
> 2d snowy landscape gen w/ perlin noise

- _CodingChallenges/094.1-2048.md
https://editor.p5js.org/davidgraygs4@gmail.com/sketches/zMhaJYxmc
> 2048 contribution with OOP

- _CodingChallenges/150-runway-rainbows.md
I just did what he does in a video but move the z vector around circles to generate fluid image sequences. I sped it up for the video because it looks nicer.
> StyleGAN Rainbow Animation

- _CodingChallenges/098.1-quadtree.md
Link: https://www.ernst-schmidt.com/coding/5d70ea631d0a070017666552
> Quadtree contribution: Combine quadtree and steering behaviours

- _CodingChallenges/148-gift-wrapping.md
https://github.com/GypsyDangerous/QuickHull-in-python
> quickhull in python contribution

- _CodingChallenges/100.1-neuroevolution-flappy-bird.md
Link: https://www.ernst-schmidt.com/coding/5d30690dc7a6e90017a94ef6
> Neuroevolution Contribution: Obstacle Course

- _CodingChallenges/149-tic-tac-toe.md
Images have been used to display the results and this was done using processing.
> Using images to display the result with processing

- _CodingChallenges/124-flocking-boids.md
Link: https://www.ernst-schmidt.com/coding/5d70ea631d0a070017666552
I added this contribution to the Quadtree challenge a couple of weeks ago. Not sure if I can contribute the same project twice, but I realized that it fits both challenges very well.
> Contribution: Quadtree and Flocking Simulation

- _CodingChallenges/027-fireworks.md
Nothing too special, just contributed the old one. :heart: 
demo: https://anuraghazra.github.io/CanvasFun/fireworks/
> Added Contribution To CC27 - Fireworks

- _CodingChallenges/124-flocking-boids.md
Creepy flocking parasites. Tails of the boids are actually verlet physics ropes. made with [Verly.js](https://anuraghazra.github.io/Verly.js)
Demo: https://anuraghazra.github.io/parasites/
> Added Contribution To CC124 Flocking Sim - Parasites

- _CodingChallenges/074-clock.md
Link to project: https://www.ernst-schmidt.com/coding/5d765ef90938150017951f9f
> Contribution: Onion Clock

- _CodingChallenges/130.1-fourier-transform-drawing.md
I programmed the complex epicycle drawing with Fourier Series in MATLAB.
> Drawing with Fourier epicycles in MATLAB!

- CodingChallenges/CC_151_Ukulele_Tuner/P5/index.html
- CodingChallenges/CC_151_Ukulele_Tuner/P5/sketch.js
- CodingChallenges/CC_151_Ukulele_Tuner/P5/style.css
- _CodingChallenges/151-ukulele-tuner.md
It's been forever, excited to release this!
> Coding Challenge: 151 Ukulele Tuner

- _CodingChallenges/074-clock.md
Link to Demo here: https://borisbreuer.de/clock
> clock contribution: no canvas, no libaries

- _CodingChallenges/093-double-pendulum.md
my variant of the double.
link:https://github.com/martif1202/processing/blob/master/tripple_pendulum.pde
> triple-pendulum.md

- _CodingChallenges/151-ukulele-tuner.md
Demo: https://editor.p5js.org/terrestrialstudio@gmail.com/full/-bovQ8Zxl
> ukulele tuner contribution

- _CodingChallenges/151-ukulele-tuner.md
This is my little experiment. I have added the p5.Amplitude() too.
> Ukulele Tuner contribution: Bass/Guitar Tuner with VU style

- _CodingChallenges/151-ukulele-tuner.md
I implemented three different designs of uke tuner, plus a random number generator!
I: https://editor.p5js.org/simontiger/full/VtgkGHrtp
II: https://editor.p5js.org/simontiger/full/LXV6dEoz9
III: https://editor.p5js.org/simontiger/full/0fb8c4uBI
Random # Generator: https://editor.p5js.org/simontiger/full/eOXdkP7tz
> New Community Contributions to the Ukalele Tuner!

- _CodingChallenges/030-phyllotaxis.md
I just added my contribution in MATLAB language, check it out!
> Phyllotaxis Simulator in MATLAB

- _CodingChallenges/151-ukulele-tuner.md
DEMO : https://editor.p5js.org/lokeshlkr@gmail.com/full/RcEcndWR2
SOURCE : https://editor.p5js.org/lokeshlkr@gmail.com/sketches/RcEcndWR2
> Adds new contribution from lokeshlkr@gmail.com

- _CodingChallenges/059-steering-text-paths.md
Demo: https://deshrike.github.io/FancyClock/
Source: https://github.com/DeShrike/FancyClock
> Steering Behaviors Contribution: Fancy Clock

- _CodingChallenges/121.1-logo-interpreter.md
Link to demo here: https://editor.p5js.org/mmendelsimon@gmail.com/sketches/DhPhxHkF0
> Add Logo Interpreter contribution

- _Streams/113-return-neural-networks.md
- _Streams/115-backpropagation.md
- _Streams/118-more-neural-networks.md
These references are being removed related to the recent discovery of plagiarism on Siraj's channel. This follows a pattern of little to no crediting of sources in code examples and videos.
For more background:
https://twitter.com/AndrewM_Webb/status/1183150368945049605
I don't feel I can confidently sent viewers in the direction of his content at this time. I would be happy to reconsider if and when it becomes appropriate to do so in the future. 
😞
> Removing references

- _CodingChallenges/122.2-quick-draw.md
Hi, I've been playing around with this CC to show collections of drawings, like postcards or scenes, positioned and scaled on the canvas accordingly.
Demo: https://codepen.io/decrecementofeliz/pen/oNNbOxv
Thanks!
> Add Contribution: quickdraw scenes

- _CodingChallenges/074-clock.md
Link to project: https://www.ernst-schmidt.com/coding/5c7838dd5896d80017d4452d
> contribution to clocks

- _CodingChallenges/108-barnsley-fern.md
Adjusted the stroke based on the y-axis to apply a rainbow gradient.
> Barnsley-Fern with a rainbow gradient

- _CodingChallenges/145-2d-ray-casting.md
Came across this broken link while looking at how coding challenges are structured.
> fixing broken link on CC145

- _CodingChallenges/143-quicksort.md
https://editor.p5js.org/D_Snyder/full/gEBQa5elpY
> added quicksort vis contribution

- _CodingChallenges/022-juliaset.md
same as #1798 for the mandelbrot/julia set videos
> add mentioned video link for CC22

- _CodingInTheCabana/001-maurer-rose.md
first: https://editor.p5js.org/D_Snyder/full/lE-Dexkr2
second: https://editor.p5js.org/D_Snyder/sketches/avDF4BxuU
> added 2 maurer rose contributions

- _CodingInTheCabana/001-maurer-rose.md
Link to demo here: https://codepen.io/leimapapa/pen/PooWmow?editors=0010
> Contribution: Maurer Rose linked to scroll

- _CodingChallenges/047-pixelsorting.md
Fixes #1807 
Thanks @GypsyDangerous for putting this in the p5 editor!
> Adding Web Editor Version CC47

- .github/pull_request_template.md
- _Guides/community-contribution-guide.md
Creating a pull request template to help with community contributions and the new effort to share contributions on social media.
If anyone has suggestions for ways to improve this template let me know.
> Adding Pull Request Template

- _CodingChallenges/081.1-circle-morphing-part-1.md
- _CodingChallenges/085-the-game-of-life.md
- _CodingChallenges/111-animated-sprite.md
- _CodingChallenges/120-bit-shifting.md
- _CodingChallenges/133-times-tables-cardioid.md
- _GuestTutorials/006-golan-levin-modulo-operator.md
- _GuestTutorials/007-golan-levin-circle-morphing.md
- _Streams/105-p5js-workflow-circle-morphing-arrow-function.md
- _Streams/108-more-oop-with-es6-and-the-game-of-life.md
- _Tutorials/16-javascript-es6/16.8-filter.md
- _config.yml
- unit_testing/yaml.test.js
Adding code links, changing naming of guest section, and can contribute default to true.
> Updating existing guest tutorials

- _GuestTutorials/004-emily-xie-matrix-digital-rain.md
Added the Backlog of the Guest Tutorials number 4 from issue #1813
> added md file related to Guest tutorial 4

- _CodingChallenges/094.1-2048.md
https://editor.p5js.org/mmendelsimon@gmail.com/sketches/WCcBsMqNC
> 2048 Contribution: 2048 with basic animation

- _CodingChallenges/152-rdp-algorithm.md
**Link to live project: https://editor.p5js.org/mikakruschel/sketches/ZmaEzFIvA**
> Contribution: RDP algorithm in 3D using p5.js

- _CodingChallenges/010.1-maze-dfs-p5.md
> Added Java Maze Generator

- _GuestTutorials/010-lisa-jamhoury-kinectron.md
Adding guest tutorial 10 to backlog of guest tutorials #1813
> added md file for guest tutorial 10

- _GuestTutorials/005-yining-shi-brick-breaker.md
Adding guest tutorial 5 to backlog of guest tutorials #1813
> Added .md file for guest tutorial 5

- _CodingChallenges/152-rdp-algorithm.md
https://editor.p5js.org/D_Snyder/sketches/sQ2qgRaAo
**Instagram:**
snyderling_
**Twitter:**
@jebfan101
> added rdp contribution, "performing rdp on path for fourier drawing"

- _CodingChallenges/147-chrome-dinosaur.md
Link to project: https://www.ernst-schmidt.com/coding/5d30690dc7a6e90017a94ef6
**Instagram:**
**Twitter:**
> Add project to chrome dinosaur coding challenge

- _CodingChallenges/152-rdp-algorithm.md
My contribution:
https://owenmcateer.github.io/Motus-Art/projects/week_74.html
https://owenmcateer.github.io/Motus-Art/projects/week_74.html
**Instagram:**
motus_art
**Twitter:**
omcateer
> My contribution

- _CodingChallenges/101-may-the-4th.md
- _GuestTutorials/002-sarah-drasner-web-animations-and-mojs.md
Added the Backlog of the Guest Tutorials number 2 from issue #1813
> Added .md file for guest tutorial 2

- _CodingInTheCabana/001-maurer-rose.md
https://editor.p5js.org/sequentialchaos/full/Zq70Kbrmk
**Instagram:**
**Twitter:**
@sequentialchaos
> Maurer Rose contribution: "maurer triangles rainbow swish"

- _CodingChallenges/099-color-predictor.md
- _GuestTutorials/009-jabril-color-predictor.md
Added the Backlog of the Guest Tutorials number 9 from issue #1813 and fixed PR #1831
> Added .md file for guest tutorial 9

- _CodingChallenges/136.1-polar-perlin-noise-loops.md
> ### "Ranunculaceae"
Named after the family of plants.
Click for a different, random design.
CodePen: https://codepen.io/Alca/full/xxxrdRL
Source: https://codepen.io/Alca/pen/xxxrdRL
**Instagram:** `AlcaMagic`
**Twitter:** `AlcaMagic`
> Add contrib to "Polar Perlin Noise Loops" - "Ranunculaceae"

- _GuestTutorials/001-tega-brain-particleio-board.md
As per Issue #1813 here is Guest Tutorial 1
> Add Guest Tutorial 1 - Tega Brain

- CodingInTheCabana/Cabana_002_Collatz_Conjecture/P5/index.html
- CodingInTheCabana/Cabana_002_Collatz_Conjecture/P5/sketch.js
- CodingInTheCabana/Cabana_002_Collatz_Conjecture/P5/style.css
- CodingInTheCabana/Cabana_002_Collatz_Conjecture/Processing/CollatzConjecture.pde
- _CodingInTheCabana/002-collatz-conjecture.md
Adding page and code for Collatz Conjecture.
> Collatz Conjecture - Coding in the Cabana Episode 2

- CodingInTheCabana/Cabana_001_Maurer_Rose/P5/index.html
- CodingInTheCabana/Cabana_001_Maurer_Rose/P5/sketch.js
- CodingInTheCabana/Cabana_001_Maurer_Rose/P5/style.css
- CodingInTheCabana/Cabana_001_Maurer_Rose/Processing/Cabana_001_Maurer_Rose.pde
- CodingInTheCabana/Cabana_002_Collatz_Conjecture/P5/index.html
- CodingInTheCabana/Cabana_002_Collatz_Conjecture/P5/sketch.js
- CodingInTheCabana/Cabana_002_Collatz_Conjecture/P5/style.css
- CodingInTheCabana/Cabana_002_Collatz_Conjecture/Processing/CollatzConjecture.pde
Adding some headings to the code. @violetcraze, feel free to take note of this as a "template" of sorts (though I'm open to other ways of doing this!) I also removed the `style.css` files since they mostly just clutter the repo?
> Comment headers and minor changes for Cabana code

- _CodingInTheCabana/002-collatz-conjecture.md
https://editor.p5js.org/ALVAROCA/sketches/2yoCVWCYI
**Instagram:**
**Twitter:**
> collatz-conjecture: it grows now

- _CodingInTheCabana/002-collatz-conjecture.md
https://editor.p5js.org/sequentialchaos/full/R3G_dBXzc
> Add contribution "collatz rainbow tree"

- _CodingChallenges/138-angry-birds.md
- _GuestTutorials/008-catt-small-phaser-game-development.md
Added the Backlog of the Guest Tutorials number 8 from issue #1813
> Added .md file for guest tutorial 8

- _CodingInTheCabana/001-maurer-rose.md
Noticed source and url were flipped on this contribution.
> Fixing switched links

- _CodingChallenges/099-color-predictor.md
link to project: https://www.ernst-schmidt.com/coding/5d00f8c51c1770001776aa52
**Instagram:**
**Twitter:**
> Contribution to Neural Network Color Predictor

- _CodingChallenges/076-10print.md
https://codepen.io/joseMitsu/pen/yzRvEB
**Instagram:**
https://www.instagram.com/josemitsurevilla/
**Twitter:**
https://twitter.com/jose_mitsu
> 10Print contribution, Random gradient

- _CodingInTheCabana/002-collatz-conjecture.md
Collatz tree where the growth is "steered" by even/odd numbers of collatz.
Link to demo: https://editor.p5js.org/diplofocus/full/oIG2Ir3vD
https://editor.p5js.org/diplofocus/full/oIG2Ir3vD
**Instagram:**
pop_culturally_impaired
> Collatz conjecture contribution

- _CodingInTheCabana/002-collatz-conjecture.md
Really cool colors and growing animation :)
https://codepen.io/LuisMDLeon/full/jOOLzGB
> Animation in p5.js

- _CodingInTheCabana/002-collatz-conjecture.md
https://jcponce.github.io/sketches/collatz
**Instagram:**
**Twitter:**
@PonceCampuzano
> My Contribution Collatz Sea Tree

- _CodingInTheCabana/002-collatz-conjecture.md
Link to Demo: https://github.com/manishKr135/CollatzWeed
**Instagram:**
**Twitter:**
> Collatz Conjecture Sea Weed

- _CodingInTheCabana/002-collatz-conjecture.md
I came up with interesting visualizations while experimenting with Collatz Conjecture, here are some screenshots
Here's more screenshots https://twitter.com/anuraghazru/status/1189487979812704256
**Link to live project, video, or image:** https://anuraghazra.github.io/CanvasFun/collatzSunrise
**Instagram:** https://www.instagram.com/anuraghazra/
**Twitter:** https://twitter.com/anuraghazru
> Added Contribution: CC 2 Collatz Conjecture | CollatzSunrise

- CodingChallenges/CC_153_Interactive_SketchRRN/P5/index.html
- CodingChallenges/CC_153_Interactive_SketchRRN/P5/rdp.js
- CodingChallenges/CC_153_Interactive_SketchRRN/P5/sketch.js
- _CodingChallenges/153-interactive-sketchrnn.md
Adding page for coding challenge 153.
@shiffman Can you double check the code and header formatting to make sure it looks good?
> Coding Challenge 153 - Interactive Drawing with SketchRNN

- _CodingInTheCabana/002-collatz-conjecture.md
I'm not completely sure about "The code in the repository should match the code written in the YouTube tutorials". There are only a few lines left of the original.
https://editor.p5js.org/SuperRembo/present/FlVS_V65b
**Twitter:**
@SuperRembo
> Collatz Tree contribution: branch with based on usage

- Gemfile.lock
- _jekyll/includes/3-modules/back-to-top-button.html
- _jekyll/layouts/base.html
- assets/css/4-modules/_back-to-top-button.sass
- assets/css/main.sass
- assets/javascript/functions.js
Couldn't sleep, so here you go. I hope this approach is acceptable.
Haven't worked with this repo in a long time, it was kind of fun to navigate thru all the files 😸 
Closes #1855
> add back to top button

- .github/workflows/nodejs.yml
- .github/workflows/ruby.yml
> Hello GitHub Actions

- _GuestTutorials/003-val-head-spring-animations.md
- _Streams/119-solving-merge-conflicts-xor-problem.md
Added 003-val-head-spring-animations.md to GuestTutorials for #3, as requested in #1813.
> Add 003-val-head-spring-animations.md

- _CodingChallenges/145-2d-ray-casting.md
Raycasting contribution: Rendering with textures
https://www.youtube.com/watch?v=igKRMz--BuM
> Raycasting contribution: Rendering with textures

- .github/workflows/nodejs.yml
- .github/workflows/ruby.yml
> Adding caching

- _jekyll/includes/4-vector-graphics/squarebrackets.svg
this should fixes #1896 
if it doesn't i'll revert it.
> fixing issue with new logo

- _jekyll/includes/4-vector-graphics/squarebrackets.svg
Reverts CodingTrain/website#1898
> Revert "minor change to new logo"

- _TeachableMachine/2-teachable-game.md
**Link to live project:** https://editor.p5js.org/mikakruschel/sketches/fQHlDecY9
> Added contribution to teachable machine game

- _CodingInTheCabana/001-maurer-rose.md
Link to demo here: https://stampyzfanz.github.io/games/MaurerRose/
**Instagram:**
**Twitter:**
> Maurer rose contribution: make rose rainbow color

- _CodingChallenges/068.1-bfs-kevin-bacon.md
Link to source code: https://github.com/jwood74/BFS_kevin_bacon
(sadly no visualisation - maybe one day)
**Instagram:**
**Twitter:**
> BFS contribution: Kevin Bacon in ruby

- README.md
Line 15: "If you want to share your own variation based on a Coding Train video, you can do this by visiting the page ..."
- Because of the nature of an if statement, the "you can do this" is implicit, so I altered the sentence to make it shorter and easier to read
-"If you want to share your own variation based on a Coding Train video, visit the page ..."
Line 11: "please subscribe to get a notification"
- Ambiguous what "a notification" refers to
- Changed to "notifications for events" just to make this a bit more clear!
- "get" changed to "receive", since "receive" is more appropriate in this context
**Instagram:**
**Twitter:**
> Some changes for sentence concision in README.md :)

- _Tutorials/index.md
Based on discussion from #1906
> Changing Links to Increase Accessibility

- _CodingChallenges/127-snowflake-brownian.md
**Live demo:** https://codepen.io/rajatkantinandi/full/QWWVrmB
**Source:** https://codepen.io/rajatkantinandi/pen/QWWVrmB
**Twitter:**
https://twitter.com/rajatkantinandi
> Add Brownian Tree Snowflake falling animation w/p5

- landing-page.html
Reverts CodingTrain/website#1917
> Revert "update demo"

- _CodingChallenges/059-steering-text-paths.md
View demo here :- https://editor.p5js.org/Arnav-Sirigere/full/4kjlzekku
**Instagram:**
**Twitter:**
> The text morphs and changes and creates new text.

- _TeachableMachine/2-teachable-game.md
Link to main project: https://editor.p5js.org/simontiger/present/McNY2_ay_
Version w/o ml5: https://editor.p5js.org/simontiger/present/qH_ZSvup5
> Add community contribution(s) to Teachable Game video

- _CodingChallenges/055-roses.md
https://editor.p5js.org/D_Snyder/full/V4QZDfwl-
**Instagram:** snyderling_
**Twitter:** jebfan101
> Polar Rose Fireworks

- Courses/beginner_ml5/6.1_train_your_own/index.html
- Courses/beginner_ml5/6.1_train_your_own/sketch.js
- _Courses/ml5-beginners-guide/6.1-ml5-train-your-own.md
Followed the library references like in #1935 so they would not have to be updated later.
> Adding ml5.js: Train Your Own Neural Network

- .eslintrc.js
Path got change in one of the linting exceptions. Fixed it.
> Fixing Path in Lint

- _Courses/ml5-beginners-guide/6.1-ml5-train-your-own.md
Link to demo: https://drive.google.com/open?id=18RyT2x_GEEAuHiSxYJkoSMGoK5j1pmdg
**Instagram:**
**Twitter:**
> Self learning neural network

- _Courses/ml5-beginners-guide/6.1-ml5-train-your-own.md
https://youtu.be/8HEgeAbYphA
**Instagram:**
**Twitter:**
> Adding my version of ml5 network

- _CodingChallenges/064.1-forward-kinematics.md
Added entry: "Koi Pond"
Click to feed the fish!
demo: https://editor.p5js.org/brytlao/present/um2WVvzaN
**Instagram:**
**Twitter:**
> Contribution for Coding Challenge 64

- _Courses/ml5-beginners-guide/6.1-ml5-train-your-own.md
https://editor.p5js.org/raisinten/full/Ho2LJo4Iw
* regression instead of classification
* interaction by dragging the mouse as well
The number of basic notes in music, i.e, C, D, E, F, G, A and B is 7. What else goes with 7 and is colorful too? A rainbow of course! It has 7 colors!
* notes mapped with the colors of a rainbow
* note color prediction 
**YouTube:**
https://www.youtube.com/channel/UCuq2FJyz5oonWDvfEXNNLBw
> ml5-train-your-own contribution: regression added

- landing-page.html
> Removing streams from latest videos on the landing page

- _TeachableMachine/2-teachable-game.md
This is evolutionary AI snake game, based on idea of snake game + AI from this video and your flappy-bird neural network. 
demo: https://editor.p5js.org/deplodog@gmail.com/present/HrbT-gueC
demo how i trained it: https://editor.p5js.org/deplodog@gmail.com/present/JiFD0311f
source: https://editor.p5js.org/deplodog@gmail.com/sketches/JiFD0311f
**Twitter:** https://twitter.com/deplodog
> Snake Game Evolutionary AI

- _Courses/ml5-beginners-guide/6.1-ml5-train-your-own.md
Link to demo here: https://colorfinder-meinsware.netlify.com/
**Instagram:**
**Twitter:**
> train your own NN: learn different colors

- _GuestTutorials/012-shirley-wu-introduction-to-d3js.md
I added the guest page for Shirley Wu and added my community contribution. 
[Observable Notebook](https://observablehq.com/@mikakruschel/film-flowers-variation)
> Add guest page for Shirley Wu

- Courses/beginner_ml5/6.2_save_data/P5/index.html
- Courses/beginner_ml5/6.2_save_data/P5/sketch.js
- _Courses/ml5-beginners-guide/6.2-ml5-save-data.md
Page for the saveData() video.
> Page for ml5.js: Save Neural Network Training Data

- Courses/beginner_ml5/6.3_save_model/P5/index.html
- Courses/beginner_ml5/6.3_save_model/P5/sketch.js
- _Courses/ml5-beginners-guide/6.2-ml5-save-data.md
- _Courses/ml5-beginners-guide/6.3-ml5-save-model.md
Page for saving and loading ml5 nn model.
> Page for Save and Load Model Video

- _CodingChallenges/085-the-game-of-life.md
Link to demo here
https://www.openprocessing.org/sketch/805872
**Instagram:**
**Twitter:**
> change it editable and more slowly.

- Courses/beginner_ml5/6.2_save_data/P5/sketch.js
- Courses/beginner_ml5/6.3_save_model/P5/sketch.js
- Courses/beginner_ml5/6.4_regression/P5/sketch.js
- _Courses/ml5-beginners-guide/6.2-ml5-save-data.md
- _Courses/ml5-beginners-guide/6.3-ml5-save-model.md
- _Courses/ml5-beginners-guide/6.4-ml5-regression.md
> fixing descriptions and headers for latest ml5 videos

- _Courses/ml5-beginners-guide/6.4-ml5-regression.md
New description for ml5 regression video
> updating ml5 regression description

- _jekyll/includes/3-modules/video-list.html
- _jekyll/layouts/series-index.html
> Fixing #1973

- CodingChallenges/CC_154_Tic_Tac_Toe_Minimax/P5/index.html
- CodingChallenges/CC_154_Tic_Tac_Toe_Minimax/P5/minimax.js
- CodingChallenges/CC_154_Tic_Tac_Toe_Minimax/P5/sketch.js
- _CodingChallenges/149-tic-tac-toe.md
- _CodingChallenges/154-tic-tac-toe-minimax.md
@shiffman Check to make sure the description looks good.
> Adding Page for Tic Tac Toe Minimax

- _CodingChallenges/154-tic-tac-toe-minimax.md
Direct link to Chess AI: https://Chess-AI--simontiger.repl.co
Direct link to Chess AI with customizable search depth: https://Chess-AI-User-friendly--simontiger.repl.co
> Add first two community contributions to the Minimax challenge!

- CodingChallenges/CC_154_Tic_Tac_Toe_Minimax/C/Main.c
> C Implementation

- _CodingChallenges/154-tic-tac-toe-minimax.md
> fixed link on contribution

- _CodingChallenges/154-tic-tac-toe-minimax.md
> Community Contribution added

- _CodingChallenges/152-rdp-algorithm.md
This code, https://github.com/Ignotus-mago/DrawReduceMakeCurves, reduces the number of points in a line you draw on screen and then creates curves from the reduced points. You can switch between a Bezier spline and a weighted Bezier curve.
https://youtu.be/U4aC8tJkbtA
**Instagram: ignotus_mago**
**Twitter: ignotus_mago**
> Draw, Reduce, Make Curves

- _CodingChallenges/152-rdp-algorithm.md
Edit: added source tag to previous accepted contribution
**Instagram: ignotus_mago**
**Twitter: ignotus_mago**
> Added source tag to previous contribution: https://github.com/Ignotus-mago/DrawReduceMakeCurves

- _CodingChallenges/124-flocking-boids.md
View demo here:- https://editor.p5js.org/Arnav-Sirigere/full/FMBzzf5Vd
Change color according to neighbors in flock and Design improvements.
The boids have a frontal cone view which means they can only see ahead in a cone view.
https://editor.p5js.org/Arnav-Sirigere/full/FMBzzf5Vd
**Instagram:**
**Twitter:**
> Frontal cone view + Obstacle

- _CodingChallenges/053-random-walk-levy.md
Multiple walkers which reproduce on meeting and have a score based on how many pixels they have covered on the screen.
Slider to change speed of walkers.
https://editor.p5js.org/Arnav-Sirigere/full/0iRp-6BRt
**Instagram:**
**Twitter:**
> Reproduction and Ball Paint Mechanics + Speed

- _CodingChallenges/154-tic-tac-toe-minimax.md
link: https://editor.p5js.org/yuvalbi/full/HuinyONTR
**Instagram:**
**Twitter:**
> 154-tic-tac-toe: minimax that thinks about depth

- _CodingChallenges/154-tic-tac-toe-minimax.md
https://editor.p5js.org/D_Snyder/full/A7Y89mBLB
**Link to live project, video, or image:** https://editor.p5js.org/D_Snyder/full/A7Y89mBLB
**Instagram:**
**Twitter:**
> added tic tac toe contribution

- _CodingChallenges/027-fireworks.md
Fireworks now produce letters!
https://editor.p5js.org/Arnav-Sirigere/full/gHb_ytBvB
**Instagram:**
**Twitter:**
> Text Fireworks

- _CodingChallenges/155-kaleidoscope-snowflake.md
Adding a markdown file for planned release of coding challenge video tomorrow. To do:
> Challenge 155: Kaleidoscope Snowflake

- CodingChallenges/CC_155_Kaleidoscope_Snowflake/P5/index.html
- CodingChallenges/CC_155_Kaleidoscope_Snowflake/P5/sketch.js
- CodingChallenges/CC_155_Kaleidoscope_Snowflake/Processing/CC_155_Kaleidoscope_Snowflake/CC_155_Kaleidoscope_Snowflake.pde
- _CodingChallenges/155-kaleidoscope-snowflake.md
#2012 
Code for the Kaleidoscope Snowflake challenge. Ported to processing as well.
> Code for CC155

- Tutorials/Processing/9.3-array-of-objects/Processing/sketch_9_3_Array_of_Objects/Bubble.pde
- Tutorials/Processing/9.3-array-of-objects/Processing/sketch_9_3_Array_of_Objects/sketch_9_3_Array_of_Objects.pde
- Tutorials/Processing/9.4-arrays-and-loops/Processing/sketch_9_4_Arrays_and_Loops/Bubble.pde
- Tutorials/Processing/9.4-arrays-and-loops/Processing/sketch_9_4_Arrays_and_Loops/sketch_9_4_Arrays_and_Loops.pde
- Tutorials/Processing/9.5-flexible-arrays/Processing/sketch_9_5_Flexible_Arrays/Bubble.pde
- Tutorials/Processing/9.5-flexible-arrays/Processing/sketch_9_5_Flexible_Arrays/sketch_9_5_Flexible_Arrays.pde
- _Courses/learning-processing/9-arrays/9.1-what-is-an-array.md
- _Courses/learning-processing/9-arrays/9.2-array-syntax.md
- _Courses/learning-processing/9-arrays/9.3-array-of-objects.md
- _Courses/learning-processing/9-arrays/9.4-arrays-and-loops.md
- _Courses/learning-processing/9-arrays/9.5-flexible-arrays.md
- _Courses/learning-processing/9-arrays/index.md
> Adding Pages for Playlist 9 (Arrays) of Learning Processing

- _CodingChallenges/155-kaleidoscope-snowflake.md
[Snow flake Make & Share](https://code.sololearn.com/WmtTj0e3g8mt/#js)
[My Sololearn Profile](https://www.sololearn.com/Profile/10779261)
**Instagram:**
**Twitter:**
> Adding My Contribution [ Snow Flake Make & Share ]

- _CodingChallenges/155-kaleidoscope-snowflake.md
Live URL: https://editor.p5js.org/ravid7000/present/74w9Fcx4D
**Instagram:** https://www.instagram.com/theravidhiman/
**Twitter:** https://twitter.com/thecodeboy_ravi
> Added contribution to Kaleidoscope Snowflake

- CodingChallenges/CC_155_Kaleidoscope_Snowflake/P5/sketch.js
Angle declared at line 8 and redeclared at 47.
Removed angle declaration at line 47.
**Instagram:**
**Twitter:**
> Angle Redeclaration

- _CodingChallenges/003-snake-game-p5.md
implemented most of the features of the well known snake game
**Instagram:**
**Twitter:**
> added "SSS-nake" contribution

- _CodingChallenges/014-fractaltree.md
Strokeweight changed as of a sine wave to create a blooming effect and improved colors.
https://editor.p5js.org/Arnav-Sirigere/full/ZCuoBe9DT
> "Blooming" Effect and Rainbow Colors

- _CodingChallenges/155-kaleidoscope-snowflake.md
https://editor.p5js.org/Clipi/sketches/HEWqeH_XD
**Twitter:** twitter.com/_Clipi_
> Snowflake generator with more features

- assets/css/2-base/_navigation.sass
> Mobile navbar fix test (will revert if breaks)

- _CodingChallenges/152-rdp-algorithm.md
Here's a link to repl.it (just click run!): https://repl.it/@elunico/RDP-Algorithm
https://repl.it/@elunico/RDP-Algorithm
**Instagram:**
**Twitter:**
> RDP Line Simplification in Python with Matplotlib

- _CodingChallenges/004-purplerain.md
Rain that responds to wind (With mouse click)
Made using Processing.
Link to source code:
https://github.com/AryamanKejriwal/RainWithWindAndSplash
**Instagram:** aryaman_kejriwal
**Twitter:**
> Added A Rainy, Splashy, Windy Night

- _CodingChallenges/046.1-asteroids-part-1.md
Asteroids Plus was made in Processing 3.
Asteroids have collision detection and gravitationally attract each other.
https://github.com/AryamanKejriwal/AsteroidsPlus
**Instagram:** aryaman_kejriwal
**Twitter:**
> Asteroids Plus

- _CodingChallenges/063.1-unikitty-flag.md
Simulation for the surface of water or taught cloth with ripples going through. Made in Processing.
https://github.com/AryamanKejriwal/SurfaceOfWater-TaughtClothSimulation
**Instagram:** aryaman_kejriwal
**Twitter:**
> Added Surface of Water / Taught Cloth Simulation

- _CodingChallenges/155-kaleidoscope-snowflake.md
https://editor.p5js.org/D_Snyder/full/3lvx56LMc
**Instagram:** snyderling_
**Twitter:** @jebfan101
> add snowflake creator

- _CodingChallenges/001-starfield.md
Link to veiw Demo : https://asteroidfield.glitch.me
**Instagram:**
**Twitter:**
> Asteroid Field with more 3D depth

- CodingChallenges/CC_155_Kaleidoscope_Snowflake/Processing/CC_155_Kaleidoscope_Snowflake/CC_155_Kaleidoscope_Snowflake.pde
> Changed pop()-> popMatrix() and push->pushMatrix()

- _CodingChallenges/076-10print.md
Code and Run: https://repl.it/@Ari24/10Print
It's the 10PRINT in Python Pygame
> 10PRINT in Python Pygame

- _jekyll/includes/2-base/navigation.html
- assets/css/2-base/_navigation.sass
- assets/javascript/functions.js
- Updated styling for all the buttons on Nav bar to match with previous links
- Fixed issue where the sub menu is not visible in Safari
Desktop: 
Mobile:
> Fix for safari issue
