- challenges/CC_61_fractal_spirograph/README.md
I'm not completely happy with https://github.com/Zalastax/p5js-projects/blob/master/CC_61_fractal_spirograph_rainbow/sketch.js#L51-L52 though, because of how bad the performance gets. Any way of creating performant gradient line shapes in p5.js?
> Add rainbow fractal in p5.js

- challenges/CC_64_1_a_ForwardKinematics/Segment.pde
Since the selfAngle variable is not initialised for the segment with no parent, the animations always begin from angle = 0. If we look at the animation around 1:25:40 in the live stream video, the segments begin to rotate from angle = 0, even though the first segment is defined to start from angle = -45.
> Bug: selfAngle not initialised for first segment.

- CodingChallenges/CC_60_Butterfly_Wings/sketch.js
(Sorry, my previous pull request somehow included my own customisations, in addition to the fix. I hope it's fine now)
The condition on line 31 was producing 3 equal wings and one different, instead of two and two. Once that's changed, the rotation is not necessary, it produced simetry on the horizontal axis instead of the vertical one.
> Fix simetry (updated)

- _jekyll/includes/2-base/header.html
- assets/css/2-base/_header.sass
Closes issue #370
This should now be fixed. I somehow forgot to set `overflow: hidden` for the `nav` container.
Therefore, the links were "peaking out" since their `height` property was set to `auto` (used for animating the menu in).
Big thanks to @Maik1999 for pointing me in the right direction!
> 🐛  Menu links don't hide on mobile

- _jekyll/includes/2-base/head.html
This script will only be visible when the site was built in production mode to not influence the tracking results when testing locally.
Closes #399
> Added google analytics gtag.js script to the header

- .circleci/config.yml
- _Courses/programming-with-text/10-chatbots/10.2-rivescript.md
- _Courses/programming-with-text/11-chrome-extensions/11.1-introduction.md
- _Courses/programming-with-text/11-chrome-extensions/11.5-pop-ups.md
- _Courses/programming-with-text/2-regular-expressions/2.1-introduction.md
- _Courses/programming-with-text/2-regular-expressions/2.10-homework-assignments.md
- _Courses/programming-with-text/2-regular-expressions/2.2-meta-characters.md
- _Courses/programming-with-text/2-regular-expressions/2.3-character-classes.md
- _Courses/programming-with-text/2-regular-expressions/2.4-capturing-groups.md
- _Courses/programming-with-text/2-regular-expressions/2.5-back-references.md
- _GuestTutorials/6-golan-levin-modulo-operator.md
- _GuestTutorials/7-golan-levin-circle-morphing.md
- _Streams/106.1-chrome-extensions-part-1.md
- _Streams/106.2-chrome-extensions-part-2.md
- _Streams/108-nn-continued.md
- _Streams/110-webgl-with-p5js-continued.md
- _Streams/124-upcoming.md
- unit_testing/coding-challange-yaml.test.js
- unit_testing/formats.js
- unit_testing/package-lock.json
- unit_testing/package.json
- unit_testing/yaml.test.js
Moves to PropTypes in order to check for keys that shouldn't exist but do. Sadly, this also implements a lot of the wonderful work of @MeaningOf42 and I am sorry about that.
Also, uses describe to label the tests as parts of testing a file for cleaner output.
> Test YAML with PropTypes

- _CodingChallenges/90-floyd-steinberg-dithering.md
My version of the challenge is written in python. As well as doing image dithering, it also makes a CSS file that can display the image without needing a HTML image tag. I'm not sure if I explained that very well, so I'll briefly show what my code does.
Checkout this page's source: [https://meaningof42.github.io/pointless-site/css_dithering/index.html](https://meaningof42.github.io/pointless-site/css_dithering/index.html)
Notice there is only a div tag in the html body. So how does the page display an image? Well CSS allows you to have an unlimited number of box shadows. Each pixel of the image is actually a box shadow of the first pixel which is the div element. Adding each box-shadow by hand would be infeasible, so I decided to write a python script to automatically convert an image …
> Added my version of coding challange 90.

- CodingChallenges/CC_94_2048/grid.js
- CodingChallenges/CC_94_2048/sketch.js
I've removed the unnecessary `direction` argument from the `transposeGrid` function
because transposing a matrix is not dependent on a direction and this might be irritating.
> CC_94_2048: Removed unnecessary direction in transposeGrid

- _jekyll/layouts/video.html
As requested by @shiffman and @meiamsome, contributions on multi-part videos are now only allowed for the first part (video `XX.1`). Each video in a multi-part series now lists the contributions made in the first video instead of its own, unless specified otherwise. To control how contributions should behave, refer tho this set of rules (only applies to multi-part videos):
- If a video doesn't contain the `contributions` property it shows the contributions made to the first video in the series (video `XX.1`).
- If a video already contains the `contributions` property it shows its own contributions.
- If a video should allow direct contributions, set `contributions: false`
> Multi-part videos should only allow contributions to the first part

- _CodingChallenges/50.1-circlepackinganimated.md
Add my contribution to Coding Challenge 50 now also to the website md-files.
Do I see that correct that contributions here always should go to part 1?
See also PR #190 
Reminder: it was this:
Fade out circles after time and use camera...
> Add (existing) contribution to Coding Challenge 50 (website)

- _CodingChallenges/102-2d-water-ripple.md
used 8 neighbors instead of 4, but otherwise same as Processing version (used to compare speed of canvas vs Processing)
> browser version of "2D Water Ripple"

- _CodingChallenges/050.1-circlepackinganimated.md
I implemented an alternative (but not necessarily better) method of circle packing based on a paper by Paul Bourke in which he describes using an infinite function that converges to the area of the space to be filled. I also added a number of bells and whistles in terms of displaying the result. Spacebar will toggle "2d" or "3d" mode--display as circles on a plane or spheres. Arrow keys rotate the result, "R" resets, and "P" toggles between orthographic and perspective perspectives.
Live demo: http://www.quillaja.net/circ_pack/sketch.html
Code: https://github.com/quillaja/p5-sketches/tree/master/circ_pack
> Added a community example to circle packing

- CodingChallenges/CC_112_3D_Rendering/CC_112_3D_Rendering.pde
Last row for rotationX had an extra 0.
rotationY was wrong. Issue #694
> Fixed rotationX and rotationY

- _CodingChallenges/121-logo-interpreter.md
Its my first open-source contribution in github, i am a little bit nervous.
i made this logo interpreter long while ago (3-4 months ago), i also added 'repeat' and 'repcount' commands. i think the results are pretty impressive.
> Contribution To Logo Interpreter Coding Challenge #121

- CodingChallenges/CC_125_Fourier_Series/P5/sketch.js
In the livestream a path array was made to draw the path of the point.
This, however, was not included in the final video, therefore some unnecessary code for the path remained in the code.
> Removing the rest of the path array

- unit_testing/package-lock.json
- unit_testing/package.json
- unit_testing/yaml.test.js
Makes tests check that a specified `web_editor` field exists, is on the right account and has an optional 1-to-1 mapping to a repository
> Enforce Web Editor existence, user & mapping to repositories

- unit_testing/yaml.test.js
Fixes the issue just seen in #825
> Fix the error message output for when a video should be a local link

- assets/css/2-base/_navigation.sass
The culprit is the nav element just under .navigation  as talked about in #904  
This changes it's width to 0% unless the nav-toggle is checked, which hopefully solves the problem.
**Note:** I have no way of building and testing jekyll site, so hopefully I got the sass-code right.
> Link doesn't work on mobile devices -fix

- _jekyll/includes/3-modules/video-card.html
- assets/css/2-base/_global.sass
fixes #837
Added aria-label attributes to video cards with a hidden span as fallback
> Add addtional info for screen readers

- _CodingChallenges/139-pi-collisions.md
https://editor.p5js.org/tht-jxny/full/RG9tqIJqN Fullscreen version for PI Collision Animation without using PI. To change number of digits modify line 41 to a mass thats a power of 100. I've created this animation before the CodingTrain Video came out based on 3Blue1Brown's video so its neither OOP nor can it deal with more than 4 digits (at least not my pc :D). To try more just reduce the initial velocity.
> Edit l.41 for digit count. Animation without using Pi

- _CodingChallenges/046.1-asteroids-part-1.md
I used gyroscope sensor to control the player and added some sound effects too.
**GyroDodge is more fun to play on mobile devices.**
play : https://anuraghazra.github.io/GyroDodge/
> Added Contribution To CC46 - Asteroids (GyroDodge)

- _CodingChallenges/145-2d-ray-casting.md
Added info for my example "wolfenstein 3d style raycasting with randomly generated mazes". This was inspired by a [video](https://www.youtube.com/watch?v=eOCQfxRQ2pY) by Matt Godbolt about how Wolfenstein 3D did raycasting in the ancient days.
keyboard arrow keys move player (also pressing at top, bottom, left, right of screen on touchscreen).
space toggles 3D/2D view, S toggles some statistics and viewing rays in the 2D view.
> added example to CC 145-2d-ray-casting.md

- _CodingChallenges/145-2d-ray-casting.md
- _CodingChallenges/146-rendering-ray-casting.md
CC 146 wasn't posted when I submitted my example to CC145, but is a much more appropriate match with CC146. See #1334 for the PR that originally added my example to C145. Sorry for the trouble.
> moved example from CC145 to CC146.

- _CodingChallenges/090-floyd-steinberg-dithering.md
Link to DHALF.txt: [https://github.com/SixLabors/ImageSharp/blob/master/src/ImageSharp/Processing/Processors/Dithering/DHALF.TXT](https://github.com/SixLabors/ImageSharp/blob/master/src/ImageSharp/Processing/Processors/Dithering/DHALF.TXT)
> Adding DHALF.txt as Community Reference for CC90

- CodingChallenges/CC_100.1_NeuroEvolution_FlappyBird/Processing/CC_100_1_NeuroEvolution_FlappyBird/Neural_Network.pde
Hello! I think there is a little error in 'mut' function of 'Neural_Network.pde' file in coding challenge 100. From my knowledge the if condition on line 69 should be:
`if(random(1) < rate)`
instead of:
`if(random(1) > rate)`
Suppose the rate is 0.9, then what our intention is to mutate 90% of the time. But according to me, the function is performing other way round right now i.e the probability that the random(1) > 0.9 is just 10%.
Also when I checked the P5 version of this coding challenge, I found the 'mutate' function correct there.
Here are the snippets from both the versions.
This snippet is from P5 version which I think is correct:
And this is from Processing version:
Correct me if I'm missing something here.
Cheers!
> Corrected mut function in Neural_Network.pde file

- _CodingChallenges/151-ukulele-tuner.md
A simple modification to display a pitch trail while tuning the ukulele. The AudioContext was not working as expected in the P5 web editor full/presentation view, so here is a link to the sketch: https://editor.p5js.org/originalang/sketches/NK3x9FZ_0.
> Ukulele Tuner contribution: Pitch Trail

- assets/css/1-tools/_vars.sass
I guess `letter-spacing` without px unit is invalid.
> Fix: invalid `letter-spacing` unit

- _CodingChallenges/026-supershape3d.md
I noticed that the spherical geometry video wasn't linked to on the supershape challenge page even though its mentioned in the video so I added it
> add link to mentioned video in CC26

- assets/css/2-base/_navigation.sass
As mentioned in Issue #1834 
$mobile breakpoint was not sufficient to stop the nav bar overflowing. Have updated to $tablet-big(:920px) for sufficient space (as of current nav layout).
> Update breakpoint for nav bar

- _CodingChallenges/097.2-book-of-pi.md
I found an extra space in `097.2-book-of-pi.md` which caused this [subpage](https://thecodingtrain.com/CodingChallenges/097.2-book-of-pi) not to build. Probably the testing should be extended so that such an error does not recur.
> Fixed format for CC 097.2-book-of-pi.md

- _Guides/core-contribution-guide.md
Since @shiffman is in the process of deprecating patreon for the coding train I thought it would be a good idea to change 'patron' to 'member'
> changed 'patron' to 'member'

- _jekyll/includes/2-base/footer.html
Since the new `back to top` has the same background color as the `shiffman.net` footer link I moved it from the far right to the far left, I don't if this is the best solution but it is the easiest.
Before ![Before](https://user-images.githubusercontent.com/45735850/68143928-805a5f80-ff00-11e9-9837-c7785f77de84.jpg)
After ![After](https://user-images.githubusercontent.com/45735850/68143949-88b29a80-ff00-11e9-8d89-a8fe0489d360.jpg)
Full footer after ![full after](https://user-images.githubusercontent.com/45735850/68143956-8f411200-ff00-11e9-9908-fe1cab203ebd.jpg)
> rearranged footer links

- _TeachableMachine/2-teachable-game.md
- _TeachableMachine/3-teachable-audio.md
- _TeachableMachine/index.md
- landing-page.html
As suggested in #1901 I added the Teachable Machine videos to the landing page and fixed the release dates for them to appear in the right order.
> Add Teachable Machine videos to landing page #1901

- _Tutorials/index.md
- assets/css/2-base/_typeface.sass
I think it is easy to overlook the links to the guest tutorials and the Teachable Machine videos, so I highlighted "guests" and "Teachable Machine":
> Add highlight for links to guest tutorials and Teachable Machine videos

- .github/pull_request_template.md
In #1902 it was pointed out that the labels are only available to maintainers so removing the line about it in the template. Sorry that was my bad I just assumed it was visible to everyone.
> Removing Label Line in Pull Request Template

- _Courses/ml5-beginners-guide/1.1-ml5-image-classification.md
- _Courses/ml5-beginners-guide/1.2-ml5-webcam-image-classification.md
- _Courses/ml5-beginners-guide/3.1-ml5-feature-extractor-classification.md
- _Courses/ml5-beginners-guide/3.2-ml5-feature-extractor-regression.md
- _Courses/ml5-beginners-guide/4.1-ml5-save-load-model.md
- _Courses/ml5-beginners-guide/5.1-ml5-knn-classification-1.md
- _Courses/ml5-beginners-guide/5.2-ml5-knn-classification-2.md
- _Courses/ml5-beginners-guide/5.3-ml5-knn-classification-3.md
Some `.md` files in the "ml5-beginners-guide" course linked to the repo on github.com which caused the buttons "Download Code" and "Live Demo" not to show up.
> Fix links to repo in ml5-beginners-guide

- Tutorials/Processing/11_video/sketch_11_9_BlobTrackingIDs_js/blob.js
- Tutorials/Processing/11_video/sketch_11_9_BlobTrackingIDs_js/index.html
- Tutorials/Processing/11_video/sketch_11_9_BlobTrackingIDs_js/sketch.js
This is a port to p5.js of the Blob Tracking code that goes with this video. I get asked for this a lot so thought I would port it and add it to the site. @violetcraze @gruselhaus not sure if there's a way to include on the actual webpage for this video (if there even is one!), but at minimum here it is!
> port of blob tracking to p5js

- _Guides/core-contribution-guide.md
When i tried to build the website on linux I had to use `sudo` so I though i would add that to the guide
> Add build command for linux to guide

- _CodingInTheCabana/003-hilbert-curve.md
https://edorfaus.github.io/coding-train-variants/CodingInTheCabana/Cabana_003_Hilbert_Curve/P5/
This variant starts by drawing an order-1 Hilbert Curve, then zooms out and keeps going, until it fills the entire canvas. To make the direction the curve is displayed in consistent, and the zooming easier, the sketch draws the curve in two directions simultaneously (at different speeds), starting from the bottom-left corner of the curve.
The code has some visualization control parameters at the top, but there's currently no UI for changing them.
-- It would be more of a shrug - I guess I don't mind if you really _want_ to share it, but it's not something I particularly care about (since I tend to avoid social media), so it wouldn't make me be happy.
> Contribute a variant of the Hilbert Curve sketch

- CONTRIBUTING.md
The old link doesn't work (404), so update it to point to the pinned issue for porting, since that contains an overview table that it says is updated automatically.
> Update overview link for contributing ports

- CodingChallenges/CC_022_JuliaSet/P5/index.html
- CodingChallenges/CC_022_JuliaSet/P5/sketch.js
- CodingChallenges/CC_022_JuliaSet/Processing/CC_022_JuliaSet/CC_022_JuliaSet.pde
- _CodingChallenges/022-juliaset.md
This code started out as a straight translation of the Processing code, just changing the use of the pixels array because it behaves differently. (And added the explanation comment about it.)
Then I added an optimization (with explanation comment), that I think changes the code little enough that it won't really be harder to follow along with - and speeds things up enough that it seemed worth it. It basically brings the sketch up from a frame rate of 0.4 in the web editor, and about 7-8 directly in my browser (I don't know why the difference), to about 50-60 in both. (Though it varies a lot with time as the sketch runs.)
However, I kept that as a separate commit, so if you disagree with me and would prefer the slower but less modified version, we can just remove that commit before …
> Add a port to p5.js of coding challenge 22: Julia Set

- TeachableMachine/2-teachable-game/P5/sketch.js
If the video is not removed, it causes new <canvas> elements to be added to the DOM constantly , this could cause a huge spike in memory usage
This is just a quick bugfix
> removed the flipped Video after classification

- CodingChallenges/CC_141_Mandelbrot_Pi/Processing/CC_141_Mandelbrot_Pi/CC_141_Mandelbrot_Pi.pde
It points to the sketch from an earlier coding challenge (CC 138: Angry Bird), and since there's no p5.js version of this challenge (yet), there isn't any correct link to replace it with.
> Remove an incorrect web editor link.

- _learning/nature-of-code/2.2-mass-acceleration.md
- unit_testing/yaml.test.js
fixes #2199 
They switched the api path to /editor from /api for most routes. More here: https://github.com/processing/p5.js-web-editor/pull/1106
> Fixing Web Editor API

- _CodingInTheCabana/004-worley-noise.md
Eventually these should probably make their way here but for now I am just going to link to the other repo so I can work on cleaning up and commenting the extra examples.
> Worley Noise: adding extra code examples in separate repo

- _jekyll/layouts/video.html
i noticed that `blank` leads to some unexpected actions that are remedied by `_blank` so i think it would be good to change it
> fixed potential bug with a tag opening in new tab

- _config.yml
Forked DownGit and added regex to only allow files from this repository. Fixes #2178 
New DownGit for CodingTrain: https://github.com/CodingTrain/DownGit
More about changes: https://github.com/CodingTrain/DownGit/pull/1
> Fixing Download Code

- Gemfile
- Gemfile.lock
- _config.yml
- _jekyll/includes/2-base/head.html
Adding a plugin for jekyll so that when a page link is shared, it has better information, on different social networks and communication channels
Add images of what it will look like from, using my page fork as an example. I leave related link
https://github.com/jekyll/jekyll-seo-tag
https://developers.facebook.com/tools/debug
https://cards-dev.twitter.com/validator
https://thecodingtrain.com/CodingChallenges/152-rdp-algorithm.html
https://nocheprogramacion.com/Tutoriales/064_Como_usar_Discord_Paso_a_Paso.html
discuss my english
**Instagram:** ALSWnet
**Twitter:** ALSWnet
**Youtube:** ALSWnet
> Data for SEO for easier sharing and being searched

- challenges/coding-in-the-cabana/005_marching_squares/P5_cave/sketch.js
This is a 1-character-delta bugfix for the cave generation code from the marching cubes coding challenge.
The `countNeighbors` function counts the number of 1's there are in a 3x3 grid centered at the given `(x, y)`. In this function, we iterate over neighbors at indices `(i,j)`. We only want to count real neighbors and not the node itself, so we should check that `(x,y) != (i,j)`. A small typo slipped in causing the function to check that  `(x, x) != (i, j)`.
> Small fix in cave generation with marching squares

- _CodingChallenges/012-lorenzattractor.md
Hi, 
I was re-factoring the code of my contribution and then I don’t know what happen to the “present” link sketch. It does not work anymore:
Broken link: https://editor.p5js.org/jcponce/present/JH7nMvdIC
However, the “sketch” link with code works: https://editor.p5js.org/jcponce/sketches/JH7nMvdIC
Anyway, I decided to create a new link for the sketch that works fine, and I will try to figure out what happened to the previous sketch.
Could you please update the link? Thanks.
https://editor.p5js.org/jcponce/present/WUmXSTPvr
**Instagram:**
**Twitter:**
> Fixed broken link for my previous contribution

- 404.md
- _jekyll/includes/2-base/navigation.html
- _jekyll/includes/3-modules/hero-item.html
- landing-page.html
`target="_blank"` is open to click-jacking attacks, so adding `rel="noopener noreferrer"` is a way to prevent that.
As an aside, both `noopener` and `noreferrer` prevent this vulnerability, though `noopener` won't work with some legacy browsers, and newer browsers just ignore `noreferrer`, so adding both is the current accepted best practice.
> add rel attribute to prevent click-jacking

- _CodingChallenges/058-earthquakeviz3d.md
This PR is related to #2615 in which I have displayed number of cases on a 3D map by using the `height` property of the boxes 
Happy Hacktoberfest 2020
**Link to live project, video, or image:** 
https://editor.p5js.org/JacobGeoGeek/full/RjkCQVEU8
> Display the # of COVID cases on a 3D map

- _CodingChallenges/094.1-2048.md
**Link to Demo:**
https://clone2048.netlify.app/
Regarding #2615
> 2048 clone with same ui and colours as original

- learning/ml5/8.4-cnn-image-classification/mask/index.html
Noticed that the html for the mask example on ml5 8.4 was missing.
> adding missing html in ml5 8.4

- _CodingChallenges/108-barnsley-fern.md
Just a quick URL fix for the rainbow fern community contribution.
> Fix Broken Link for Rainbow Fern
